### ISSUE TITLE
[Enhancement] Multiblock Heat/Steam Generator

### ISSUE THREAD

**Issue by MagisterXero** [aidancbrady/Mekanism#1224]
Currently, heat generators are a very low source of power generation (even given fuel sources), and they seem like they are a generator which has potential as a multiblock type generator. I'm just kind of throwing this idea out there to see if it catches any attention but here is the basic idea:

Think "Dynamic Tanks" kind of style for the multiblock capability, allowing for varied sizes of the generator. But instead of using the dynamic tank blocks as part of the outer frame, you'd instead use a series of heat generators. This would essentially make the multiblock capable of being a lava tank, but with the ability to generate power directly from it still when turned on.

Surrounding the tank in lava (perhaps instead of a "valve", we'd have a "power outlet") that would take into consideration the number of "molten" sources nearby. (Expanding up to 2 blocks outwards in all directions perhaps?) Each "Source" block would generator X amount of power, while a flowing block would generator X/2 power. 

Conventional fuel sources, such as coal or anything that currently powers the heat gens would still work, but ultimately the lava would be the main source of fuel. It would also be an interesting concept when combined with Biome modifiers (much like the salination plants do), causing lava to be more or less effective, or even unnecessary for small generation amounts, in certain biomes. 

This would add in a more advanced sort of heat generator that acts as a step up from the basic one, and would be much more efficient in generating power. And as a side point it would be a tank that stores lava, or other "fluids", which brings me to the next part. Because heat + water generates steam, it would be interesting to allow for water to be stored in the generator via the valves/pumps/etc. But due to the heat inside of the tank, it would be converted into steam that is usable elsewhere (a steam generator perhaps). 

Ultimately the multiblock would only have 1 primary purpose at a time, which would be limited to whatever is being pumped into it. Lava would turn it into a full time heat generator, while water would turn it into a steam producing source, powered by the nearby lava outside. This would negate its power output, or just lower it to a point where it isn't outputting much at all, because the overall temperature would be fluctuating due to the water being pumped into it. 

This is just a thought I'm throwing out there, since it gives way for the possibility of a rather unique method of generating steam, or simply utilizing something that works well early game, but is redundant in mid to late game. We might see more people using those heat gens again!

**Comment by Saizetsu** [comment]
If you run steam through it then you'll need it to be pressurized (for the sake of science in some way) or just run steam through it with electricity powering its turbine granted that causes the issue of will it produce more than it consumes? Yes it can given enough steam.

Honestly you should also consider Geothermal power as well, deeper down the greater the heat more power, but we use steam even now as a massive power source infact that is what we use in nuclear plants. Steam, just make it modular like most of the mekanism machines.

Give us tools to make it produce more power (And a possible chance of steamsplosions) Parts or pieces to control it make it so we can recycle the water that comes from it, not enough to repower it but enough to help a loop feed.

**Comment by aidancbrady** [comment]
I am now working on this in the v9 branch if anyone would like to keep up with my progress. I'm starting with the Industrial Turbine, whose design I may end up slightly changing, but I also plan on implementing the Thermoelectric Boiler.

**Comment by unpairedbracket** [comment]
Cool! I was going to do some work on this over Christmas, but it's been a while and I couldn't remember how to un-hide the unfinished stuff that we removed to release v8. I'm looking at attempting to port to MC1.8 again, now that the scene seems to be moving that way generally. I'll try and keep merging changes from this into the 1.8.9 codebase as I'm updating it.

**Comment by aidancbrady** [comment]
@unpairedbracket, that sounds awesome!  I'm having fun developing turbines using the new multiblock framework, I'll provide some screenshots once I have a few things finalized; they're by far the most complex multiblocks I've worked on yet.  Once we have the heat conduits added back in we'll have added a whole new dimension to Mekanism.

How far did you get to completing the boilers back when you started them?  I'd like to work on boilers once I finish these turbines, and I'm not sure if you'd consider the work salvageable or if I should start fresh.  I won't touch the code if you want to work on it some more, otherwise just give me some direction towards your ideas.

For early/mid-game energy generation I'm thinking of adding some kind of single-block steam generators and miniature boilers, if I have the time.

I'm also going to try and extend the work you did on item/energy/etc teleportation to use my new frequency system I developed for teleporters- I think it could work quite nicely.

Do you have any other ideas for the release?  Chunk-loading is something we've never really dabbled in.  Regardless, let me know if you have any questions and I'd be happy to help.

**Comment by unpairedbracket** [comment]
I think my work on boilers was pretty preliminary, and I was thinking I'd have to go back and redo a whole bunch of it anyway, because it was pretty inefficient. If you want to get to work on it I'd say go ahead; I'll be kept busy enough with 1.8.9 and real life as it is.

I think the way I had the boilers working was that all the frame blocks would share a temperature in some kind of delegate object and heat would transfer between that and the water (Custom temperature-sensitive FluidTank subclass?) I'd think the water could use heat it absorbs to raise its heat up to 100°C (amount of heat this would take being proportional to the amount of water in the tank, then use any excess heat to convert some of this 100°C water into steam. The IFluidHandler method to inject ΔV more water into the tank (containing V<sub>i</sub> water already) would take the temperature from initial temperature T<sub>i</sub> to final temperature T<sub>f</sub> = T<sub>i</sub> - ΔV/(V<sub>i</sub> + ΔV) (T<sub>i</sub> - T<sub>ambient</sub>) [adding water at ambient temperature reduces the tank's temperature towards ambient]

The early-game boilers/steam generators sound like a good idea, so there's a bit of a feeling of progression through the industrial technologies.

Using the frequency system sounds like a good idea too - it would be good if we could keep the "creative frequencies" that allow infinite production of a fluid, gas, or energy (acting like a creative energy cube), and the ones that allow us to use these blocks as fluid/gas/energy/item void blocks as well (that might be a good thing to make an upgrade for?); these are all quite helpful in development as well as ingame.

Other than that I think chunkloading is potentially an interesting thing to look into, I'd be interested to see if we can make it different enough from the other options out there to make it worthwhile.

**Comment by sinspawn1024** [comment]
**[Thermoelectric Generation Matrix]**

After reading the above, I’d like to propose a multiblock energy conversion device that would be both customizable and scalable from very early-game all the way to end-game power production. Its game mechanic is reminiscent of Big Reactors (BR), but is unique to and consistent with Mekanism. I call it the Thermoelectric Generation Matrix (TGM). I apologize, this is about to be a long explanation, but I promise it'll be worth the read.

**Overview**
The TGM gamifies real technologies and thermodynamic principles. In short, the TGM inputs a thermal fluid – a hot liquid or gas – and outputs RF. Early-game TGMs use Lava, mid-game TGMs use Exhaust Gas, and end-game TGMs use Steam from reactors. The selection and arrangement of constituent blocks customizes the TGM to handle various heat sources.

The exterior consists of a Controller, Casings, Glass, and various Ports; the interior consists of Mass Transfer Pipes, Heat Transfer Tubes, and Thermoelectric Cells. Mass Transfer Pipes determine how much fluid the TGM can handle; Heat Transfer Tubes determine how efficiently heat is converted to RF; and Thermoelectric Cells determine how much RF can be output and stored. Each of the three interior component types comes in basic, advanced, elite, and ultimate tiers. This is allows TGMs to scale all the way from second day power generation all the way to the end-game Fusion Reactors.

**Comment by sinspawn1024** [comment]
**[Thermoelectric Generation Matrix]**

**Formation**
The TGM adds the following blocks to the mod:
•	Generator Casing – TGM structure blocks
•	Generator Glass – TGM aesthetic blocks
•	Generator Controller – UI block 
•	Generator Power Port – energy output 
•	Generator Combustor Port – burns fuels to create Combustion Exhaust
•	Generator Fluid Port – fluid input/output
•	Mass Transfer Pipe (basic/advanced/elite/ultimate) – transports thermal fluids through the TGM
•	Heat Transfer Tubes (basic/advanced/elite/ultimate) – extract heat from thermal fluids
•	Thermoelectric Cell (basic/advanced/elite/ultimate) – converts heat to power
•	(optional) Generator redstone port – allows TGM to be controlled by redstone
•	(optional) Generator computer port – allows ComputerCraft/OpenComputer control
The Thermoelectric Generation Matrix is formed similarly to the Energized Induction Matrix, but with stricter construction rules (like multiblocks from BR). In order to be valid, the TGM must follow the following rules:
1.	The multiblock must be a cuboid.
2.	The edges must be Generator Casings.
3.	There must be exactly one Generator Controller placed on a face of the structure.
4.	The rest of the exterior may consist of only Generator Casings, Generator Glass, and Ports.
5.	The interior may contain only Mass Transfer Pipes, Heat Transfer Tubes, Thermoelectric Cells, and/or Lava source blocks (or optionally other hot things, e.g. blazing pyrotheum, etc.).
6.	Mass Transfer Pipes must in a straight line from one face of the TGM to the opposite face, and begin and end with Fluid Ports on the exterior faces (or a Combustor Port; see later).
7.	Heat Transfer Tubes must be directly adjacent to at least one Mass Transfer Pipe.
8.	(optional) Thermoelectric Cells must be placed so that they touch one another on at least one face, with at least one touching a Power Port. (This is so that they conduct energy between one another to the power port.)

**Comment by sinspawn1024** [comment]
**[Thermoelectric Generation Matrix]**

**Progression**
_Early Game_
The entry level TGM is essentially a multiblock version of the Heat Generator, but better. A hollow cuboid is built with Casings, one or more Thermoelectric Cells are placed inside, and the remaining space is filled with Lava. Like a heat generator, for every face of a Thermoelectric Cell in contact with the Lava, a fixed amount of RF/t is produced. 

_Mid Game_
When expanding the amount of Lava in the TGM is no longer sufficient for growing power needs, it will become necessary to move to a more sophisticated TGM: one that burns fuels. After removing the Lava from the inside of the TGM, the interior is filled with Mass Transfer Pipes, Heat Transfer Tubes, and Thermoelectric Cells. At one end of each Mass Transfer Pipe is placed a Combustor Port with a Fluid Port on the opposite end. After the multiblock forms, accessing any of the Combustor Ports reveals a UI with an item and two fluid inventories. Combustible items, liquids, or gases can be pumped into a Combustor Port, which will burn them and produce a certain amount of hot Exhaust Gas, which in turn is consumed by the TGM resulting in power. Better fuels produce more and/or better Exhaust Gas, resulting in more power. Optionally, when a Combustor Port is operating, particles can be emitted from the Fluid Port at the opposite end, mimicking exhaust leaving.

_End Game_
Ultimately, the real point of this is to give something that is capable of handling the amount of steam produced by a Fusion Reactor, something that, at the time of writing, not a single mod is capable of doing. The Combustor Ports must be removed and replaced with mere Fluid Ports, and Steam from the source of choice is pumped into Fluid Ports. The steam is converted to RF, and an equal amount of water is ejected from the Fluid Ports on the opposite end of the TGM.

**Comment by sinspawn1024** [comment]
**[Thermoelectric Generation Matrix]**

_Under the Hood_
Each type of thermal fluid is associated with a “nominal energy density,” i.e. RF/mB. This is the maximum possible energy that can be extracted from a particular thermal fluid. For example, Steam might have a nominal energy density of 14 RF/mB, meaning that if you pumped 2000 mB/t of steam into a perfectly optimized TGM, the power output would be 28,000 RF/t (comparable to a BR Turbine). 

The mechanic for determining performance is simple. The controller would have two internal fluid tanks (input and output), and a power buffer. If the structure is valid (see rules), then the behavior is calculated when the TGM forms. 

The size of the input/output tanks is determined by the number and type of Mass Transfer Pipes in the interior: more and/or bigger pipes equal bigger tanks. Every tick, the Controller multiplies the nominal energy density of the type of fluid in the input by the amount in the inventory, then consumes the fluid, resulting in a nominal thermal input (RF/mB * mB = RFth). Thus, the Mass Transfer Pipes determine the maximum feed rate through the TGM.

The conversion efficiency is determined by the Heat Transfer Tubes. Each tier (basic/advanced/elite /ultimate) is more efficient than the last. The efficiencies of each Heat Transfer Tubes block are averaged, and the nominal thermal input is multiplied by the average efficiency, resulting in the power production (RFe). 

Finally, the maximum power output and power buffer size are determined by the Thermoelectric Cells. Each face accepts a certain amount of heat. Multiplying the maximum heating rate of that particular Thermoelectric Cell by the number of Thermoelectric Cell faces adjacent to Heat Transfer Tubes results in the maximum power output. Any power production in excess of that is voided, and what remains is put in the power buffer.

**Comment by sinspawn1024** [comment]
**[Thermoelectric Generation Matrix]**

**Balancing the TGM**
As noted, the TGM scales from early- to end-game. For easier entry early on, the recipes for the exterior blocks (Casings, Glass, Controller, and Ports), as well as the basic Thermoelectric Cell should be very cheap. The four tiers of interior parts for the TGM should be balanced in their recipes and performance with the following tech levels in mind:

•	Basic – intended for use with Lava and low grade fuels like Wood or Coal.
•	Advanced – intended for use with advanced fuels, like Hydrogen or Oil.
•	Elite – intended for use with a fusion reactor with an injection rate up to 4
•	Ultimate – intended for use with a fusion reactor with an injection rate over 4

This huge span of technical capability means that the cost of progression must grow exponentially, as the resources available to a player grow so quickly with energy availability. This is particularly true of someone with a Fusion Reactor. The minimum injection rate of 2 still provides the player with 2 million RF/t, enough for multiple maxed out Digital Miners and a max speed ore quintupling system. So resources can be expected not to be an object.

To make the progression from an Elite TGM to an Ultimate TGM an actual challenge, I suggest adding a new alloy: Antimatter Alloy. This ultimate alloy is created in an upgraded version of the Metallurgic Infuser: the Mattergic Inverter. The machine is made by a crafting together a Metallurgic Infuser, two Laser Amplifiers, an Ultimate Energy Cube, and four Atomic Alloys around a Steel Casing. 

The Mattergic Inverter would infuse items with Nether Stars, which can either be feed in as blocks to give 10 uses, or cannot have their yield increased at all. The machine would requires 500 million RF per operation, however the energy could only be transferred to the machine by Lasers. Two stacks of lasers feeding energy into the Mattergic Inverter would consume 256,000 RF/t, and would produce an Antimatter Alloy in approximately 90 seconds.

**Comment by aidancbrady** [comment]
Boilers and Turbines are now complete for Mekanism v9- it's been a major project, but I'm happy it's complete :)
