### ISSUE TITLE
Electrolytic separator -> gas generator crash

### ISSUE THREAD

**Issue by Magnusri** [aidancbrady/Mekanism#2110]
I am having trouble with Mekanism Version 1.7.1.127 all the way up to 7.1.2.157.

The problem seems to be at mekanism.common.FuelHandler.getFuel(FuelHandler.java:31).

Error log following:
http://pastebin.com/mLJVCMEq

The crash can easily be re-produced, and includes(but not restricted to);
Electrolytic Separator - Mekanism
Bio Generator - Mekanism
Reservoir - Ender IO
Capacitor Bank - Ender IO
all connected by Universal cables - Mekanism.

This setup works just fine until you add power to the circut, which makes the machines start up. This crashes the client, and the server. Any player moving into the area will crash the server later on.

Magnus

**Comment by Greylocke** [comment]
I would suggest making a new test world and test pack with JUST Mekanism and EIO. Set up your test systems, and see if you still get a crash. If the problem goes away, then the source of the problem is not with Mekanism or EnderIO. 

If the problem still exists, please include a snapshot of the system in your test world that causes the crash.

From personal experience, Mek and EIO work very well together.

**Comment by aidancbrady** [comment]
True, I am unable to reproduce this on my own end.  If you can confirm that there is a direct interaction issue that roots back to Mekanism, I will reopen the issue and take a look.
