### ISSUE TITLE
Aesthetics: Pipes should not connect to Portable Tank's sides

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#2135]
Since Portable Tanks have well defined input/output faces (i.e. up and down), mechanical pipes should avoid connecting to the sides of a Portable Tank.
![2015-02-16_23 27 41](https://cloud.githubusercontent.com/assets/6743303/6221999/6c8b462e-b633-11e4-83d0-0f6071dde36e.png)

Not gamebreaking at all.

**Comment by aidancbrady** [comment]
In prerelease the tanks originally worked that way - only allowing connections on the top and bottom. However, I later realized that the tank could also be used as a Mekanism-based Fluid Transposer (filling/emptying buckets), and that would require both a fluid input and two transporters being connected to the top and bottom in order to import/export fluid containers. BuildCraft tanks also allow for pipes to connect to their sides and modify their contents.
