### ISSUE TITLE
Minechem/Mekanism compatibility

### ISSUE THREAD

**Issue by hilburn** [aidancbrady/Mekanism#2176]
Regarding #2169 and jakimfett/Minechem#695

All of our elements are registered as fluids - as I understand it, the Rotary Condensentrator can convert fluids to gasses but only for the registered fluid for said gas in the Gas Registry. The issue is then that we have particular properties that we require from our chemical fluids, and you have different requirements from yours, so neither can really just use the other's fluids to get the compatibility to work.

As I see it, the only real way to enable this is if there was a secondary mapping where we could register eg. 1,000mB Minechem Hydrogen -> 500mB of Mekanism Gas (the relative proportions would have to be worked out in order to maintain some semblance of balance) in order to enable the conversion

Thoughts?

**Comment by Moorleiche2k** [comment]
Well, as for balancing, some thoughts:
One has to consider in which environment / modpack it will be used. Since you cannot cover all modpacks, it should be, obviosuly, possible to use a config file. So you can distribute the issue of balancing to the rewsponsible modpack creators and also offer the option for server owners to adjust the balance themself. Their feedback might help to find a balanced standard of conversion.

As for the technical part, i am not that in depth (and as such this might be wrong and / or not helpful). But maybe forge offer possibilites to use a standardized API which itself could check for both mods. If not, i guess a standardized properties of the fluids used by both mods could ensure compatibility.

**Comment by hilburn** [comment]
Yes - we would have a config.
The rest, no, Forge has no "FluidDictionary" or equivalent and I don't think it would be a good idea for either mod to use the other's fluids - they have different purposes and it would also prevent the aforementioned configurable balance.

**Comment by aidancbrady** [comment]
Closing this on my end as it seems it's being looked into by the MineChem team. I don't have any plans of doing direct integration on my end, but in the case MineChem wants to be compatible I would be happy to make whatever API changes are necessary.

**Comment by hilburn** [comment]
@aidancbrady I am on the minechem team and discussing those changes is why I opened this issue...

**Comment by aidancbrady** [comment]
Oh, I was assuming it was just jakimfett.

**Comment by hilburn** [comment]
Ok, well would it be possible to add that registry of Fluid->Gas recipes to enable our fluids to work with the condensentrator? Because that's pretty much the only way I can think of to enable it working

**Comment by Kodos-Atoz** [comment]
@aidancbrady Is this still being considered? Would love to see Mekanism and Minechem Hydrogen, Oxygen, etc be interchangable.

**Comment by callous4567** [comment]
Would love it too
