### ISSUE TITLE
Mekanism error with Gas API in Galacticraft

### ISSUE THREAD

**Issue by SportsFan10** [aidancbrady/Mekanism#2265]
This may seem a bit like a Galacticraft issue and if that's the case I will bring it up with them.  Figured I'd bring it here first since the issue never occurred until updating to mekanism v8.  

Mekanism V. 1.7.10-8.0.0.188
Forge: 7.10.85.1291
Galacticraft V. 1.7-3.0.8.265

I believe the issue comes in where I have my ore processing set up.  I'm using Galacticraft O2 collectors to send oxygen to my purification chambers.  In the Crash log it seems that there is an API error?  
Crash Log: http://pastebin.com/5fZnU0jW

Like I said this very well could be a Galacticraft problem if so I will bring the issue to them.
Thanks,
-Nick

**Comment by SportsFan10** [comment]
Edit: Seems to be more like an updated needed on Galacticraft's side I already opened an issue with them as well.

**Comment by radfast** [comment]
Yes, it's an update that was needed on Galacticraft's side, sorry I hadn't realized we were so out of date before, I don't know why no other player spotted this.

Please excuse closed issue #2267 : that was my bad, in a panic because Mekanism v8 is about to be released and I thought this was a very recent API change.
