### ISSUE TITLE
Extreme lag while scrolling through NEI from all the portable Tanks in V8

### ISSUE THREAD

**Issue by crunkazcanbe** [aidancbrady/Mekanism#2266]
There is also so much lag when scrolling through the creative tab for mekanism that it gets stuck half way through scrolling , and will not go any further . This is from all the portable tanks BTW .

**Comment by halvors** [comment]
I can confirm this, probatly because of custom item renderer.

**Comment by unpairedbracket** [comment]
I'd thought about putting in a config option to disable all the tanks - would it be better to have an NEI subset you could disable? Or would that not help?

**Comment by crunkazcanbe** [comment]
Yes a option to disable the viewing of them in NEI, and the creative tab for Mekanism would be nice in the config . Not totally disabled like you could still craft them , but just not viewable .

Thank you!

-Crunk

**Comment by aidancbrady** [comment]
Added config! :)

**Comment by crunkazcanbe** [comment]
Thank you. :)

**Comment by halvors** [comment]
This is still a problem, think there should be an more automatic solution. Without the need to deal with config files.

**Comment by crunkazcanbe** [comment]
Well when i turned tanks off in config the prob was 100% fixed . So i don't know whats causing your problem .

**Comment by usafphoenix** [comment]
default config setting should probably set the tanks to disabled in NEI and creative mode. as it's only really a single item that can be crafted, having (potentially) hundreds load up in NEI or creative menu is useless (except for checking for potential rendering errors that may arise in-game), but for the normal user, prefilled-tanks should probably be disabled. unless theres a good reason otherwise that i'm missing
