### ISSUE TITLE
This is actually a question Due to FPS lag

### ISSUE THREAD

**Issue by crunkazcanbe** [aidancbrady/Mekanism#2319]
What is CTMRenderer also when disabling MachineEffects what exactly is that disabling ?
Whats OldTransmitterRender too if you dont mind telling me . I am trying to reduce FPS lag what do you recommend me disable in the configs . Is there any advantage in me adjusting ClientUpdateDelay ?

I know I am probably going to get stoned for this, but I didn't know where to reliably get these answers from .

I do have one suggestion , and that is to allow a option in the config to change the amount of any one upgrade . This would help modpack DEVS instead of just 8 being the max what about a config option to allow you to put 10 or more of the same upgrade in? Also the option to allow a machine to only be able to take lets say 4 upgrades as the max or a option to totally disable the upgrades altogether .

Thank you!

-Crunk

**Comment by aidancbrady** [comment]
1. CTMRenderer is the renderer we use for connected block textures.  This will not consistently improve FPS, though it may improve overall client-side performance if you disable it (at the loss of connected textures of course).
2. By disabling MachineEffects you are disabling the particles coming out of active Mekanism machinery as well as the lighting effect.
3. OldTransmitterRender will not use the new intelligent transmitter render that doesn't render sides when  it isn't necessary.  This shouldn't necessarily improve performance, it's really in the config for those who prefer the old render.
4. ClientUpdateDelay is a delay that defines how often a Mekanism machine can change from its on to off state.  Because the switch between on and off forces a lighting and render update (assuming MachineEffects is enabled), increasing this number will make sure that your machines don't flicker often (when receiving varying power for example).

What you speak of can be accomplished by changing the "UpgradeModifier" property, which defines how effective upgrades are on machines.

Hope this helped!

**Comment by crunkazcanbe** [comment]
This sure did help man. I appreciate it very much . There is a strange crash that your mod is causing with Thaumic Energestics mod http://pastebin.com/Wc72aypA . Mek Version 7 Did not cause this .
