### ISSUE TITLE
Issue with micdoodle8 galacticraft mod

### ISSUE THREAD

**Issue by Suikju** [aidancbrady/Mekanism#2359]
I got every time a crash, when i tried to connect the electric seperator, which produce deuterium and oxygen with any other machines which needs oxygen. There is a generally  problem to connect any gaseous needed machine with mekanismengines. Downgrading is a temporary solving. But i dont want to abandon the fusion reactor. This is one of my favorite machines in this mod :I. Maybe you could fix that. 
I'm using the latest galacticraft mod 1.7-3.0.10.298

Thanks for your work.

**Comment by aidancbrady** [comment]
Galacticraft needs to update the mekanism API.

**Comment by Suikju** [comment]
Ok, thanks.

**Comment by radfast** [comment]
@Suikju please post your full crash report - that version of Galacticraft should be compatible with Mekanism v8, maybe something else is going wrong here

------------------------------------------------------------------

@aidancbrady  I understand you have a lot to cover at the moment with this exciting update to v8 and a huge number of issue reports in the past few days, but:

* it seems obvious your v8 API for IGasHandler ought to include legacy compatibility for your v7 API which you can do with minimum effort https://github.com/aidancbrady/Mekanism/issues/2267

* @unpairedbracket already offered there to look at this so I am hopeful

* you can't expect all other mods to "insta-update" on the same day you release v8 - and even though we have in fact updated Galacticraft (or I think we have ... waiting on that crash report from Suikju though) we can't guarantee that players will update other mods simultaneously with updating their Mekanism version, players may be happy with an existing version of another mod for ther reasons

* updating to your new gas API also breaks compatibility with v7 --- resulting in a situation where if a player updates their Galacticraft but not their Mekanism then they get crashes
* it seems Galacticraft is not the only other mod affected: https://github.com/aidancbrady/Mekanism/issues/2228

At Galacticraft we have always aimed to be very good friends with Mekanism - you know better than I do of the original teamwork on UE, shared open source principles, and generally because the two mods partner very well together for players.

Please can I suggest that you or @unpairedbracket  make the simple changes needed to fix this, instead of 'the other mod must update' response.

As mentioned above, in fact (!) I thought we already did update in Galacticraft 3.0.10.298  -  purpose of my comments above is that that has broken compatibility with Mekanism v7 and I'd really like to restore dual-compatibility with Mekanism v7 and v8 (also to have older GC versions, which many players will still be using, compatible with Mekanism v8).

See also:

https://github.com/micdoodle8/Galacticraft/commit/aa355c70220891f71a9547f4da7b8551bfdd209e
https://github.com/micdoodle8/Galacticraft/commit/4774c8d54cde9e4d11bfa85677e8c70b9ee705f7
http://wiki.micdoodle8.com/wiki/Compatibility#Mekanism
(We are pointing players correctly in the documentation, but the 95% majority of players don't read it)

**Comment by Suikju** [comment]
here is the crashreport if it helps
![unbenannt](https://cloud.githubusercontent.com/assets/11639581/6823203/4938c8c0-d2e6-11e4-96fb-8cf693eaf29a.PNG)

**Comment by radfast** [comment]
Thank you this may be an issue on the Galacticraft side, we'll look at this urgently and ask the Mekanism guys for their help if needed.

**Comment by Suikju** [comment]
i only use the latest version from mekanism (8.0.2.199) and galacticraft (3.0.10.298)

**Comment by radfast** [comment]
Update to Mekanism 8.0.2.201 should fix this, I think - if anyone else has the same issue.

**Comment by Suikju** [comment]
I updated it to 201, but the problem is still there

**Comment by Suikju** [comment]
i can converte the crashreports to images if you need. I tried various builds. heavy water will be pumped in electric seperator: Deuterium and Oxygen will produced. Connecting oxygen output with oxygen tank (galacticraft machine) -> Crash.
Normal water with electric seperator -> seperate into the two gases. Connecting oxygen output with oxygen tank -> same crashproblem.
I tried to replace the pressuretube by mekanism with oxygentube by galacticraft -> another crash.

**Comment by radfast** [comment]
@Suikju that's fine - the crash report you posted on the Galacticraft issues list gives enough information.  This appears to be a technical problem with the way we have implemented Java "reflection", it looks like I'll probably have to do it two different ways for the two different versions of Mekanism API even though @unpairedbracket has kindly included legacy compatibility which will help most mods.  Please be patient, we will aim to get a fixed version of Galacticraft out within a few hours.

**Comment by radfast** [comment]
For anyone else affected by this, please update your Galacticraft to 3.0.10.300 for full Mekanism v.8 compatibility.

See also: http://wiki.micdoodle8.com/wiki/Compatibility#Mekanism
