### ISSUE TITLE
Client Crash when use Portable Teleporter with QuantumSuit from IC2

### ISSUE THREAD

**Issue by Steelpower900** [aidancbrady/Mekanism#2368]
http://pastebin.com/2ECexrJj

**Comment by aidancbrady** [comment]
Not Mekanism-related.  Still a strange error, though.

**Comment by lehjr** [comment]
Also happens when using the portable teleporter wearing the armor from Modular Power suits:
http://openeye.openmods.info/crashes/9c06e6c59adaae25475d1b8aa0f40e9b

This is from testing Mekanism in a dev environment with quauntum suits (because I didn't have a deobfuscated version of MPS handy) : http://pastebin.com/CTNNu6Ep
