### ISSUE TITLE
Feature Request - Reset the fluidic plenisher with a redstone pulse

### ISSUE THREAD

**Issue by bshelden** [aidancbrady/Mekanism#2376]
I would like to be able to reset the fluidic plenisher so it'll rescan and re-fill the area it's responsible for.
This will enable me to use the world as a transfer tank for fluids for various purposes.

A simple method for this is to make the fluidic plenisher redstone sensitive and have it re-scan when activated in that manner.

My specific use case is in tandem with the liquid absorber from RF Tools which absorbs liquids from the world.

**Comment by aidancbrady** [comment]
Shift-right click the plenisher with a configurator :)

**Comment by Greylocke** [comment]
The concept is to have an **automated** way of resetting the Plenisher.

Considering his example, the plenisher would fill his "ravine tank", then, once full, would stop filling. Now a pump starts removing the liquid in the "ravine tank". Eventually the ravine will dry because the Plenisher never rechecks to see if the RavineTank needs to be refilled.

But if the Plenisher would rescan the area upon receiving a redstone pulse, then a clock could easily drive the Plenisher, which would keep the RavineTank filled.

**Comment by laz2727** [comment]
Right now, you can either emulate the shift rightclick or just use a bc
floodgate, which fills automatically.

**Comment by aidancbrady** [comment]
Good thinking.  Reopening...

**Comment by aidancbrady** [comment]
Alright, I've added this functionality via ComputerCraft peripheral integration, hopefully this serves as a good compromise :)

**Comment by aidancbrady** [comment]
For reference, call "reset" on the Electric Pump or Fluidic Plenisher to reset the calculation.
