### ISSUE TITLE
Solar Evaporation tower odd bug 

### ISSUE THREAD

**Issue by yepidoodles** [aidancbrady/Mekanism#2433]
Not a huge issue, but I started building one of the towers and it formed without being finished. It had a hole in the side and no solars on top - It's not a massive issue as it still doesn't work, but it's really strange and therefore decided to report it

![2015-04-01_06 43 42](https://cloud.githubusercontent.com/assets/10975665/6935313/6bda6da2-d83b-11e4-9bb1-1ff7f9a343c9.png)

![2015-04-01_06 46 41](https://cloud.githubusercontent.com/assets/10975665/6935316/740f7490-d83b-11e4-8a23-70f7a290264f.png)

![2015-04-01_06 47 12](https://cloud.githubusercontent.com/assets/10975665/6935317/791fa464-d83b-11e4-9f51-a21bec8ff14c.png)

And once the hole in the side is filled, it de-forms again.

As I said, it doesn't really effect anything, but it's weird and may cause issues in the future

Thanks :)

- Alice

EDIT: Just remembered that the controller is supposed to go at the top - but the tower still should not act like this.

**Comment by aidancbrady** [comment]
Solar Evaporation Plant doesn't necessarily need the controller to go on top, and it doesn't need solars either for the multiblock to form.  The hole thing is strange, though.

**Comment by Itchiha** [comment]
i've had something simelar, the tower forms when unfinished but when i finish the tower it deforms. i can place all blocks expept for 1.
![2015-08-05_13 31 41](https://cloud.githubusercontent.com/assets/13506198/9084709/92045846-3b76-11e5-9a50-64276176f56f.png)
if i place the remaning block it deforms, any tips?
![2015-08-05_13 31 45](https://cloud.githubusercontent.com/assets/13506198/9084722/ac9fe878-3b76-11e5-8ae1-a76f8446b044.png)

**Comment by Itchiha** [comment]
I got it working, had to place it 1 block under the upper ring.
![2015-08-05_13 42 26](https://cloud.githubusercontent.com/assets/13506198/9084873/ff1eeec2-3b77-11e5-9712-49555378a6ab.png)
Seems some kind of bug with the controller and the evaporation blocks 1 above the controller to the right.
i moved the controller 1 level at a time and each time the location of the bugging block moved to, till the location it is now because there is no evaporation block to its upper right.
(Hope it clear to you, my englisch might not be the best.)

**Comment by aidancbrady** [comment]
Fixed!
