### ISSUE TITLE
electrolytic separator

### ISSUE THREAD

**Issue by wandersonbraz** [aidancbrady/Mekanism#2542]
hello I make a jetpack and before did hydrogenio separator and oxygen fed with energy with water but it does not generate gas some as not image what and need to do and some bug mod

http://imgur.com/QXVK18X

**Comment by tgstyle** [comment]
What Forge version are you using? I cannot get it to work on Forge 1373. It works fine with 1352 and below.

**Comment by RAWRwins254** [comment]
I too am having issues on 1373 Forge.... Brine and Liquid Lithium production no longer works... in fact, no gas/liquid gen works. will try to revert to 1270 and see if that fixes it.

**Comment by wandersonbraz** [comment]
with these attempts ended up ruining my modpack am then recreating with the same 1352

**Comment by vixblu** [comment]
I rolled back to Forge 1291 (if you also have Extra Utilities in the pack, you need to use v1.23 instead of 1.24a--> the last one requires Forge 1355), and it didn't ruin anything in my world or mod mix, but it's always a good idea to back up before making changes :-) 

I'm very happy to see my fuids again (worked hard for those). I'll wait to update Forge again when the fluid thing is fixed.

**Comment by XFactHD** [comment]
This problem occurs because of a change in the forge fluid system, that's no bug in Mekanism.

**Comment by StarkRG** [comment]
That's a rather short sighed and idiotic stance to take. If a Windows program fails to work because of a change in the way Windows works it's up to the program developer to fix it so it will continue to work. Unless, of course, you're suggesting we use mekanism without forge.

Forge is an essential part of modded minecraft, not working because of a change in forge IS a problem with the mod. It may not be a bug, per say, but it is a problem that needs to be addressed.

**Comment by unpairedbracket** [comment]
There is still no recommended Forge build with this change included. When there is we will build against it and address issues that result from the change. Until then, building against any version of Forge with the change will break compatibility with the recommended version of Forge, and we would rather have relatively minor issues with the latest build than crash with the recommended.

**Comment by tgstyle** [comment]
@unpairedbracket 

I would suggest you reconsider. Many mods have already moved on to Forge 1355, Mekanism is the only mod using fluid in my pack that is not.

**Comment by tgstyle** [comment]
Buildcraft, EnderStorage, ExtraUtilities, ExtraCells, OpenBlocks just to name a few that are already compatible.

**Comment by wandersonbraz** [comment]
then all the mods I am using station that list.
ender storage was a mod that intended to use but he gave crash along with the other then I gave up his still do not know if there is a similar mod because I want to make a system with ae2.

http://pastebin.com/xhtThicu

**Comment by tgstyle** [comment]
@wandersonbraz 
TConstruct even has an alpha release to address this issue.

**Comment by tgstyle** [comment]
https://github.com/aidancbrady/Mekanism/issues/2544

**Comment by wandersonbraz** [comment]
did not understand the part of tconstruct it has to do with the cashs the storage ender?

that link and a crash report that separated but do not know interpret it
http://pastebin.com/YRb1HmNC

**Comment by unpairedbracket** [comment]
I've updated Forge and fixed the separator issue in development. Expect an update and fix in the coming days.

**Comment by tgstyle** [comment]
@unpairedbracket 

Thank you!

**Comment by Tomatoh** [comment]
Has there been any update on this issue with the electrolytic seperator and forge 1355+
