### ISSUE TITLE
Suggestion: Fission reactors

### ISSUE THREAD

**Issue by xGhost169** [aidancbrady/Mekanism#2549]
Fission Reactors to MekanismGenerators, nuclear reactors that use Uranium. For another type of Nuclear reactor.

**Comment by XFactHD** [comment]
It should also definitely be a multiblock.

**Comment by EzerArch** [comment]
I don't know. Mekanism seems to have a subtle "green" taste, I mean, it seems to be an eco-friendly mod. Look at all those wind turbines, solar panels, biogenerators, and now a fusion reactor... okay you can now burn entire forest with a flamethrower, who cares about those pesky trees?

**Comment by Barhandar** [comment]
From my viewpoint, it's less about being "green" (nuclear reactors, when run properly, are several orders of magnitude more "green" than coal-fired plants - the former only irradiates everything when broken, the latter constantly due to thorium in coal), and more that everybody and their cat add nuclear reactors to their mods. Why not something a bit more original?

**Comment by unpairedbracket** [comment]
I'm with @Barhandar on this one. A large part of the reason I went with fusion was because it's a technology I find interesting, and it hadn't been done to death like the fission reactor in mods. I'm not aware of any other mod that uses ICF, so I decided to see if I could do something cool with that instead of going for a Tokamak and magnetic confinement like all the other fusion reactors I've seen.

I just can't think of a way of doing fission power that would be interesting and different, but if anyone has any good ideas on that front, do let me know.

**Comment by aidancbrady** [comment]
I'm all for adding fission reactors, but yes, it would need to be done uniquely like how @unpairedbracket designed the ICF reactor.  I'm closing this for now, but I'll definitely leave open a request that details a new take on fission reactors we could logically implement.
