### ISSUE TITLE
Request: Factory versions of tier 4/5 processing.

### ISSUE THREAD

**Issue by PiggyWhiskey** [aidancbrady/Mekanism#2567]
I'm currently running a digi-miner with max upgrades and I recently delved into the Tier 4/5 Ore production (Never done that before)

Now with the T4/5 max upgrades (Gas/Energy/Speed) it can only process in line with a single machine (T1/2/3) which makes factories essentially useless for bulk ore processing.

So my options are T1/2/3 with factories (miss out on 4x and 5x production) or very slow ore processing and not use factories or make 7 copies of the T4/5 processing machines.

Is there an option for factory versions for the Chemical Crystalliser, Chemical Washer and Chemical Dissolution Chamber?

Edit:

The final bottleneck actually seems to be the chemical crystalliser. Even with 8x Speed Upgrades, its still slower than everything else.

**Comment by Flukethoughts** [comment]
I have noticed this to I thought I was building a beast only to realize the slowness of the chemical crystallizer was a huge down fall. Even with the upgrades it moves to slow I think it might be best to make it produce in chunks of 5 rather then by one that might even it out by a little but I'm not to sure.

**Comment by PiggyWhiskey** [comment]
That is true. But chunks of 5 would still be slower than the elite factories. 

Working in parallel doesn't work either as fluid pipes won't always sent even lots of 10 slurry. Leaving a couple behind and requiring manual intervention.

**Comment by Flukethoughts** [comment]
double checked and yea it sucks horribly makes the x5 method seem pointless as the x3 method was so much faster.

**Comment by EvulOne** [comment]
The point of 5x processing is not speed, but efficiency; you should not be running everything through it without multiple 5x processing lines.

That said, having 2-3 setups for each ore type of 5x processing, you can have an insane rate of production going on.

Factories aren't meant for bulk ore 5x multiplication, since that would kind of defeat the purpose of having the large setup for it.  Maybe Aidan can correct me if I'm wrong on all this.

**Comment by Flukethoughts** [comment]
I would honestly agree with you on that but to be honest mek has far to much lag in it at this current time to sit there and build more machines for it would be pointless and just bring down a server. I already have 12 lines doing there own ores.

**Comment by EvulOne** [comment]
So you make a compromise then, you either reduce your ore output and use factories, or you get better hardware and churn out 5x efficiency. (I'm assuming you mean that it's lagging the server-end of things?  I haven't had any issues with lag, either client or server-side, on my current ~20 player server) 

As I previously said though, you by no means have to use the long-process for 5x processing for all ores.  Keep it for the rare ones, and let the plentiful ores go through your factory processing.

**Comment by Flukethoughts** [comment]
http://i.imgur.com/53CcUju.png

Best hardware money can buy so ill let you try again
cpu usage is mekanism

**Comment by mcgraj3** [comment]
I have posted elsewhere on the Mekanism issue tracker about T4 (5x processing) bottlenecks at the crystallization machines. It is dreadfully slow and I have honestly abandoned it. With the Digital Miner, 4x ore processing is pretty damn good.

**Comment by Flukethoughts** [comment]
mcgraj3 i would love to show you my setup

if ur interested you can see for yourself on how i have everything setup

**Comment by mcgraj3** [comment]
@Flukethoughts If you can take some screenshots and throw them in an Imgur album, sure thing.

**Comment by Flukethoughts** [comment]
http://imgur.com/a/HIRSR

**Comment by mcgraj3** [comment]
@Flukethoughts Very impressive! I had a nice base but when I updated some mods the entire save got corrupted. I have since started rebuilding (as of last week). Few questions:

1. What are the angled information panels that display the liquid contents?
2. On the Mek laser array, what are those rounded cables?

I run a custom modpack (no BC or IC2, using mostly TE, Mekanism, and EnderIO) so it may be why I don't recognize some of these blocks. Thanks.

**Comment by Flukethoughts** [comment]
@mcgraj3 
Come see and find out everything you want.
http://bit.ly/1HxGpgB

**Comment by aidancbrady** [comment]
As @EvulOne stated, by creating 5x ore processing you're trading off speed for efficiency.  After doing a bit of testing I'm happy with the current mechanics.

**Comment by scifibob** [comment]
Something you might not have thought about, is that it's impossible to automate multiple crystallizers because there is no way to restrict gas cable transfer in a multiply of 200mB.

So I'm stuck with one crystallizer per Washer, unless I do a manual cleanup with a dropper in each crystallizer after it's finished.

If by efficiency you mean no automation, then you made your goal.

**Comment by mrgrey1** [comment]
I have to agree with other comments here about the crystallizer. I've happily split my main ores off to start at the purifier and had my precious ores going to the t5. Discovered a significant bottleneck at the washer to crystallizer, thought no problem I'll just put 4 crystallizers in only to have them all jam up because they accept any amount of fluid. Restricting their fluid intake to a 200mB quantity would avoid the jamming situation and solve an otherwise pointless bottleneck.
