### ISSUE TITLE
[Feature Request] Electrolytic generator

### ISSUE THREAD

**Issue by XFactHD** [aidancbrady/Mekanism#2581]
The Electrolytic generator would generate electricity from combining hydrogen and oxygen the be able to build a chain out of some tanks, an electrolytic separator and a electrolytic generator to store excess power when using less than producing and release it again when needing more power, much like what you can do with IC2s electrolysed water cells.

**Comment by gabrieltm9** [comment]
This is a really cool idea. I know i would definitely use it.

**Comment by Badcholo** [comment]
I like the hydrogen gens so much, please don't change the way this works. go get ic2 if you like that better.

**Comment by XFactHD** [comment]
I didn't request to change the existing gas burning generator, I just wanted a new one.

**Comment by Greylocke** [comment]
You can already do what you have described with the machines that are already in the mod.

Electrolysis adds the energy required to split the bonds between hydrogen and oxygen. Then the Gas Burning Generator recombines the hydrogen with oxygen, so that you get that energy back again. In effect, tanks of hydrogen are already a gaseous battery.

**Comment by XFactHD** [comment]
I know, but burning hydrogen is less efficient than recombining it with oxygen in exactly the opposite way how electrolytic separation works. I just want this for the sake of reality.

**Comment by halvors** [comment]
@XFactHD You mean a fuel cell? http://en.wikipedia.org/wiki/Fuel_cell

That would be a great addition :D

**Comment by XFactHD** [comment]
That's exactly what I meant.

**Comment by Badcholo** [comment]
Your over complicating things to get the same result. Power. There are already batteries and cubes to store energy. Thermal expansion has Capacitors to charge items in hand or ender io to charge items in your inventory. Simply jetpacks with Ender io has backpacks to hold large quantities of power, like 50mil RF.

**Comment by EvulOne** [comment]
You're not "burning hydrogen" so to speak.  Hydrogen doesn't burn in the sense that you're describing, it combines with oxygen to form water, and releases heat in the process.  What you're describing is barely more efficient than the current "hydrogen burning" method.

You get back almost what you had to put into it as it is currently.  You'll never get back the same amount of energy as you used to produce the H, and you'll never get back an excess of energy.

**Comment by XFactHD** [comment]
Talking about overcomplicating: Aidan added a fusion reactor, he could have made it a simple block, but, no, he made it an awesome multiblock.
Also, there is an immense difference between burning hydrogen in an oxygen environment and pumping the hydrogen in a fuel cell and "mixing" it with oxygen, because even if you don't need any turbine to get power from the gas burning generator, you have to think of it as an engine that produces steam and sends it into a turbine. The efficiency of those systems is more or less bad.
Last but not least I think that this mod isn't about making everything easy (then I could also use IC2 or Thermal Expansion for every task), it is about having to think of what you do, making things different and more modular and sometimes also a bit more complex.

**Comment by EvulOne** [comment]
It doesn't have to involve steam at all.  
You can mix oxygen with hydrogen to produce an electric current, or
You can burn hydrogen in a combustion-type engine and power a generator with its mechanical output.  

The efficiency difference between the two is negligible; only a small amount of energy is lost to the mechanical components/heat.

You're treating it like a steam system, which it is not.

**Comment by dman11235** [comment]
In reality, you can't get more energy back from what you put in.  The way the generators/separators work now is much MORE efficient than reality, because there's no energy loss (and in reality there is).  When you have H and O in a fuel cell, you are still burning the hydrogen to get energy, because all burning is is the rapid oxidation of a chemical.  The only difference is that there's no flame in a fuel cell.  This makes them more efficient than gas burning generator, but still not perfectly efficient (because nothing is, and the flame is inefficient because you lose energy to excess heat and light).  The current machines pretty much do this already.

Oh, and turbine systems?  They can be REALLY efficient.  It's just a matter of fuel source.

**Comment by aidancbrady** [comment]
We already are planning on adding turbines and boilers into Mekanism v9.  I appreciate the idea, but I'd rather not add any content that is even slightly redundant - there's already a lot to work on for the next version.
