### ISSUE TITLE
ClassNotFoundException: mekanism.common.tile.TileEntitySalinationController

### ISSUE THREAD

**Issue by xenoswift** [aidancbrady/Mekanism#2586]
Occurs on load during pre-init on 8.1.2.228, 227 and 226. The crash log is from 228.
http://pastebin.com/hu8PH0K4

I'm trying to upgrade from Mekanism-1.7.10-7.1.2.185 to get away from the Gas Generator placement crash, and now I can't load period. I'm thinking something else is going on in my mods though since this is stretching back through several revisions.

**Comment by halvors** [comment]
The issue is not Mekanism's fault. But you are using WAILA Plugins that seems to trying to load the Mekanism v7 TileEntitySalinationController, which does not exist in Mekanism v8.

You should either remove the Waila plugin, downgrade to Mekanism v7 or suggest to the developers of the WAILA Plugins that they update Mekanism integration to v8.

**Comment by xenoswift** [comment]
Updated WAILA, plugins and ttcore and the problem is solved. Thanks Halvors.

**Comment by halvors** [comment]
You're welcome :)
