### ISSUE TITLE
Request: Laser Affect the Wither

### ISSUE THREAD

**Issue by speakerrob** [aidancbrady/Mekanism#2596]
I would like to be able set up wither farms using your lasers, and I noticed that the lasers will kill a multitude of entities from other mods (e.g. bosses from Twilight Forest) but not the Wither. Is this by design?

**Comment by gabrieltm9** [comment]
It might be a little OP, but, i think it would be awesome to have this feature and set up wither farms using mekanism.

**Comment by speakerrob** [comment]
OP is relative I think. Considering that the power requirements on the lasers is pretty hefty, you would have to set up an entire power system to exclusively pump energy into any farm setup you had going. That's a lot of infrastructure to accomplish a single task. There might be other considerations I'm not seeing though, which is why I was asking if this missing mechanic was intentional or just an oversight.

**Comment by TacoMage** [comment]
I think it's related to the fact that lasers do fire damage, and the wither is immune to such; very likely they cannot kill anything fire immune (pigmen, blaze, etc), but I have not done significant testing along that line.

So far as the power requirements go, there is a way around it so that laser traps consume no power at all beyond an initial charge.  Not terribly OP in my opinion because first, lasers have a chance to destroy whatever items are dropped if they fall wrong, and second, because they functionally mimic iron spikes from Extra utilities except with fire damage, and do not force player-kill drops the way diamond spikes do.  So, in the grand scheme of things, lasers set up to perpetually grind mobs without any power draw don't do anything that other mods don't already do.

**Comment by speakerrob** [comment]
Valid point @TacoMage , I forgot that it doesn't lose the energy on entities, just when breaking blocks. I didn't know about the lasers being counted as fire damage. However, having a power draw when damaging entities would be welcomed in my opinion. I'm not sure how feasible that would be in the code, and I doubt everyone would appreciate it. Overall it seems to make more sense for me though, energy must be lost from the beam when it is absorbed by the entity as damage.

P.S. Thank you for your spotlights @TacoMage they were very useful for me when learning the new v8 stuff.

**Comment by aidancbrady** [comment]
Just changed the functionality a bit - the laser will only catch entities on fire that are not immune, but will damage any entities with a generic damage source regardless.  Hopefully this solves the issue.
