### ISSUE TITLE
Reactor - RF versus kelvin and ignite

### ISSUE THREAD

**Issue by scifibob** [aidancbrady/Mekanism#2633]
There seem to be a missing piece (among MANY) in the documentation of your mod, converting kelvin into RF.

How am I to know how much RF my lasers is to produce to ignite a reactor?
I've tried the last 3 days, but nothing seems to work.

The most RF I stuffed in was 500 MRF, but the reactor didn't ignite, not even close.
I'm tired of creating lasers just for "try-and-error", so why don't you publish a real number?

Another thing is, that I got it to work in creative mode (with 70 lasers), but the reactor was inactive the next time I logged in.
So I fear that even if I do manage to ignite the reactor, the next time I log in I will need to do it again..

**Comment by scifibob** [comment]
Forgot to mention, I'm using Mekanism-1.7.10-8.1.2.229.jar

**Comment by RAWRwins254** [comment]
Hey Bob! I'm not a dev but I figured I'd share some insight with you. I don't have an exact RF number to give but typically you need either one laser.amplifier with 1.2GJ or two amps with 600MJ. I'm pretty sure you're already aware of having to build up charge in the amp instead of releasing as it comes in. As far as the reaction shutting off, is the area chunkloaded and do you have enough tritium production to last through night cycles?

**Comment by scifibob** [comment]
The reactor that was shutting down was not chunkloaded
I have yet to get my new reactor up and running in a chunkloaded area to see if it works.

I'm aware of the laser build-up thing, and have a redstone switch on the end amplifier.
1.2GJ, what is that in RF?
I spotted this setting in the config:
D:RFToJoules=0.4
That would mean the RF value would be way beyond reach.

**Comment by scifibob** [comment]
Update: I finally managed to ignite the reactor, with 2GRF in the amplifier (the max value).
The reactor is now in a chunkloaded area, and seems to persist client reloads.

I still would like to know the exact value in RF (of Joules if that's selected as "currency") for ignition instead of Kelvin.

**Comment by scifibob** [comment]
Update 2: Seems like the reactor also stays active on a server restart. Good!

**Comment by TacoMage** [comment]
400MRF in a single pulse was enough to light reactors when I was doing the last of my spotlight series.  Not entirely sure why 500MRF didn't work for you as I did repeated testing at and around 400 MRF and found it to reliably ignite reactors at that energy, which is what I successfully use in the video.

That said, I don't know if it would work if you're doing water cooling.  My testing was passive-setup only.  Ostensibly it should be the same, but I know there are differences between passive and liquid cooled, so that may be one of them.

**Comment by scifibob** [comment]
I'll try again with 400MRF, the reason the 500 MRF didn't work might have been that I tried an obscure combination of amplifiers (3 lasers into one amplifier, then three of those into the next), so amplifying amplifiers so to say.

I have not tried water cooling yet, because the main reason of getting this thing up and running is to get rid of the Big Reactors plugin, and I can't find any use for steam anywhere else in the mods I'm running.

**Comment by TacoMage** [comment]
That could be it.  I used a single amp that gathered energy, set it to maximum output of 400MRF and put it on button mode.  That way I could be sure it precisely output a single burst of 400 MRF.

**Comment by RAWRwins254** [comment]
Bob, 0.4 RF = 1 Joule For future reference.

**Comment by scifibob** [comment]
Seems like the reactor has some more bugs, so I'm abandoning this route to power for now.

The lasers, electric pumps and the brine processing machines produce too much lag compared to big reactors, and every time I log in and right click the reactor controller, it shuts down.

No errors in the logs, so I'm not sure what's happening.

Anyway, it seems like between 350 and 400 MRF is around the amount needed to ignite the reactor, so I'm closing this issue. I'm opening a new one on the shutdown issue if it's not reported by anyone.
