### ISSUE TITLE
Reactor D-T fuel a poor choice?

### ISSUE THREAD

**Issue by Tergiver** [aidancbrady/Mekanism#2635]
Mekanism v8.1.2.229

I've been trying to get a reactor running without a lot of success.

At this point I have six full-sized brine towers feeding a half-sized lithium tower. This produces just a bit more brine than the lithium tower can consume. That tower feeds 14 Solar Neutron Activators which seems to be just about as much of the lithium as is produced.

I make liquid D-T Fuel at this site so I can send it through a EnderIO Dimensional Transceiver to the Reactor site. There it is turned back into gas and dumped into the reactor.

The reactor says I need a minimum injection rate of 2, so that's what I set it to and started the reactor. I had about 200,000mb of D-T fuel (liquid) prior to ignition. It sucked it all out in a matter of a few dozen seconds and my reactor shut down.

On the other hand, if I take the same tritium and deuterium production and instead of routing it into a chemical infuser to make D-T fuel, turn it to liquid, transmit it, etc., I route the tritium and deuterium directly into a reactor(*), the reactor runs all day and all night while still producing excess tritium.

Shouldn't the D-T fuel made from tritium/deuterium provide the same "fuel" to the reactor as the two gasses directly?

(*) I built another reactor at the brine/lithium site to test this.

**Comment by TacoMage** [comment]
Pretty sure this is working as intended.  Since it's introduction, the function of the system is that Deuterium and Tritium are separately input and the injection rate controls their paired injection into the D-T fusion chamber, which leads to a controlled reaction and stable energy production. Injecting D-T directly leads to immediate burn-off and conversion into heat, which leads to an extremely high, but inefficient, burst of energy production.

I'm almost positive I've seen Aidan comment on another bug report that this was the desired mechanic.

**Comment by aidancbrady** [comment]
Thanks @TacoMage.
