### ISSUE TITLE
Copied chisel code is out of date - Could possibly use API now?

### ISSUE THREAD

**Issue by tterrag1098** [aidancbrady/Mekanism#2642]
We have improved the code in both CTM and RenderBlocksCTM to allow for more flexibility with blocks.

For instance the CTM now supports non-full block bounds, such as slabs. It will properly adjust the UVs to match these bounds.

On the whole the code is also much cleaner.

Both of these classes are now included in the API download of chisel, though I'm not sure what you want to do with that info :P

**Comment by tterrag1098** [comment]
Here's the relevant stuffs https://github.com/TheCricket/Chisel-2/tree/dev/src/main/java/com/cricketcraft/chisel/api/rendering

**Comment by aidancbrady** [comment]
Thanks so much! I'll take a look later tonight :)

**Comment by aidancbrady** [comment]
@unpairedbracket, did you make any changes to the chisel code you adopted? I don't want to overwrite anything.

**Comment by unpairedbracket** [comment]
I had to make significant changes to the system they use for matching blocks that should CTM together, so that it's possible to add several lists of metadata values with different block instances to a CTM group. The salination blocks for example are split across 2 block instances, so I think they need 2 meta values from BasicBlock and 1 from BasicBlock2 to match, so the CTM works properly

**Comment by aidancbrady** [comment]
Okay.  CTM is working fine for the most part right now, I think I'll leave things be.  If I ever run into any issues that are fixed in the new Chisel additions I'll see about doing a bit of refactoring and updating.

**Comment by unpairedbracket** [comment]
If it hasn't already been done by then, I'll look at updating the CTM code to be in line with recent chisel upstream when I finish the set of exams I'm working towards currently.
