### ISSUE TITLE
MekanismTransmitters 

### ISSUE THREAD

**Issue by darknat** [aidancbrady/Mekanism#2673]
Hi,

I have a problem with my server ,my ram increases rapidly and in my log, i have : 

[Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
[Server thread/DEBUG] [MekanismTransmitters/]: Dealing with 11 invalid Transmitters
[Server thread/DEBUG] [MekanismTransmitters/]: Dealing with 1 orphan Transmitters
[Server thread/DEBUG] [MekanismTransmitters/]: No networks found. Creating new network
[Server thread/DEBUG] [FML/]: Gathering id map for writing to world save world
 [Server thread/DEBUG] [MekanismTransmitters/]: Dealing with 1 invalid Transmitters
[Server thread/DEBUG] [MekanismTransmitters/]: Dealing with 1 orphan Transmitters

http://pastebin.com/YZYWjPi3

**Comment by aidancbrady** [comment]
Check the crash log again - the stack trace isn't related to Mekanism at all from what I can see.

**Comment by aidancbrady** [comment]
Closing for now, let me know if you can confirm this is on my end.

**Comment by ziba1** [comment]
Hi, its been suggested I come here since i am having the same issue.


https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/611#event-314073727

(copied from my thread)



updated my server from 0.7.6a to 0.7.7a yesterday and its become fairly laggy, with cpu and ram usage both mostly 100% on the server, even when noone is online. Has anyone else had any issues running servers after updating ?

This isn't a big server by any means, 2 players only on it, was 2gb of ram, upgraded to 3gb of ram

when I upgraded it, it was running fine for a few hours, ram usage at like 65-70% and cpu usage was at like 50%, got up this morning and logged into mcadmin to check and both are at 100% again, logged into game and its laggy again.

The only new thing so far as I can see is mystcraft with the update, it did its configuration thing yesterday but we haven't used it yet.

We pretty much turned off every contraption running - my mate was messing around heavily with laser drills and the big reactors. Turned off our mob spawner setup, broke every chunk loader we have (which was like 4) But still having this issue.

Here are my logs from my server

http://paste.ubuntu.com/11374188/

http://paste.ubuntu.com/11374188/

according to the modpack runner for the 1.7.10 pack theres 3 lines from mekanism repeating over and over again.

So can this issue be reopened please ? 

cheers.

**Comment by utoc** [comment]
I too am having this issue, it has caused our server to hang twice. It does not appear to respond to commands while this issue takes root and I finally gave up and gave the server a control+C.

http://pastebin.com/5yRSZMRp

The server was normal until 08:28:35 when it began going on about the MekanismTransmitters issue.  I was online and kicked off.  I logged in to a remote shell and saw the java process was running at 200% CPU and had maxed out memory at 12GB with three players online.  TPS before this event was 20.

I'm sorry I can't provide any more information than this, if you need anything done to help rule out or otherwise debug this issue, let me know.  Thank you.
