### ISSUE TITLE
Pressurized Tubes fail to move gases after chunks are loaded

### ISSUE THREAD

**Issue by UntouchedWagons** [aidancbrady/Mekanism#2732]
I'm playing on a server and I've got the ore quintupling set up. My base is loaded via a Personal World Anchor so that it's loaded only when I'm on. However every time I log on and go to my base I have to replace every single pressurized tube because they won't move gases.
[In this picture](http://i.imgur.com/dVlSpjO.png), I've removed and replaced the tube my cursor is pointing at, but the gas (hydrogen chloride) won't go to the other tubes in the network.

I'm using mekanism version 8.1.2

**Comment by UntouchedWagons** [comment]
Maybe it's just a visual quirk. I put some gold ore in the chemical washer and all the tubes showed they had the correct gases. I'll keep an eye on it.

**Comment by RAWRwins254** [comment]
This is due to how mekanism handles object loading in a newly loaded chunk. A chickenchunks chunk loader will solve the issue completely until such a time that the devs can fix this issue. It might be solveable by the method you described but it should automatically detect newly loaded pieces if it doesn't already.

**Comment by aidancbrady** [comment]
Update Mekanism to 8.1.4, this should have been fixed.
