### ISSUE TITLE
Sound system glitch

### ISSUE THREAD

**Issue by Radviger** [aidancbrady/Mekanism#2741]
Hi, @aidancbrady. I have an issue with MK:
MK's sound system have a bug that create some fake sound sources when I for example stay near the macerator, then I teleport somewhere and then go back I hear two sounds and one of them fake and one is real. That bug still occurs when I continue teleport somewhere and back. That means that soon I will hear ten and more sounds. It's really terrible to my ears. Fix it pls =) Thanks!

**Comment by scifibob** [comment]
I agree on this one. Usually I tend to log off and on again to get rid of the annoying sounds.

**Comment by BeardedGrue** [comment]
I'm not sure if it is related, but Sound Muffler has no affect on Mek machines either.

**Comment by TehStoneMan** [comment]
I've had a look into this. It seems that when a machine is operating in a loaded chunk but outside the client render range, if that machine finishes operating, the client does not receive the network message to stop playing the sound, so when the player returns to the machine, the sound system still thinks that the machine is operating. This is because the sound system is relying on the server to tell it to stop playing the sound, and not looking at the render state of the machine.
As for the gas mask issue, I have not been able to reproduce that.
