### ISSUE TITLE
Server Crash - at mekanism.common.FuelHandler.getFuel(FuelHandler.java:33)

### ISSUE THREAD

**Issue by ProsperCraft** [aidancbrady/Mekanism#2766]
http://pastebin.com/UMXnSX8R

FTB Daybreaker 1.0.2

**Comment by ProsperCraft** [comment]
This crash seems to be related to Engineers toolbox mod(which includes gascraft) gas being produced by the electrolytic separator and being fed into a gas burning generator.  It is only when the user attaches the oxygen side that causes the crash.

Server owners- Disabling Engineers toolbox, loading the region in question allows you to punch out the gas burning generator, then you can re-enable engineers toolbox.

**Comment by EchoingZen** [comment]
I received the same crash the moment I placed my gas-burning generator to the right of my pump.  Unable to load my world now.

http://paste.feed-the-beast.com/view/faff304d

**Comment by aidancbrady** [comment]
Fixed in development, expect release soon.

**Comment by EchoingZen** [comment]
Thank you for addressing this issue, been locked out of my world for a couple weeks now. Can't wait for release!  Thank you.

**Comment by ProsperCraft** [comment]
You shouldn't be locked out, I posted a workaround in my report 16 days ago.

**Comment by EchoingZen** [comment]
I didn't do your solution because I thought the was worldgen in engineer's toolbox.  Disabling would trash anything the was worldgen'd.  Was I mistaken?

**Comment by RAWRwins254** [comment]
@EchoingZen @ProsperCraft did provide a work around. I will reference another thread which has a current (as of 3 days ago according to last commit) build linked in from my website of the development branch of this repository. https://github.com/aidancbrady/Mekanism/issues/2809 has a link to the builds I did yesterday of the development branch. I have yet to hear back from either Aidan or Ben, so I will assume that they are fine with it until I hear otherwise. Although, I should probably put the dates in where the jars say homebaked currently (which I have just completed the process of doing).

**Comment by EchoingZen** [comment]
@RAWRwins254 Just tried your jar and it works like a charm.  Wonderful work.

**Comment by RAWRwins254** [comment]
@EchoingZen it better work! I didn't write the code in it. That was all Aidan. I just compiled the jars and am hosting them.

**Comment by EchoingZen** [comment]
@RAWRwins254 Well, wonderful work compiling the jars!  Hehe.
