### ISSUE TITLE
[Question] Which version Digital Miner doesn't use Forge BreakEvent standards?

### ISSUE THREAD

**Issue by spannerman79** [aidancbrady/Mekanism#2809]
As per @aidancbrady responce [here](https://github.com/aidancbrady/Mekanism/issues/2745#issuecomment-111843344) and until version 8.1.6 is pushed ( [source](https://github.com/aidancbrady/Mekanism/issues/2771#issuecomment-118918530) ) which version of Mekanism doesn't follow Forge BreakEvent standards in the Digital Miner so Mekanism is able to be used on a Cauldron server?

Related issues: #2771 #2745

**Comment by RAWRwins254** [comment]
If I can confirm it's been fixed in the development branch, I can manually compile for you or teach you how to manually compile it. Whichever. The thing i catch most flak for is offering to compile stuff for people. They claim I could put malicious code into the files. Sure I could... if I knew Java for one and for two, that assumes I want to put malicious code in. You'll actually see that I've only submitted one pull request to this repository and it was code that somebody in the MinecraftForge IRC channel provided me with to help me manually fix the crash until the build could be pushed. So honestly, it's up to you if you want to learn how to compile it yourself or you want me to compile a build for you.

**Comment by RAWRwins254** [comment]
Okay, Compilation is done: For those who do not know how to or do not want to manually compile the development branch, I have uploaded my compilation of the development branch with a last commit of this: https://github.com/aidancbrady/Mekanism/commit/b7436181867be9fbb4d2eaef2d1d64895bf90cdf

Link to all jars is as follows (do not use HTTPS for this as I have decided not to add in any SSL support for these files. I will enable it only if demand becomes sufficient.): http://crius.lksmith.net/mekjars/ 

@aidancbrady or @unpairedbracket , If either of you want me to remove my hosted jars, Please send me a PM and I will take them down as soon as I see the notification of a PM with the content instructing me to remove them. My intent is not to supplant your guys' jenkins server but rather to provide an intermediary unit in which I can compile the jars when builds have yet to be pushed due to unknown reasons and people start getting antsy about it.

**Comment by RAWRwins254** [comment]
Also, @aidancbrady and @unpairedbracket, i will be opening another issue regarding something in manual compilation vs builds.

**Comment by spannerman79** [comment]
@RAWRwins254 sorry for the delayed reply - I'm UTC+10 - when you added your first initial comment it was ~2am for me.

I would have liked to have learnt how to build from source but your builds are acceptable.  Trust has to start at some point.  As my server runs on linux, and it runs under a user with no actual privileges within a SELinux tweaked profile the chance for any possible security issues are minimised - which any decent sysadmin would do in the first place. 

Once I wake up :coffee: - plenty of :coffee: - I'll try your builds out @RAWRwins254 

On a side note, and to @aidancbrady - I am *still* awaiting for access to your dev build server from my to date two complete continuous months contribution via Pateron - [my profile](https://www.patreon.com/user?u=700119)  - so if you have an issue with @RAWRwins254 look to others that have have actually supported you but without the actual means promised to them that have been provided by others

**Comment by RAWRwins254** [comment]
@spannerman79 if you'd still like to learn, I can set aside time later tonight (I'm GMT/UTC-5 currently due to US DST) around 7 or 8pm my time. So if my math is right around noon or 1pm your time. Let me know.

**Comment by RAWRwins254** [comment]
also, that may be true about sysadmins doing that but a lot of end-users know nothing about SELinux or the Linux kernel at all. Hell, I've got so many technologically illiterate friends it's not even funny. Some of them actually use Linux although when they encounter issues they phone me going, "WTF DO I DO?!"... So yeah.

**Comment by juniorjunior** [comment]
Has anyone actually gotten this (or any other) build to function properly in a [K]Cauldron server? If so, which specific version of the server and which protection plugin? I've tried this (and my own build) on KCauldron 144. The DM will not mine and the [Mekanism] user does not show up in the ops.json file when opped.

**Comment by RAWRwins254** [comment]
@juniorjunior i'll try firing up one locally.

**Comment by spannerman79** [comment]
No need.

I already tester your builds and they work flawlessly. 

Once 8.1.6 is pushed officially I would recommend using your builds @RAWRwins254

**Comment by RAWRwins254** [comment]
@spannerman79 mind posting your kcauldron build and what plugin you use that prior to my builds, mekanism couldn't use the DM with? Might help isolate issues. Also going to be sorting the built jars by commit hash (the HEAD tag not the full thing).

**Comment by spannerman79** [comment]
It wasn't a matter of what build of kcauldron or what plugins I was using, it was the moment that @aidancbrady made the Digital Miner use ForgeBreakEvent with a fakeplayer, and that fakeplayer wasn't being announced - hence why kcauldron couldn't log the fakeplayer and blocked the break events - hence the Digital Miner was useless.

Now what @aidancbrady did was correct code wise - using ForgeBreakEvent was correct so that wasn't his fault.  The issue was what i mentioned before - fakeplayer wasn't being announced and logged - which was fixed in https://github.com/aidancbrady/Mekanism/commit/77db81bcf0c0eaaa7f3757e7b1a610b804491253 - which is a commit before of your build that was based on https://github.com/aidancbrady/Mekanism/commit/b7436181867be9fbb4d2eaef2d1d64895bf90cdf

As to my original OP question I never found an answer as your build that your did initially [here](https://github.com/aidancbrady/Mekanism/issues/2809#issuecomment-120461769) solved my issue.

As to what plugins I use - the same that any sysadmin has used for ages I'd assume lol.  PEX, ModifyWorld, Multiverse(family), WorldGuard, WorldBorder etc
