### ISSUE TITLE
[Request/Issue] Atomic Vien Mode + Other trees

### ISSUE THREAD

**Issue by yepidoodles** [aidancbrady/Mekanism#2823]
Mekanism Version 8.1.5.246

When using Vien mode on the Atomic disassembler, it doesn't recognize MFR rubber trees as trees, and when it cuts down Extra tree's wood, it cuts the wood down, but all but the one you broke, disappears. 

Hoping you'll be able to sort these out,

Thanks

- Alice (yepidoodles)
DragonTechMC

**Comment by aidancbrady** [comment]
The Atomic Disassembler will "disassemble" a vein of ores that use the same Ore Dictionary key, with the exception being keys that equal "logWood."  This is probably due to MFR not registering their wood- I'd rather not add special integration.

I don't believe the Extra Trees issue is not on my end, though the author is welcome to correct me if I'm doing something wrong.
