### ISSUE TITLE
Add OpenComputers API

### ISSUE THREAD

**Issue by egorchik007** [aidancbrady/Mekanism#2826]
Please add OpenComputers API.
It's another mod which adds computers to minecraft.
It's much better at perfomance (native runtime for Lua) and at some other features.
https://github.com/MightyPirates/OpenComputers

**Comment by Vexatos** [comment]
Translation: Please add support for the OpenComputers API and add all the functions that you made available for ComputerCraft. I recommend using the prefabricated [Driver](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/java/li/cil/oc/api/prefab/DriverTileEntity.java) and [ManagedEnvironment](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/java/li/cil/oc/api/prefab/ManagedEnvironment.java) for easy implementation, and if you prefer the ComputerCraft way of registering methods, implement [ManagedPeripheral on the ManagedEnvironment](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/java/li/cil/oc/api/network/ManagedPeripheral.java).

Furthermore, it's recommended to implement [NamedBlock on the ManagedEnvironment](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/java/li/cil/oc/api/driver/NamedBlock.java) and setting the priority so that the name of the environment with the highest priority gets chosen for display.

**Comment by aidancbrady** [comment]
Hey @Vexatos, thanks for the more in-depth explanation.

After doing a bit of research, would it be alright if I just implemented SimpleComponent and ManagedPeripheral in classes I also implement IPeripheral in, and just have the OC methods call the CC ones?  I want to try and do this with as efficiently as I can.

**Comment by Vexatos** [comment]
@aidancbrady That would work as well and would not require registering any driver. But there is a drawback: OC will propagate its network across all connected Environments (SimpleComponent being one). Depending of the CPU tier in your Computer, there is a certain maximum amount of components that may be connected at once. Meaning if you, for instance, implement SimpleComponent on your cables, every single Cable and all machines connected to those cables and all cables connected to them etc. would become part of the network and ultimately crash the computer due to the exceeded component limit. By registering a driver, You force the player to place an Adapter block from OC adjacent to the block they want to interface with. This means that only the one block the player wants to interface with gets added to the network and thus the component count. This issue occured with PneumaticCraft until it got changed to the Driver-based system.

**Comment by Vexatos** [comment]
Note that you could still easily implement your methods in your TileEntity just like you want to and then just call `tile.whateverthemethodiscalled()` from the ManagedEnvironment.

**Comment by aidancbrady** [comment]
In that case, what's the easiest way I can build on my already-existent CC integration by means of drivers?  For my machines, right now I implement IPeripheral in the base machine class and take care of several common methods there, and then take care of the more specific methods (getMethodNames()/callMethod()) in functionality base classes (TileEntityElectricMachine for Enrichment Chambers/etc, TileEntityAdvancedElectricMachine for Osmium Compressors/etc).  I currently just pass getInventoryName() as the peripheral name and everything works alright.  Is something like this possible with the driver system?

**Comment by Vexatos** [comment]
@aidancbrady it is. When implementing `NamedBlock`, you need to implement `preferredName` which you can just call `tile.getInventoryName()` in. For the methods in `ManagedPeripheral`, you could also just, as I said, directly relay them to their according methods in the TileEntity. See [here](https://github.com/asiekierka/Computronics/blob/master/src/main/java/pl/asie/computronics/integration/mekanism/DriverStrictEnergyStorage.java#L23) and [here](https://github.com/asiekierka/Computronics/blob/master/src/main/java/pl/asie/computronics/integration/ManagedEnvironmentOCTile.java) for the stuff needed. Just mind that you won't need to use `@Callback` methods when you instead implement `MagagedPeripheral`.

**Comment by aidancbrady** [comment]
So it doesn't matter if I don't return the highest-level class in getTileEntityClass(), then?

**Comment by Vexatos** [comment]
Exactly. You can just return a superclass there and it will call `createEnvironment` everytime it finds a TileEntity with that superclass.

**Comment by aidancbrady** [comment]
Oh, perfect. Thanks so much.

**Comment by Vexatos** [comment]
Then you cast the TE to that superclass and give it to the environment, and your Environment now has the tile it can relay all the methods to.

**Comment by Vexatos** [comment]
By the way, [OC does have a maven repo](https://github.com/asiekierka/Computronics/blob/master/build.gradle#L39-L42).

**Comment by Vexatos** [comment]
Oh, another note: Convention for OpenComputers has component names lowercase and separated by underscores, so for instance `geolyzer` or `tape_drive`. It would be nice if your blocks adopt this convention.

**Comment by aidancbrady** [comment]
.toLowerCase().replace(" ", "_") should do it

**Comment by Vexatos** [comment]
`toLowerCase(Locale.ENGLISH)` :neckbeard:

**Comment by aidancbrady** [comment]
Done!
