### ISSUE TITLE
Reactor looses all fuel on start up

### ISSUE THREAD

**Issue by Quack430** [aidancbrady/Mekanism#2834]
When ever i try and start up the reactor, it consumes all of its fuel it has store (even when set to 0) and then promptly dies before more fuel can flow in, i can't figure out why

**Comment by TacoMage** [comment]
If you're pumping in DT Fuel, that's by design. DT fuel burns instantly inside the reactor and is expended in a giant burst of energy production.  For a stable reaction you need to pump in the tritium and deuterium gas individually.  The injection rate is the rate at which those two are combined into DT fuel and burned within the reactor.

**Comment by Quack430** [comment]
thank you! that would be the problem, there arn't many tutorials out there, and the one that helped me didn't explain that.
