### ISSUE TITLE
[Suggestion] Commandos legs

### ISSUE THREAD

**Issue by hehe3301** [aidancbrady/Mekanism#2839]
Everyone loves cargo pants! And divers will often store emergency tanks on their legs. So I had the idea to implement a pair of legs that the player could keep extra hydrogen, oxygen, or energy tablets to charge their tools/armour. Which would also allow players to use the oxygen mask and the jetpack at the same time.

**Comment by aidancbrady** [comment]
One thing I really want to do is add a set of 'ultimate armor,' kinda like IC2 has with their QuantumSuit, that has a bunch of cool features.  I do like the idea of using the pants instead of the typical chest plate for extra gas/energy storage - I can picture them now, "Mekanist's SuperTrousers 3000" :)

**Comment by hehe3301** [comment]
Mekanist's SuperTrousers 3000 is an amazing name!

**Comment by hehe3301** [comment]
I cannot tell how sarcastic you were being but I was being completely serious.

**Comment by aidancbrady** [comment]
Not sarcastic at all, don’t worry.  I’m hoping I can start working on this stuff soon…
