### ISSUE TITLE
[Suggestion] Realistic tank use.

### ISSUE THREAD

**Issue by hehe3301** [aidancbrady/Mekanism#2840]
For both flamethrowers and diving gear they swap out tanks rather then then fill a tank attached to the equipment. Perhaps for items like the flamethrower and the jetpack you could implement a item slot where players could place a tank rather then a integrated tank.

**Comment by ruifung** [comment]
This would be handy to have. Why, it's just like swapping magazines!

**Comment by Mementh** [comment]
would be nice!! plus the jetpack imho needs a better tank option..

I would prefer it to also use RF for the "armor" part if we could..

concept: the jetpack has three inventory slots two are for armor/tanks

when its first built it comes with 2 gas tanks.. allows swapping.. tanks hold 24k gas and can be swapped easily while wearing

upgrades.. Armor.. abrative.. IE wears down over time.. replace one tank for this..simple to make 

RF capacitor/battery: goes in third slot.. useless without other options shoudl have 2-3 tiers of this 

armor RF complex to make replaces the regular armor upgrade with a RF powered one.. IE self repairs the armor 

Electric turbines.. no more gas usage.. flight is via RF.. should last equal to gas on first tier.. longer on second and extreme on third.. but its a trade since armor repair is using same battery

**Comment by hehe3301** [comment]
Not exactly what I was thinking of. But Mekanism is a unique tech mod and
the ability to "change the batteries" instead of recharging would be a
realistic and interesting feature.

**Comment by aidancbrady** [comment]
I'll consider something similar to this once I start on the MekaSuit armor :)

**Comment by Mementh** [comment]
armor!!! YES!!!!
