### ISSUE TITLE
Crash at startup after upgrade

### ISSUE THREAD

**Issue by harley9699699** [aidancbrady/Mekanism#2844]
http://paste2.org/jvhK5wKn

**Comment by M4vErw1kiXL** [comment]
Go to the version that is fine
then remove all Logistical sorters or someting related to mekanism inventory system
do the upgrade again and replace the pipes

try it :)

**Comment by harley9699699** [comment]
Oh my God! That'd take forever. Crap. Guess I stay on the old one then. Geez.

**Comment by aidancbrady** [comment]
@unpairedbracket, does this have anything to do with the recent inventory management changes?

**Comment by HowardRoark2016** [comment]
I believe I have the same issue. I had broke about five Advanced Logistical Transporters but crashed the moment I broke the Advanced Logistical Transporter that was attached to the Logistical Sorter. I was using the 8.1.6.250 versions when the crash occurred. I was playing SSP but now I am unable to load that world. The same crash occurs immediately upon loading the world now. I am going to follow M4vErw1kiXL's advice to see if that allows me to load this world again.

Here's my crash log:
http://pastebin.com/TCqmfsgz

**Comment by QORTEC** [comment]
I too have the same error; https://gist.github.com/QORTEC/a36332859c6e9cca229d.

I my testing this error only seams to happen when I am loading an existing world, reading the text above I'm guessing its b/c I have Mekanism blocks placed on my world... 

@M4vErw1kiXL:
Thank you for your suggestion unfortunately It's not feasible on large builds/servers. As a server admin/modpack maintainer I cannot ask my users to remember where they placed all of their Mekanism related blocks and then remove them. This process could take an ungodly amount of time, I would sooner restart the world since that would probably cause less wrath...

**Comment by Ommina** [comment]
My paste of what appears to be the same crash: http://pastebin.com/1fGD6maK

For what it is worth, I can only get it to crash when using the Logistical Sorter to pull FROM an Applied Energistics 2 charger.

Reproduction steps that work (where 'work' is 'crash spectacularly') for me:

AE2 Charger -> Logistical Sorter -> Basic Logistical Transporter

Set the Logistical Sorter filter via ItemStack to Charged Certus Quartz. Click save. Boom.

The pipe is required. It won't crash if it is just a charger, sorter pair. It does not matter if there is a destination for the pipe. It'll go yucky if there is a chest at the end or not.

No promises that other reports are using the same setup, of course!

**Comment by ruifung** [comment]
Heh, I just had a look at the code,

The variable 'side' is being accessed in the StackSearcher constructor BEFORE its initialized.... which would cause a NPE.

**Comment by ruifung** [comment]
@harley9699699 @HowardRoark2016  @QORTEC @Ommina 

Since this is a really crashy bug, heres a version I compiled that includes a few minor bugfixes made by me since 8.1.6, I've compiled it with the exact same version and build numbers so you can just drop it on your servers and players can connect without updating since this is purely a serverside crash. (Unless it's singleplayer, then you would probably want to update.)

https://drive.google.com/file/d/0BxBo-WAVAzaMQkhsN19NR1ZKclU/view?usp=sharing

**Comment by xJon** [comment]
@ruifung Is this fixed in v8.1.6.250?

**Comment by ruifung** [comment]
Uh, probably as there hasn't been any other changes to mekanism. I'm not sure though, why don't you try and tell me.

**Comment by xJon** [comment]
@ruifung I'm using you version, but can I update to v8.1.7.252 and still have it?

**Comment by ruifung** [comment]
Yes. 8.1.7 includes the fix.
