### ISSUE TITLE
[Suggestion] Helium-3 and Helium-4

### ISSUE THREAD

**Issue by nintendow131** [aidancbrady/Mekanism#2851]
Helium-4
-Created by a Fusion Reactor as a waste.

-Can be used to fill Ballons, that fly higher.

-Liquid Helium-4 can be used for Cooling.

Helium-3
-Can be created by leaving Tritium Gas alone for 12 Minutes and 32 Seconds

-Can be extracted from the Moon if Galacticraft is present?

-Can be used in the Fusion Reactor (He³+D/He³+He³)

**Comment by XFactHD** [comment]
For Helium-4 I would agree with you that it would add some good new additions, but I am against your idea for Helium-3 because reactor builds with a huge storage of Deuterium and Tritium would become senseless. I for example have a reactor that uses two railcraft steel tanks to store enormous amounts of Deuterium and Tritium. If your idea was implemented, the Tritium in the pipe between the rotary condensentrator and the reactor would get clogged up by Helium-3 and I would waste Tritium even though the reactor is not running. (I am sorry if I misunderstood how the conversion to Helium-3 should work, but this is what I understood.)

**Comment by aidancbrady** [comment]
I do have some ideas for balloons, but this kind of stuff is getting too complex for my liking. I'd rather not get too scientific.
