### ISSUE TITLE
small update

### ISSUE THREAD

**Issue by harley9699699** [aidancbrady/Mekanism#2864]
So, mine IS SP. Does that mean then, to tear out and rebuild every single Mek pipe and machine to go to 816? Or, will the next Mek version be backwards compatible to 8.1.5? Confused. Thx.

http://paste2.org/jvhK5wKn

**Comment by ruifung** [comment]
see #2844

**Comment by harley9699699** [comment]
I did. That doesn't answer what I asked though. Plus, there's no generators or tools either.

**Comment by ruifung** [comment]
I did mention, it was compiled with the exact same version number. You can just replace it over the core part of the mod. Nothing has changed in generators OR tools.

**Comment by harley9699699** [comment]
So, replace anything that has an inventory then? 
What happens after it updates past 8.1.6.249 then?

**Comment by ruifung** [comment]
No, just replace the mekanism jar file (leave the generators and tools alone if you are at 8.1.6.249) with the file provided by me.

**Comment by harley9699699** [comment]
No, the pint is I couldn't get to 816, from 815, without crashing. (hence, the other/initial bug report).

**Comment by ruifung** [comment]
And what im telling you to, is use the Mekanism-1.7.10-8.1.6.249.jar file which I made and you can download from https://drive.google.com/file/d/0BxBo-WAVAzaMQkhsN19NR1ZKclU/view?usp=sharing
Instead of the Mekanism-1.7.10-8.1.6.249.jar file from aidancbrady.com

Example:

Source                    File
------------------------------
Me                          Mekanism-1.7.10-8.1.6.249.jar
Aidancbrady.com   MekanismGenerators-1.7.10-8.1.6.249.jar
Aidancbrady.com   MekanismTools-1.7.10-8.1.6.249.jar

EVEN THOUGH MY FILE HAS THE SAME VERSION NUMBER, IT HAS THE FIXES COMPILED INTO IT.

To repeat, USE THE MEKANISM 8.1.6 jar file I provided instead of the one from aidancbrady.com for now.

Honestly. It would have been easier if @aidancbrady just released a new build with the minor fixes.

**Comment by harley9699699** [comment]
NOW, I get it. Thanks, I'll give that a try. I'm really not as think as you stupid I am. :)
Yes, he should just fix it since it's all his baby (-ies).

**Comment by ruifung** [comment]
I wasn't thinking that you were stupid, just the inevitable fact that many people often can't be bothered to read things throughly. =P

**Comment by harley9699699** [comment]
Was reading it, it just wasn't being processed by my litlte pea brain I guess.

**Comment by ruifung** [comment]
Well hey, I often prefer to be on the absolute latest versions too. o/

**Comment by harley9699699** [comment]
Oh, I'm Way past "often prefer". It's a brain-infused mandatory thing. I HAVE to be on the latest of all of them.

**Comment by ruifung** [comment]
Then compile from source! YOU WILL BE ON THE ABSOLUTE BLEEDING EDGE!

**Comment by harley9699699** [comment]
Oh hell no. Really not smart enough for that. No knowledge, at all.

**Comment by ruifung** [comment]
You probably should close this issue though =P

**Comment by harley9699699** [comment]
Okay. Thanks again.
