### ISSUE TITLE
Performance Issues w/ Mekanism Pipes

### ISSUE THREAD

**Issue by catzs** [aidancbrady/Mekanism#2866]
When using any mekanism pipes, my game slows down considerably. Perhaps add an opaque version that doesn't show contents.

**Comment by ruifung** [comment]
There's a config for it I believe.

**Comment by aidancbrady** [comment]
FPS or TPS lag?

**Comment by chaos234** [comment]
Nice that there is already a ticket like that for that.

On the server where I am playing it is realy hard to build a good flow for e. g. x5 ore production because fluid pipes are not opaque able (must change to Thermal Dynamics because Ender IO are to slow for Mekanism).

The next part are the pressurized pipes, which also causing FPS lags.

The main problem for all those pipes (icl. electical ones) are that they counted to cofh so they are always on the top in Opis with over 1000's ms.

Actually, if I am using /cofh tps I'll get only for the overworld 20.00 TPS/35.82 MS (100%) but normaly our Overworld has arround 20.00 TPS/MS. Overall is arround 44.00 MS.

I think that the way which Mekanism uses to render things is specially for the server and for the client not good, if there are no possible option to use an opaque upgrade or smth. else.

Result: With my current setup I have only 11-16 FPS as normaly +45 FPS and this with a NVIDIA GeForce GTX 970 (default ressource pack, optifine HD U1 C7, no shaders mod).

I hope that you can include a opaque option/module (like in Build Craft?) to reduce those FPS lags.
