### ISSUE TITLE
Electrolytic separator consume over 40000 RF/t

### ISSUE THREAD

**Issue by PeKlim** [aidancbrady/Mekanism#2868]
I have last version of Mekanism. Electrolytic separator with both tanks set to dump and all speed and energetic upgrades consume over 40000 RF/t. I think this is bug. Or is not?

**Comment by OntheAir3** [comment]
Hello. The bug is that the energy Upgrades dont reduce the energy consum form the Electrolytic Separator they only rise the energymemory .  I have wounder why i dont can run my old System with Gas Burning Generator and the  Electrolytic Separator and then i saw  when i put the energy Upgrades in. The energymemory is increasing but dont reduce the energy consum. At the Moment you produce so much energy how dou Need for the Electrolytic separator. I have test ohter machins by there  is alright.

When you want that the energy upgrade work correctly by the  Electrolytic separator  then use the Version 8.1.2, 

Sorry maybe for bad englisch

MFG
OntheAir3

**Comment by unpairedbracket** [comment]
This is intentional, to prevent blatant violation of conservation of energy
