### ISSUE TITLE
Steam extraction crashing

### ISSUE THREAD

**Issue by Saizetsu** [aidancbrady/Mekanism#2921]
So anytime i try to pull steam from the fusion reactor it crashes. And ruins the save. Unless i managed to break everything involving the extraction of steam. I am unable to make use of mekanism steam generation.

**Comment by ruifung** [comment]
Logs.

**Comment by Saizetsu** [comment]
There are logs? It usually kills the whole client mc stops being a process.

**Comment by Kolatra** [comment]
You need to provide the crash report that is saved in crash-reports in the Minecraft directory.

**Comment by hron84** [comment]
@Saizetsu usually, when MC being killed, a crash report is generated. If you have OpenEye in your mod list, find it in crash-reports folder of your minecraft (it lies at same level as mods folder where you copied Mekanism) . If you do not have OpenEye in your mod list, find the log directory, and upload the latest.log and fml-client-latest.log files to https://gist.github.com and paste the links here.  Github Gist takes same account as you used to report this issue, and usually does not require additional login.

Without crash log or any other information, developers aren't able to fix your problem, so I kindly ask to help speed up the process of this problem being fixed by posting your  logs, even if you cannot find any relevant info, developers maybe can.

**Comment by vedalken254** [comment]
@hron84 even without openeye, if minecraft crashes due to a forge/mod exception, it will generate a report in the crash-reports folder.

**Comment by hron84** [comment]
@vedalken254 thanks for heads up, I only know the 1.6 behavior (where crash-reports folder did not exist), some 1.7 features are new for me :-)
