### ISSUE TITLE
Placing Digital Miner in Mystcraft world, leave dimension, come back and the miner cannot detect blocks

### ISSUE THREAD

**Issue by adamcogx** [aidancbrady/Mekanism#2956]
Steps to recreate (hopefully):

1.  Create a Mystcraft world.
2.  Place digital miner and power it.
3.  Leave Mystcraft dimension (I placed a chicken chunk loader before leaving)
4.  I was away for a bit
5.  Return to dimension
6.  Digital miner has stopped mining and says there is 0 block it can mine, stop and starting doesn't change it.  But if you pick it up and replace it, it starts reporting blocks correctly.

I'm not sure what else you need to know.  But I have the miner hooked up by AE Import bus to an AE system inside of my Tardis (Tardis mod by ShaneDarkholme), it works fine as long as I stay in the Mystcraft world.

**Comment by HadesDurin** [comment]
i think it is a mystcraft related problem,
because, when i travel to a mystcraft world and come back it completly unloads from memory, as if you have never been there.
and that way it overrides the chunkloader and so the miner stopped working
the thing with point 6 is there are no blocks to scan because the area which is scanned does not exist

this is not a solution only a few thouths i have so far to this issue

if you want to mine use aromas mining dimension mod, which is a great one for mining...

**Comment by adamcogx** [comment]
Yeah, I also noticed during boot up that the Tardis mod also does something
with the dimensions as well.  I will also send the error to Mystcraft and
Tardis mods developers to get their feedback.

On Wed, Sep 9, 2015 at 7:20 PM, HadesDurin <notifications@github.com> wrote:

> i think it is a mystcraft related problem,
> because, when i travel to a mystcraft world and come back it completly
> unloads from memory, as if you have never been there.
> and that way it overrides the chunkloader and so the miner stopped working
> the thing with point 6 is there are no blocks to scan because the area
> which is scanned does not exist
>
> this is not a solution only a few thouths i have so far to this issue
>
> if you want to mine use aromas mining dimension mod, which is a great one
> for mining...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aidancbrady/Mekanism/issues/2956#issuecomment-139061410>
> .
>



-- 
Adam Greene, Lead Software Architect
adam@cognitivex.com / @aspnetaddict <http://twitter.com/#!/aspnetaddict> /
Linkedin  <https://ca.linkedin.com/in/kadamgreene>/  www.cognitivex.com
<http://www.cognitivex.com/> / 506.802.8648

*Please consider the impact on the environment before printing this email*

*NOTICE: This email and any files transmitted with it are confidential and
intended solely for the use of the individual or entity to whom they are
addressed. If you have received this email in error please notify the
system manager. This message contains confidential information and is
intended only for the individual named. If you are not the named addressee
you should not disseminate, distribute or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system. If you are not the
intended recipient you are notified that disclosing, copying, distributing
or taking any action in reliance on the contents of this information is
strictly prohibited.*

**Comment by adamcogx** [comment]
After talking to XCompWiz and ShaneDarkholm, it still seems there is an issue with the digital miner not playing nice with chunkloading / unloading.  I can place the miner in the nether start it up, leave the nether (nether is unloaded), and come back and it has the same issue (reports 0 and won't mine until picked up and re-placed).  There is an issue with chunkloaders not being respected, but the digital miner isn't playing nice chunking.

**Comment by aidancbrady** [comment]
I'm fairly certain that the issue is that the Digital Miner performs its region calculation immediately after it is loaded, meaning its surrounding chunks may or may not have been loaded previously; this means that a miner could load before the chunks around it load to mine in.  An option would be to delay the calculation by 20 ticks or so to wait on some of the surrounding region to load, or perhaps even keep a cache of the previously loaded chunk locations and then wait until those are satisfied.  I'll think about it for a bit.

**Comment by aidancbrady** [comment]
Mystcraft has not yet updated to 1.9 so I am going to mark this as closed for now.  If this issue persists in later versions I'll take another look.
