### ISSUE TITLE
[Request] Redstone monitoring of induction matrix

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2986]
when power reserves get low, need to be able to get a signal out to turn on any controllable power production

**Comment by FluffyCloud** [comment]
+1 yes please!

**Comment by tylerjcw** [comment]
This would be able to be achieved rather easily with a OpenComputers or ComputerCraft setup. These mods can interface with the API provided by Mekanism. I have a setup like this in my base and I can do much more than simply turn on power production. If I used BigReactors I would be able to throttle the Reactor down based on the amount of energy stored within my Energized Induction Matrix.

**Comment by aidancbrady** [comment]
I'd rather leave this up to computers.

**Comment by snsiox** [comment]
Only problem is [this](https://github.com/aidancbrady/Mekanism/issues/2971). Larger induction matrices will not report the proper numbers through the API that the computer mods use. If there were a redstone output for the matrix, we could determine how full it is (with a resolution of 1/15th of the total capacity, useful enough to toggle power generation) and preserve the current API.

**Comment by Landrash** [comment]
@snsiox That on the other hand might be another bug. I suggest you open a separate issue with the example your using it in, mod version and if possible you code being used.

**Comment by snsiox** [comment]
I am using an insanely old version, but the issue I referenced appears to have been closed with no intention of resolving it (because the issue is not strictly in the mekanism codebase).

I assumed that meant that I shouldn't plan on ever being able to accurately measure EIM capacities with computercraft/opencomputers, so redstone control would be the next best thing.

If other people can get reasonable numbers via computer mods with huge induction matrices with a more recent build of mekanism, I'll shut my trap.

**Comment by XFactHD** [comment]
@snsiox The problem is that the computer mods are expecting the induction matrix to give them an integer number because the RF API is based on integer values but the induction matrix uses the number format double to store those gigantic amounts of power. One thing you could do, is trying to do some math with the negative values to get the actual value displayed on screen but this would require a fair amount of experimenting.

**Comment by snsiox** [comment]
Yes, I know why it happens. The point is, it's not a glitch that will be fixed in the near future, so "leaving this up to the computers" is not an effective solution. I'm aware of several workarounds, but they are all nedlessly complex in comparison to a redstone port.

That said, it could be an accidental balance point. In exchange for the ability to store immense amounts of energy (just over 1 Peta-RF if my math is correct), the ability to easily _and_ accurately monitor it is lost.
