### ISSUE TITLE
Request: Reduce number of gas-burning generators needed for max speed electrolytic separator

### ISSUE THREAD

**Issue by Hexicube** [aidancbrady/Mekanism#2991]
Mass oxygen production is cumbersome as you need 2 generators to match the power consumption of a basic separator and each speed upgrade doubles that (which quickly spirals to 512 generators for a maxed separator).

There's a number of solutions to this problem:
- Allow using speed upgrades on a generator to burn through more hydrogen
- Compound generators to reduce number of needed blocks without reducing resource cost
- A config option to set the default burn rate higher
- An upgrade for the separator to allow it to burn the hydrogen itself

As it stands, if I want to use separators to produce enough oxygen for anything particularly demanding (galacticraft sealers, for instance), in order to offset the power consumption I would need over 30 generators running full-time. Whilst this is somewhat balanced, it can easily be lag-inducing when scaled up (I would need over 500 for my planned base).

**Comment by xenoswift** [comment]
The solution to the problem is to find alternative means to power the system.

**Comment by Hexicube** [comment]
Assuming I only have Galacticraft and Mekanism installed, what reasonable method do I have for using the separator running to power oxygen sealers through a night on the moon (which lasts 28x as long) which will never expire?

This leaves three options:
- Solar power = Needs a pretty big power bank to last the full night
- Gas-Burning = Needs a large number to handle all the hydrogen
- Bio-Generator = Needs half as many as Gas-Burning (by default), but also a farm to support it
(I've yet to try a fusion reactor, but those are probably large and complicated, overkill for this task, and require pumping heavy water which would be far more lag-inducing)

The issue is simply that there's no decently scaling alternative provided by the mod itself for this middle tier, it jumps directly from small power generation to massive power generation. Whilst this isn't an issue for one person, if you get several people doing this at the same time then there's an issue with server CPU usage.

**Comment by vedalken254** [comment]
@hexicube about the only thing I could suggest are induction matrix multiblocks for power storage.

**Comment by Hexicube** [comment]
Power storage is not power generation.

**Comment by EvulOne** [comment]
The issue you're having is lack of a "medium-high tier" of energy production.  The reason it's an issue for you though, is because you're trying to suppliment Galacticraft's oxygen needs with Mek's production (which wasn't meant to handle GC's large-scale oxygen usage)
Mek, as a standalone mod, has very acceptable power production for the uses you find with it.  It's only when you try to use its power methods to suppliment another mod that there's problems.

Your two options, from what I see, are either using GC's own oxygen production to keep your habitat aerated, or I would suggest adding another mod to make up the middle area, since you're already using more than one mod in conjunction.  Big Reactors, or Railcraft (Industrial steam engines, woo!), for example, would fit wonderfully for what you're needing.  Another option would be Thermal Expansion (whichever one of its subsidiaries has the dynamos) or the generators from Extra Utilities.

**Comment by Hexicube** [comment]
I was actually already using Big Reactors, but I'm keeping that on a mostly closed loop as I'm using the power for MFR drills to get yellorium and don't currently have the materials to enlarge it for more efficiency. I also wanted to keep oxygen systems on a closed loop so most generators were generally not applicable, as I wanted the oxygen systems to function regardless of outside factors, so failure from lack of fuel or bad time is a pretty big no-no.

I did actually also submit an issue to GC about the sealer usage being 320/s and it's going to be dropped down to 120/s, which is substantially better, but that would still require a fair amount of collectors (each leaf per collector is 2/s IIRC) as I have quite a few sealers (currently 16, should be 18 but reactor room unsealed).

My issue isn't a lack of mid-high tier power production for my mod-pack in particular, my issue is the lack of that power production that requires no upkeep for this task. Normally, that wouldn't exist, but I just so happen to get a surplus of hydrogen. I can achieve the required production, the issue is just space and CPU usage by doing so.

Is it really that unreasonable to want a more advanced gas-burning generator that costs more materials, considering hydrogen is simply an energy carrier?

**Comment by EvulOne** [comment]
Well, if you were going to add a larger gas-burning generator, you might as well add a larger electrolytic separator too.
The issue you're describing though (A no-upkeep power supply) is not solved via gas burning generators.  The energy you use to produce the O2 and H is more than the energy you then get back from burning the H in the gas-burning.  You're either using an outside power source to create  the O2 (which you could plug your sealers into) or you will eventually run out of O2 and H to burn.

You'd be more "no-upkeep" if you had a BigReactor running it (since they can produce their own fuel via laser drills) or a solar power source with a large bank of some kind of capacitors/batteries.

**Comment by mercsniper** [comment]
All of this describes the fact that hydrogen, per design, is meant to power a electrolytic separator to make it cost neutral, not provide net positive power production. 



—

**Comment by EvulOne** [comment]
And not even cost-neutral.  You get back maybe 90% of the energy you put in.

**Comment by Hexicube** [comment]
It's cost-neutral, you get free oxygen from the two machines combined. I don't know how you're losing power, but you may want to look into your designs.

A larger electrolytic separator already exists, due to speed upgrades. It goes all the way to 256x speed requiring 512 gas-burning generators to match the demand for a cost-neutral oxygen production setup (each tick produces 2 hydrogen, gas-burning generators only burn 1 per tick).

The issue I'm describing currently IS solved by gas-burning generators, it costs X power to create 1 oxygen and 2 hydrogen, and burning that 2 hydrogen gives X power back.

BigReactor reactors require fuel from the laser drill, which means I have to hit a specific breaking point in efficiency on a closed system. Any power drain on top of the drill reduces that efficiency. Whilst solar panels would in fact be 0 upkeep, the required power storage per sealer is massive (my particular base would need over 4TJ of storage, for the separators alone). It would be cheaper (by far) to just make a ton of gas-burning generators.

I didn't have the yellorium to build and fuel a larger reactor, I barely scraped enough to make the current one. I had a lot of other resources to make the base, sealers, and gas-burning generators with a bit of iron to spare. The thing that irks me is the gas-burning generator is one of the few machines that cannot be upgrades, and is one that would benefit a lot from it.

Even if gas-burning generators doubled in speed to burn 2 hydrogen per tick, that would be a decent improvement. As it stands, you need 2 for a basic separator which is an odd matching to say the least. It feels like an oversight.

**Comment by EvulOne** [comment]
You're literally describing creating something, from nothing.  If you could power a separator entirely on the H it produced, you would be creating free oxygen.  There was an issue open about this very fact about a year ago, and I'm fairly certain @aidancbrady changed it.  The issue was that the loop was self sustaining (which is what you're describing)

Gas-burning generators are not meant to be used as a source of power when ran off of electrolytic separators; they are a means of reclaiming a small portion of the energy that you used, but not all of it.

For curiosity's sake, what were you powering all these things from originally/currently, if gas-gens aren't cutting it and/or before you had gas-gens?

**Comment by Hexicube** [comment]
The separators are fully powered from the hydrogen, and my sealers were originally going to be powered by heat generators but they provide such a pitiful amount of power that I'm using the big reactor for that. The sealers have a tiny power requirement compared to the separators.

I initially had a small base on the overworld, so the separators have always been self-sustained.

I always thought that a power-neutral setup was intentional and that the issue was that you could use the loop to actually create free power, so if it's supposed to cause a power loss then the issue can be re-opened.

I'd have no issue with a power loss (90% reclaimed via hydrogen burning?), as long as the gas-burning generators become more capable of doing the power reclaiming and the loss is small but still an issue that needs to be appropriately handled. With 10% loss, that's still be hundreds of GJ through the night, but that's at least manageable with a tier 1 induction cell. ~400GJ vs ~4TJ is a massive difference, but ~400GJ is no joke. I'd also only then need about 15 large solar panels, as opposed to 150, to charge it. I'd consider a 10% loss well balanced for the task I'm performing, but it could also be configurable.

**Comment by XFactHD** [comment]
@EvulOne you need a specific amount of energy to split H2O into 2H and 1O and if oxygen and hydrogen are burned in the gas-burning generator, they create the exact same amount of energy that was used to split them. The oxygen needed to burn the hydrogen is taken from the air around the block. Just think of the combustion engine of a car. It needs oxygen which it gets from the air around it (or does any car you know of have an internal oxygen tank?).
As conclusion: It totally makes sense to be able to power a separator from the hydrogen it produces in a world where everything is 100% efficient.

**Comment by Hexicube** [comment]
I'm burning the hydrogen on the moon, where does the oxygen come from?

**Comment by XFactHD** [comment]
What you are now describing is a limit in compatibility between mods. It would be possible via GCs API to make the gas burning generator only work in a pressurized area, but because this very specific sort of compatibility is not done, the generator just assumes that there is oxygen in the area and burns the hydrogen.

**Comment by Hexicube** [comment]
But the oxygen in the sealed area comes from the separator, so no matter how you look at it either the compatibility would be off or there would be massive integration pains on at least one end.

**Comment by EvulOne** [comment]
If you're talking about a truly realistic example, we cannot regain all the energy we use to produce Hydrogen.  Yes it burns the Oxygen in the atmosphere, but there's loss to heat and other forms of energy during the process, so there is no way to have a 100% return on energy used.

**Comment by XFactHD** [comment]
But Minecraft is not realistic, it's a world where everything is optimized to be 100% efficient (except for some mods),

**Comment by Hexicube** [comment]
MineCraft isn't 100% efficient at it's core, simply due to chest mechanics it maxes out at 50% storage efficiency. Perhaps the fabric of reality will tear if untreated wooden storage devices are used in such a dense manner?

I'm talking pure balance and enjoyability here, I would like to see gas-generators be more powerful, and to compensate they should be 10% lossy.

**Comment by TheProdigy22** [comment]
Not sure if this is still active, but what about ethylene? It's EXTREMELY efficient, and would require a lot less gas burners to create a huge amount of energy. Problem is you need 20 biomass for about 30 MJ of power, so you'd need a big as heck farm (maybe automatic) to gain the power you need. Just make a big power bank charged by ethylene which should give you enough power.

**Comment by themechman** [comment]
I know what OP is doing in his post and why.
In v8, all prior understanding of the separator/gas engine should be discarded and not revisited.

GC is an oxygen hungry system. Frankly I've discussed carbon scrubber systems with the author(s) and was declined.

The proper way to get oxygen in mass quantities that you need, will require TE, Mek, and GC.
Oxygen collectors output to Rotary Condensentrators making liquid oxygen (like in real life!). Pipe this through a tesseract from TE as gasses are not transferable. Use another Rotary Condensentrator to decompress the liquid on the other side and distribute appropriately.

Also pay attention to the pipe system you use to move the oxygen! It DOES matter.

**Comment by aidancbrady** [comment]
Gas Generator now scales output rate to the amount of gas stored in its buffer.  Should be solved :)
