### ISSUE TITLE
Mekanism Reactors

### ISSUE THREAD

**Issue by iceman11a** [aidancbrady/Mekanism#3037]
For the last 2 months I been playing a round with the Mekanism
 Reactors. and well The problem has been a real pain. For more info. The programmers may want to watch this video. It will give me details on what the problems are and what I'm trying to do. 

https://youtu.be/TrnJx2BYl20

Some extra details. The idea is to maintain power for a station or base. If you have a lot of machines and need extra power. The reactor would do a better job. Watch the video. It will give more details and give you a better idea on what I want and need from the reactor.

**Comment by VT-14** [comment]
Not a programmer, but watched the video anyway.

The point of the lasers to jump-start the reaction is the fact that the reactor is a Fusion Reactor.  For such a reaction to take place, you have to reach a temperature at the core of a star.

To altar your setup post-reactor: separate your lasers from your main power line.  You only need to store something like half of the capacity of a Laser Amplifier, so sending power to your lasers after you reach that is throwing 2,000 RF/t away for each laser.  I would suggest disconnecting/turning off your lasers and adding a dedicated energy storage capable of holding enough power to start the reactor.  When that storage is full (and nothing is pulling out of it since the lasers aren't connected) 100% of your power will go to your power grid.

As for before you reactor: More Solar Neutrino Collectors.  Also, Biome plays a major part for the Solar Evaporation Chambers.  They should be built in a desert or a similarly hot biome.  Using a mod like Mystcraft or RF Tools to create an area where it is constantly day with no weather will help tremendously as well.  It will take 10 Water->Brine SECs to keep a Brine->Lithium SEC constantly running.  Also make sure that you are supplying the SECs with enough water to keep them full even when they are at their hottest temperature.

The Advanced Solar Generators on top of those Solar Evaporation Chambers are still generating power.  You can typically use those to power all of the fuel production machines, so they won't drain power from your power grid (and potentially add power to your grid).


The Big Reactors mod you mentioned in your video has the reactor control that you want.  Setting up two Rednet ports and telling one to monitor the power level, and the other to alter the control rod depth will automatically lower it's production.  You do need to do some research on how to properly set one up.  Air is a terrible coolant for that reactor. At a minimum, you will want to replace all the air in your Big Reactors reactor with Resonant Ender or Gelidic Cryotheum.  Sidenote, that's a Fission Reactor (hence no massive kick-start).

**Comment by iceman11a** [comment]
1) Then think of a way other then using the lasers to get the power you need to start the reactor. There's no sense it using all that power to start the reactor. If that much power is needed. Then the reactor is useless. 

2) It would make a lot of sense to remove  Laser Amplifiers from the main power. How ever the idea is to get the reactor to keep the  Laser Amplifier's charge up with out having to cheat. This is my idea. The problem is that to start the reactor. You have to cheat any way. 

3) As I said in the video I didn't want to do that. The reason is that there's nothing that can transfer the power from the new world back to the overworld. The tassarak's are not setup to handle that much power. and the power loss from using them any way is not worth it. This is why I don't use Buck Rogers tools. The other problem is that setting this up in a hot area mean that it will use way too much water and I never could keep up with the water. 

4) No they don't. I'm sitting here watching them. as soon as the sun goes down, The Solar Evaporation Chambers stop working. and no more gas is made. When this happens the reactor stops and shuts down when the gas stops. 

5) As for the big reactors I never did find a video showing me how to use the rednet ports. As far as I know there's no way to monitor or control them and I can't get them to power the base let a lone the rocket base. And that reactor was just a test that's why there's no water or coolant in it.The problem with those reactors is I run out of fuel all the time. I would have to cheat on the fuel. 

Last) How ever I have use Computercarft to monitor and control the reactors. It's just that this mod is not very reliable. When I log off the world. and log back in the computers are off and not running and the reactors are shut down. and my skills in LUA suck. I really didn't want to learn a new programming language. The lack of tutorials in LUA is very poor. This is why I don't have CC = Computercraft and OC = Opencomputers Installed.

**Comment by VT-14** [comment]
1) The reactor makes a ton more energy than the lasers use to start it.  The reactor is extremely expensive to set up, but is practically a solar powered creative energy cube when on.

2.0) My suggestion was Reactor -> 2 Induction Matrices.  One Matrix goes to your main power grid.  The other is disconnected from anything and will store enough power to charge a laser amplifier when you need it.  

2.1) I don't remember the exact number, but you only need like 50 Million RF to kickstart the reaction.  A single Advanced Solar Generator will produce that in 12 hours on a standard day/night cycle and no rain, and I think you have 20 of those generators on top of your SECs.

3.0) You have Thermal Expansion 4.  Tesseracts can now transfer infinite RF/t and are lossless.

3.1) You are worried about power loss with 100,000+ RF/t?  What are you doing with all that power?

3.2) The reactor takes a ton of water; that's part of the design challenge.  If you have them, use Extra Utilities' Transfer Node (Liquid).  Right below each SEC valve, place an infinite water source.  I suggest just having 3 water blocks in a line, center block directly below the SEC valve.  On the valve, place the transfer node facing the infinite water source block (the center one).  Add World Interaction Upgrades (up to a stack possible, but I think you need less than 10, maybe as little as 2 or 3) to the node to make Minecraft's best water pump.  Repeat for each SEC.  Note: Speed Upgrades are useless if you place the node directly next to where the water is going, as those upgrades just makes the node go through connected transfer pipes faster.

4.0) I have no idea what "they" is referring to.  SECs are obviously solar powered, so it should be obvious that they only work during the day.  The biome affects how long they take to cool off at night and to heat up to maximum temperature in the morning.  If you insist on not moving them to a desert, then look for another mod that will let you change the biome around them.  I know Blood Magic and one of Thaumcraft's Add-ons have ways to do that, but it's pretty rare.

4.1) If there was any confusion about the Solar Generators; then my suggestion was to hook them up to power cables.  They still generate RF during the day (unless that was changed very recently, which I doubt).

5) My Big Reactors + Rednet Setup:  This will automatically throttle a Big Reactor.  Make some passively cooled reactor with 2 rednet ports right next to each other.  2 rednet cables connecting them outside the reactor.  In the first Reactor Rednet Port, click on the battery for "Output: Energy amount (%)" and then click on one of the gray boxes next to a colored box on the left.  I just use the white on at the top left.  If you did it right, that pair of boxes should now be outlined in green, and the connected gray box should have the battery icon in it.  Hit "commit" in the bottom right to save the setting.  In the other Rednet Port, select the one with an up/down arrow and a verticle rod for "Input: Change control rod insertion" and place that one in the same color as the previous example.  Leave "Control Rod:" on "--ALL--."  Again, hit Commit.  Explanation in the next paragraph.

I used the white channel.  Rednet allows you to encode up to 16 different redstone signals on the same line with different colors, so your colors have to match to be using the same redstone signal.  The "Output: energy amount..." will output a redstone signal on the white channel depending on how much energy is stored in the reactor's internal buffer.  The "Input: Change control rod..." will receive this redstone signal on the white channel and adjust the insertion of the control rods accordingly.  If the internal buffer is empty, then the control rods will be fully active and generating full power.  As the internal buffer fills up, the control rods will insert more to slow down the reaction (producing less power, but conserving fuel immensely).  If the internal power buffer completely fills up, the control rods will be at 100% insertion, and the reactor will be off and using no fuel until power is used.

A Big Reactors reactor produces large amounts of power.  Using the auto-throttle method I listed above will cut down on fuel use.  Yellorium is fairly common, so you should be able to keep a tiny reactor filled manually, or have a large one fueled by a quarry.  Big Reactors also has Steam Turbines which will produce considerably more energy, but you can't effectively throttle those and they take Mekanism Reactor levels of water as well.  A Mekanism Reactor will typically produce more power and is effectively solar powered once optimized.

If you want a a few 1k RF/t and throttling, then Big Reactors with Rednet control and find some way of mining fuel faster than you are using it.  If you want a few 10k, then a Big Reactors Reactor + Steam Turbine will work, but is somewhat expensive.  If you want 200k+ RF/t that is practically solar powered, then make the ridiculously expensive Mekanism reactor for ridiculous energy production.

**Comment by iceman11a** [comment]
1.0) Yes I know. I just wish starting it was easy and keeping it running was easy. It would make for a better running reactor. 

2.0) I tried that before.and all I did was drain the  Induction Matrices  what I did was I had one connect go to my AE2 network and some machines I had running a long with a 5x ore processing setup I have. and it drained so fast. that I couldn't keep up. As of now most of the base doesn't get up and running. It's mostly shut down. 

2.1) Yes. I fount out about that the other day. Starting the reactor is not the real problem. It's keeping it running.

3.0) then there most be some thing wrong. If I send a 7x7x7 tank full of fuel threw one side and that 1000 buckets of fuel. and on the other end. I only get 500 bucks. There's some thing wrong. (The thing is that I'm not on the server 12 or 24 hours a day. So every thing shuts down. and stops working. 

3.1) Yes i am, AE2 Network, with auto Crafting,  TE Machines and IC2 machines. and a 5x ore processing setup. All of this drains the  Induction Matrices in less then a minute.

3.2) If you have a video on this. Then please send me the link for it. The bigger problem is lag. I can't keep mining 24 hours a day. There's no way to set that up or any thing that can run it all the time. I have 16 holes at 64x64 all the way down the the bed rock. and all I got from that was 658 pcs of the ore for the reactor. I use that up in less then 1 week. The only way to run the big reactors is to cheat on the ore and I really don't want to do that. 

as for the rest of it. the idea is that making the gas for the reactor is a joke. It needs to make it easy for some of the gases. and the only way to do that is to make the machines that require solar power is to add a power cable to them. so that way every one can keep them running. That's the biggest issue this mod has. I can make lots of brine. It's just I can't make enough gas to keep the reactor going. If every thing shuts down when it gets dark, Then the reactor will shut down.

**Comment by VT-14** [comment]
3.1) Nothing you listed seems like an obvious power hog.  I will admit that I'm not particularly familiar with IC2, and massive ME systems can take a large amount of power, but not on the scale that you are talking about.  You probably have a bug.  Make sure all your mods are up to date.  I remember when AE2 had a bug where it would use as much power as was available and void any extra, quickly draining a power grid's energy reserves.  I highly doubt that you are using enough power to legitimately drain an Induction Matrix in under a minute, as that would be enough power to run several Mine Factory Reloaded Laser Drills or a few Extra Utilities Ender Quarries with speed and fortune upgrades.

I'm not even sure the average Induction Matrix can output enough energy to drain itself in a minute unless it was specifically designed to have a (relatively) small storage capacity and huge power transfer capabilities, in which case it would effectively be a really expensive power cable.

3.2) All the videos I'm finding are making it slightly more complicated than it needs to be.  Here is the method all the videos seem to want to use:
https://youtu.be/YP_BIk7Rihk?t=35m41s

The simpler version is to have 2 Rednet Ports right next to each other and have one set to the battery (on white), and the other set to control rods (also on white), and stick 2 cables down to connect them.  The videos are needlessly bringing in the complicated Rednet Controller to save one Reactor Rednet Port.

I skipped most of the video to find the rednet stuff, but I'm pretty certain he built a descent reactor.  Keep in mind that in the config for Big Reactors is a power modifier.  Since Big Reactors generate so much more power than 99.9% of the mods out there, it is often set to use a ton more fuel or to make less power.  You may have significantly different numbers in the end.

  You can use this website to test out various designs and see what works the best:
http://br.sidoh.org/#reactor-prompt

This is the result of my 5 minutes of messing around to remember the basics.  Use this as a starting point:
http://br.sidoh.org/#reactor-design?length=5&width=5&height=5&activelyCooled=false&controlRodInsertion=0&layout=CXCXCXCOCXC3OCXCOCXCXCXC


As for your closing comment.  The Mekanism reactor makes an absolutely ludicrous amount of power once properly set up.  It is also effectively solar powered.  A 200k RF/t solar generator is insanely overpowered compared to most mods out there, which usually max out at a few thousand RF/t with an enormous number of generators.  The only way for the Mekanism reactor to be fair is for it to be insanely expensive and difficult to make.  Big Reactors is a little bit simpler and much easier to make a small reactor early on, but it uses fuel that you have to dig up to keep it somewhat balanced with other mods.  If you think that having a massive amount of power should be easier than an expensive and complicated solar generator or a Big Reactor with an Ender Quarry (or similar) going, then place down a creative energy cube.

**Comment by iceman11a** [comment]
Thanks again for your input. Lets go on ok, 
3.1)  Yes, sorry that my fault. I should have up dated you on my world. See my worlds are very large and I do have some lag to them, Sense I'm the only one that plays this world. I can make it very large. If I downloaded my world and zip it up. It would be as large as 4gbs in size or bigger. See I have a lot of machines doing all kinds of things. and I haven't even done the harder stuff that it comes with most of the mods. I have one station, A Mainbase and 4 more stations(Bases). Each one of these bases has it's design. I mean that all stations don't make or product the same fluids or machines, tools or so on. I still have  along way to go. How ever AE2, IC2 and some other mods do require a lot of power. If your running 100 machines or more. Then you need that power. Just one big reactor won't be enough.

The big problem is the fuel it needs to run. I need a fuel that's easy to get, or that I can craft it. and then make fuel with it. Or some thing. and as for the Induction Matrix. I did have it setup and I don't have it setup any more. I took all down. It just wasn't working. The thing is that I hook up the Induction Matrix to my main bases power cable and drain the Induction Matrix. See I have a lot of machines connect to that main power cable. 

It's like I said. I mite just have to cheat on the fuel. for the big reactors. 

3.2) Ok, I view it and i have one of my reactors setup like this. I'm hoping this mite save me some fuel. Where I don't need the reactor making power all the time at 100%. Thanks for the video. 

As for the web site for testing the big reactors. I didn't know how to use them or what to look for. So sorry I have no idea on how to use those pages as a test for big reactors. 

Closing) As for Mekanism being too hard or over made. I don't think so. I just think details are left out on a lot of the mod spotlights and tutorials on how to use Mekanism. How ever you are right that it does cost a lot and I do think that's wrong. The idea for the mod it to help us while playing Minecraft. If a mod it too hard to build or to craft. People just won't use that mod. I have fount that it's hard to come up with the resources for most of the machines and other items to can craft. Mining is just not enough. and remember that if I use a creative energy cube. That's still a cheat. and I'm trying to update my bases (Stations) and removing these and replacing them with real power cables connected to generators of some kind to make the power I need. 

The real reason why I use Mekanism is the 5x ore processing. If I put one gold ore into the machines. I will get 5 ingots back. and that saves my a lot of mining. 

Again Thanks for your input.

**Comment by VT-14** [comment]
Mining Tip: Use a Digital Miner (from Mekanism).  It can accept energy upgrades and speed upgrades, and will mine whatever you tell it to mine within a 32 block (square) radius in any range of heights.  With full energy (but no speed upgrades) it can be fully powered at max radius from y=0 to y=surface with silk touch enabled by a single Wind Turbine or Advanced Solar Panel and be completely off your power grid.

It is slightly confusing if you don't know how to set it up, but it will allow you to collect what ores you want very quickly.  The video is out of date, but it does show you setting up the filters and mining area correctly.  The Replace Blocks function has been moved to each item filter, and upgrades has a full tab to itself now.

https://www.youtube.com/watch?v=wkcyhnacTdQ

To mine massive amounts of Yellorite, use an Item Stack filter as shown in the video.  If you want to mine all ores, use an oreDict filter with "ore*"  (* means any letters are accepted, so ore* will mine anything in the ore dictionary that starts with the word ore, which is pretty much everything of any value).  Yellorite might be oreYellorite or oreYellorium (oreYello* for both), but if those don't work, then an item stack filter will definitely get it.

This website has common ore dictionary names:
http://www.minecraftforge.net/wiki/Common_Oredict_names

I think Uranium is also a valid ore to make Yellorite from, so oreUranium will work for gathering that.

**Comment by iceman11a** [comment]
Thank you. I set one up and I started it and I got 360+ pc of the Yello! for the big reactors. That's not too bad. One question. Can I keep it running when it gets done mining so that (IF) it can still mine more. Or do I have to bust it and move it to another location.

**Comment by VT-14** [comment]
No, you have to move it and I don't know of any ways to turn it on automatically.  I also don't have any idea how it will react to in-world movement like Funky Locomotion.

The Digital Miner is actually mining ores from the world in the mining area you set.  Unless you are somehow getting more yellorium in that mining area, you will have to move it.

I recently requested a Repeat function for the Miner.  I think redstone just pauses it.  I asked for a repeat for things like makeshift tree farms, cobblestone generators, gravity falling blocks [mines from bottom up, so it misses things that fall], etc.  Now I'm imagining the possibility of throwing a Digital Miner on a Funky Locomotion platform.

**Comment by iceman11a** [comment]
I was thinking about the laser drills that come with the Minefactory reloaded mod. where you don't have to move the drills. They just keep drilling. That would be a good idea. The idea is to place it and then forget it. I didn't want to have to try and remember to maintain that miner where I have to watch it and move it.

**Comment by GuntherDW** [comment]
Also, another tip is to not inject D-T fuel directly into the reactor iceman11,
the reactor burns up D-T fuel as fast as you can give it. It is nice for a temporary "kickstart" or boost, but it's better to input deuterium and tritium seperately.

**Comment by iceman11a** [comment]
Thanks for the info, It's just I don't have any of that stuff setup any more. I can't make enough fuel to get it going. The idea behind this was to power the 5x ore processing. That does use a lot of power. The reactor was a pain to setup.
