### ISSUE TITLE
Fork on Curse

### ISSUE THREAD

**Issue by XFactHD** [aidancbrady/Mekanism#3098]
Someone uploaded the latest version of Mekanism to Curse. It is called "Mekanism Fork" and "Mekanism Generators Fork" Did you give a permission for that?

**Comment by VT-14** [comment]
Judging by Aidan's comment to the Curse.com page, it was uploaded without permission.

I personally use Curse Voice to make my personal modpacks, so I definitely want Mekanism to have a (legal) version to download from Curse.  This fork copy already got 175 downloads in 2 days, so I'm obviously not the only one.  That said, I'm not downloading a not authorized copy.

I like Mekanism a lot, but the slightly inconvenient download/install and ad happy download pages turns me away from adding it to my private packs 95% of the time.  It does hold the record as being the only mod that I've gone out of my way to add since I started using Curse Voice though.

**Comment by BrewAndCode** [comment]
regardless of the dickery of the dude who uploaded the fork to Curse it unfortunately wasn't against the license (then nor now).  Changing the license now also doesn't impact the code retroactively.

if I was Aidan I would consider getting ahead of it but just publishing a copy there. He can always use his website to stay several builds ahead or even keep newer builds to himself.  At least that way he gets the recognition for it.  Curse has become the definitive #1 site for mods.

**Comment by gp009** [comment]
looks like its removed from curse as i cannot find it on curse, so thats good

**Comment by HanatakeYurii** [comment]
No it's not: http://minecraft.curseforge.com/members/forkingforge/projects

**Comment by gp009** [comment]
yea, i see that.  Its just I couldnt search for for that mod name on curse for some reason.  but yes, its still in his profile i see

**Comment by aidancbrady** [comment]
The project has been removed after speaking with Curse staff.

**Comment by hron84** [comment]
@aidancbrady But did  you considered to upload the mod to Curse? It would be appreciated.

**Comment by usafphoenix** [comment]
can you just upload it to curse because Ad.Fly is fuckedup and sends me  to spam or botnot pages. have not been able to download current versions.
