### ISSUE TITLE
Request: Logistical Sorter Blacklist

### ISSUE THREAD

**Issue by Malkierian** [aidancbrady/Mekanism#3136]
It would be really nice if the Logistical Sorter filters were capable of whitelisting and blacklisting items.  It's really annoying, when a Sorter hooked up to a chest that stores inventory for several BC quarries only ever feeds dirt and cobble because they are so plentiful and keep pulling only the last stack in the inventory.  It tends to clog the chest with all of the other items that just sit there.  To be able to set up a particular filter that could send out everything BUT dirt and cobble would be fantastic.

Another alternative would be to allow priorities for filters (including negative numbers to be taken after items that don't have a filter) that would be applied per item.  Having a default of 0 (or 5, if you don't want negatives) for non-filtered items, and set up a filter for cobble with a 1, to make it look for other items to eject BEFORE ejecting the cobble.

OR you could also make Size Mode filters apply even while Auto-Eject is on (don't know if that's a bug or not, but the Size Mode values for a filter are completely ignored when Auto-Eject is on).

**Comment by aidancbrady** [comment]
Filter priorities already exist assuming you're using the latest Mekanism versions :)

**Comment by Malkierian** [comment]
I am using the latest version, 8.1.9.265.  If you're talking about the order of filters, that doesn't apply when auto-eject is on, and doesn't take into account non-filtered items.  In fact, most of the time, when I have filters on a Sorter and any of them are dirt or stone, and any others exist (like the wildcard ore* for oreDict) and are either above or below them, when Auto-Eject is on, it'll take either the dirt or cobble first, and if AE is off, then it never takes anything BUT dirt or cobble.

**Comment by Malkierian** [comment]
Here, I made a few snapshots to show what I'm talking about.  This is a setup I have with two filters on it.  One has only three item filters and an oreDict filter (ore*)
https://i.gyazo.com/8fe8947b7d261c3887631e6a6b7b0047.png

and the other one has just dirt and cobblestone.
https://i.gyazo.com/a6c37c03b7771059e7b82d81ae952922.png

Here's a GIF looking at what's going on in the chest's inventory.
https://i.gyazo.com/446a19f868c23c3ef0615d91f2825466.gif

Even after adding a separate item filter JUST for the copper ore that's sitting in there, it STILL isn't getting removed, no matter what sorter it's added to.

**Comment by VT-14** [comment]
Option 1) Use a more physical sorting system.  Use a Restrictive Transport to make anything past it seem really far away (1,000 blocks), and have another place where only things like cobblestone and dirt can go.  JABBA and Storage Drawers both have void options that would fit perfectly here.  Extra Utilities has a Trash Can that can have a filter put in it to only allow you to throw away certain things.  If you only have mekanism or no way to void specific items, then you will need a large number of bins.

The idea is to give only common items a place to go on the "short" line, and by having nowhere to go on that line, everything else will go through the Restrictive Transport on the "long" line and can be properly sorted from there.


Option 2) Use a Digital Miner instead of a Quarry, and don't mine things like stone or dirt in the first place.  The two simple solutions are to use the one filter "*ore" or to set the Miner to inverse mode and tell it to mine everything except for stone and dirt.
