### ISSUE TITLE
Item mode

### ISSUE THREAD

**Issue by moonmoon97** [aidancbrady/Mekanism#3140]
i'm not sure wether or not this is just me, but i can't change the mode on atomic dissassembler, and i've tried a few keybinds.

**Comment by ktole1999** [comment]
As long as the key bind is not red you should be able to shift right click to change it


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: moonmoon97 <notifications@github.com> </div><div>Date: 3/21/2016  4:17 AM  (GMT-06:00) </div><div>To: aidancbrady/Mekanism <Mekanism@noreply.github.com> </div><div>Subject: [Mekanism] Item mode (#3140) </div><div>
</div>
i'm not sure wether or not this is just me, but i can't change the mode on atomic dissassembler, and i've tried a few keybinds.

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/aidancbrady/Mekanism/issues/3140

**Comment by moonmoon97** [comment]
Now, see, i've de-binded every key and tried just the mekanism atomic dissassembler, but it still dosen't work.. the bind key isn't red, and i've tried shifting while clicking the bind key, right mouse key etc, but it still won't work :/

**Comment by moonmoon97** [comment]
well... eh... turns out i didn't test the shift right mouse key... surprises me that i didn't, but okey, i got it working, thanks xD
