### ISSUE TITLE
Issue: Mekanism Lithium dust is Ore dictionaried

### ISSUE THREAD

**Issue by b0bst3r** [aidancbrady/Mekanism#3144]
And believe me that leads to huge shortcuts in Mekanisms processing line when Lithium ores exist in world gen.

It needs removing from the ore dictionary or given its own name, this would stop:

Tinkers construct from smelting lithium ore straight into liquid lithium.

Would stop lithium ore being crushed into lithium dust bypassing the solar evap plant entirely.

Would stop Induction cell/provider recipes from being shortcut by the above processed dust straight from ores without any mek processing involved.

At the moment we are trying to minetweaker all the other recipes out and it's just not working as not every mod has MT compatibility.

Also think about the next mod coming along and adding in lithium ores and you end up with the same scenario,  please rethink the lithium dust > ore dictionary please.

Did I say please?

Please

PS We've given up trying to MT everything as all a player needs to do is make 1 mek lithium dust and them using one of numerous ways to unify ore dictionary items can change any lithium dust into Mek's Lithium dust.

**Comment by Nova001Sol** [comment]
You can remove items from oredictionary entries with MT. I did something similar with ReactorCraft's Thorium. Here's the script I used:

val thorium = <ore:ingotThorium>;
thorium.remove(<ReactorCraft:reactorcraft_item_ingots:8>);

It should be easy enough to alter that. You'd need something like this:

val lithiumdust = <ore:dustLithium>;
lithiumdust.remove(<**unlocalized name of Mekanism Lithium dust goes here**>);

**Comment by b0bst3r** [comment]
Only problem with removing Meks lithium dust from the ore dictionary is that then breaks the recipes for Induction providers and cells, as well as other things.  

It not only requires ore dictionary removal but Meks' recipes need altering to not use ore dict lithium dust.  I've not managed to change the Induction cell and provider recipes successfully (doesn't seem to be working correctly) without it breaking them completely.

Also removing it from the ore dictionary does not stop other lithium dusts being used in the chemical oxidizer to make lithium.  In fact those 2 lines you said which I added did very little.

**Comment by Nova001Sol** [comment]
Hm. That would definitely be more troublesome. The only other option I can think of is to disable oregen for Lithium, but that might break the source mod.

**Comment by Sil3ntStorm** [comment]
OreDict removal on MT is broken somewhat. See https://github.com/stanhebben/MineTweaker3/issues/272
In any case, I generally prefer having stuff in OreDict and recipes actually using OD values. IC2 was always a pain because it never did that (dunno now they sure didn't when I last used it).

As for the recipes, it's possible to rewrite the Induction Cell / Provider recipes with advanced recipe stuff in MT. You only need to rewrite the basic one anyway because the others already depend on that one by default.
Removing the Oxidizer recipes is pretty effortless too, the only downside being if you crystallize too much Lithium there is no way to turn that back into liquid / gaseous form, at least as long as MT hasn't fixed that OreDict bug.

In any case long story short, I don't think anything needs to change in Mekanism for this.

**Comment by aidancbrady** [comment]
I agree, I don't want to remove Ore Dictionary registration for the sake of another mod's balance.  There are plenty of mods which allow for recipe modifications, as well as configurable ore gen.

**Comment by b0bst3r** [comment]
@Sil3ntStorm please try and rewrite the Induction cell/provider recipes and see what happens.

**Comment by Sil3ntStorm** [comment]
@b0bst3r I already did (you should know that) and it works just fine. What issues do you see (we should probably discuss that elsewhere like over on yours as this doesn't seem the right place)?

**Comment by b0bst3r** [comment]
If you mean the push you sent then I suggest you check the recipes for the tiers after the basic one and have a go at crafting them.

Feel free to open a git to discuss it.
