### ISSUE TITLE
Digital Miner functionality request

### ISSUE THREAD

**Issue by Cbert** [aidancbrady/Mekanism#3202]
Can you make that Digital Miner accept in Energy Slot - Thermal Expansion 4 Tesseract that configured to receive energy and configured to send items?

**Comment by ktole1999** [comment]
Just attach tesseract to back or top


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Cbert <notifications@github.com> </div><div>Date: 5/2/2016  12:25 PM  (GMT-06:00) </div><div>To: aidancbrady/Mekanism <Mekanism@noreply.github.com> </div><div>Subject: [aidancbrady/Mekanism] Digital Miner functionality request (#3202) </div><div>
</div>
Can you make that Digital Miner accept in Energy Slot - Thermal Expansion 4 Tesseract that configured to receive energy and configured to send items?

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/aidancbrady/Mekanism/issues/3202

**Comment by aidancbrady** [comment]
@ktole1999 is right, if you want to interface with energy cells or tesseracts, block form works perfectly fine

**Comment by Cbert** [comment]
Block form works, an I knew that before making this request, but it would be cooler if it works in Energy Slot.
Sorry for bugging you.

**Comment by XFactHD** [comment]
Using the tesseract in item form is not possible AFAIK because the tesseracts item form doesn't implement the necessary interfaces, it only saves your settings.
