### ISSUE TITLE
Logistical Transport pipes and Elite Factory issue

### ISSUE THREAD

**Issue by theflyingjeff** [aidancbrady/Mekanism#3217]
Currently with max upgraded Elite factories and Ultimate Logistical Transporter it only takes for the last two slots and clogging up the rest like bellow. I don't know if it is a bug or something i'm doing wrong.

![image](https://cloud.githubusercontent.com/assets/10285031/15273650/8ca3aea4-1a98-11e6-8b78-e7d8a6a22e98.png)

**Comment by theflyingjeff** [comment]
Recreated it with just mekanism installed
![image](https://cloud.githubusercontent.com/assets/10285031/15273770/bfa77b3a-1a9a-11e6-857a-48497c501ed9.png)

**Comment by theflyingjeff** [comment]
Recreated with just Mekinism installed

![image](https://cloud.githubusercontent.com/assets/10285031/15273774/d0b9b640-1a9a-11e6-944d-cf8cd58a770f.png)

**Comment by theflyingjeff** [comment]
Recreated with only mekanism installed
![image](https://cloud.githubusercontent.com/assets/10285031/15273779/ed2666ac-1a9a-11e6-86e9-3e9dabb859c9.png)

**Comment by theflyingjeff** [comment]
Currently running 8.1.9.265

**Comment by theflyingjeff** [comment]
Reproduced in 8.1.9.267

![image](https://cloud.githubusercontent.com/assets/10285031/15273823/fb2c47de-1a9b-11e6-8237-d65560991c0b.png)

**Comment by theflyingjeff** [comment]
issue recreated with all Factories.

**Comment by gp009** [comment]
question.... is your elite factory set to auto eject instead of just having the logistical transporter 'pulling' items out?  Just wondering because if its just the logistical transporter 'pulling'  the items out, its possible it may not be able to keep up with the factory at full upgraded speed.

**Comment by theflyingjeff** [comment]
It was the issue fixed now. Sorry for the inconvenience i never got the hang of the auto eject function but I understand now thanks.

**Comment by Blapor** [comment]
I'm having the same issue, with all combinations of pipes pulling or not pulling and auto-eject on or off. It seems to only be exporting from one output slot at a time rather slowly, so that once all slots have started processing it only outputs from the last two slots as items fill up all the other outputs. Running 9.4.13.349
![2020-01-06_14 04 46](https://user-images.githubusercontent.com/28818388/71841537-a54c8980-308d-11ea-96c6-4a93521ad912.png)
![2020-01-06_14 05 16](https://user-images.githubusercontent.com/28818388/71841545-a7aee380-308d-11ea-91bc-7c1f2188fdc0.png)
