### ISSUE TITLE
[Bug] Quantum Entagloporter Disconnect

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [aidancbrady/Mekanism#3273]
I have a save that have been playing on for awhile and updated Mekanism to it. The problem now is the quantum entagloporter disconnects from Mekanism conduits whenever I log in. The frequencies previously saved in the entagloporter now become useless so I have to reset them everytime.

This does not happen all the time in newly generated worlds but it happens from time to time. I have the save wherein it happens all the time. I am playing this world in my own modpack.

I hope you can find what's going on here. V9 is such a wonderful update. :(

modpack: http://minecraft.curseforge.com/projects/garden-mekanism?gameCategorySlug=modpacks&projectID=240813
save: http://www.mediafire.com/download/tdz6ko0cza8fime/Garden_Mekanism_Let%27s_Play.zip

**Comment by aidancbrady** [comment]
Are the entangloporters across dimensions by any chance? If so I may know the issue.

**Comment by TheGuyFromTheInternet** [comment]
No, I thought so too. I removed that too. Only had two in a spot and relogged. It still disconnected.

**Comment by aidancbrady** [comment]
Well that at least makes things easier on me. I'll look into it

**Comment by TheGuyFromTheInternet** [comment]
Thank you

**Comment by aidancbrady** [comment]
Would you mind explaining how the frequencies become useless?  Do they disappear or just not work anymore?  If you reconnect both entangloporters to the "useless" frequency, will it work again?

**Comment by MRuth** [comment]
In my instance, the Quantum Entangleporters still list the frequencies in the frequency list, but trying to set each entangleporter back to that frequency does not work.  One has to create a completely new frequency and then set both on that new frequency and remove the "dead" frequency.  Creating a new frequency and then switching back to the old one without first removing it does not work either.

**Comment by globsb** [comment]
They become useless. Even changing to diferent freq and reverting back doesnt make it work.

**Comment by aidancbrady** [comment]
So you can't even set the entangloporter to the frequency- it won't show up as set in the interface?

**Comment by aidancbrady** [comment]
Also, is this with a public or private frequency?  Does the issue reproduce for both kinds of frequencies?

**Comment by globsb** [comment]
The bug seems to happen only with public frequencies. Tested with private and everything works as intended. After relog entangleporter is still set to the frequency but cables are not connecting. All other previously created and unused public freq dissapearing on relog. Creating new one and reconnecting to the old one again doesnt work either.

**Comment by aidancbrady** [comment]
It's weird, I was able to reproduce this issue twice a bit earlier this morning but now I can't get it to happen for the life of me.  I'll keep researching, let me know if you have any other details which will let me narrow it down.

**Comment by aidancbrady** [comment]
The more I work with this, the more convinced I get that this is primarily a world transition issue.  The naming of frequency networks changed between v8 and v9, meaning the world loader may be getting confused when loading frequency lists.  I've now tested three different newly generated worlds with mixed Teleporters and Quantum Entangloporters, inputting and outputting all kinds of resources, with their locations in the End, Nether and Overworld, and have yet to run into this again.  If someone can isolate this with a specific process of reproducing I'll look into it again, but in the meantime I'm going to mark this as closed.

**Comment by MRuth** [comment]
Okay, I just spun up a brand new instance of MC 1.7.10 with Mekanism, CoFH core and Lib, and CodeChikenCore and ChickenChunks.  The issue is not happening upon game shutdown and reload with this instance.  Is there anywhere else that Mekanism saves information outside of the world folder that could be causing the issue as the instance that I used before was updated from Mekanism v8 to Mekanism v9?

**Comment by aidancbrady** [comment]
No. Entangloporter data is exclusively stored in world-based NBT storage and is not linked to any dimension or location- all frequencies are kept track of on world load and join. In Mekanism v8, before entangloporters existed, I stored ALL frequencies (including teleporter frequencies) with the same frequency manager ID, and as that changed in v9, there's a chance that the world storage gets confused with the update. Let me know if you encounter the issue in a new world instance that was created with v9, but as your and my testing suggests, I think what we found was something related to world conversion.

**Comment by MRuth** [comment]
Well I just switched back over to my main instance (a heavily altered version of Resonant Rise 3.2.7.2) and created a brand new world with Mekanism v9 already installed, so no upgrading from v8, and the issue happened again.  I am currently disabling any mod that I think ties in with Mekanism, so far I have EnderIO and BDew's Pressure Pipes, to see if that makes a difference.

**Comment by aidancbrady** [comment]
There may be a conflict in NBT storage identifiers that is causing issues. I can't give you any names, but narrowing the list is smart. I really appreciate your help!

**Comment by MRuth** [comment]
No problem.  Is there any way to see if another mod or something is overwriting or corrupting the NBT data in the world save?

**Comment by aidancbrady** [comment]
There are certain extensions which let you track what data is stored, but that's not going to give you details on the actual offending mod. Try removing a big hunk of mods in your current instance and see if that solves the issue- if it does, you can test within that hunk and keep narrowing down.

**Comment by MRuth** [comment]
Okay, so after a bit of testing, I have found that the issue seems to be coming from Compact Machines' implementation of Mekanism gas transfer into and out of the compact machine (a separate dimension with interactive blocks).  Either removing Compact Machines or just disabling the Mekanism integration seemed to have fixed the issue!

**Comment by b0bst3r** [comment]
I'm loathed to add EIO 426 because of this issue report https://github.com/SleepyTrousers/EnderIO/issues/3333

EIO addons is not in the pack you must have added that.

MFR is already on a newer version in BetaS

Can do ExtraCells but not EIO until they fix the above issue.

**Comment by Giovanni-NL** [comment]
Just a note to confirm the same problem happens for me using Mekanism-1.7.10-9.0.2.271.  I'm using a private frequency to transfer gas from an RFTools dimension to the overworld that stopped working.  Creating a new frequency on the sender and receiver will fix the problem.  The 'old' frequency remains broken. Going back to that frequency will not transfer gas, and then switching to the 'new' frequency will transfer gas.

**Comment by MRuth** [comment]
@aidancbrady Do you have any tips in finding out the root cause of the issue.  I have kept up with the issues of the project, and there have been several issues opened which seems to be related to this problem.  I have tried to disable and re-enable mods to find out which might be causing the issue, but after one time that I had disabled all mods except base Mekanism, and then re-enabled them, with the entangelporters working before the re-enable as well as after, I can't seem to figure a way to hunt down the problem.
