### ISSUE TITLE
Industrial Turbine UI inconsistency

### ISSUE THREAD

**Issue by Lescius** [aidancbrady/Mekanism#3301]
Sometime the turbine UI will show me the total steam flow rate and power generation, other times it will divide that by the number of ports.

Example: I have a reactor running at injection 20, generating ~750B of steam into a turbine with 2 ports. When I first built the turbine, it reported flow of 749488 mB/t  and production of 23.55 MRF. If I quit and restart Minecraft, those numbers will change to 385339 mB/t and 12.11 MRF. It's still outputting 23.55 MRF, it just shows the wrong number in the UI. Breaking and reforming the turbine causes the correct number to appear.

Mekanism 9.0.2.271

**Comment by aidancbrady** [comment]
Strange. Does this always happen, do you have some kind of defined strategy to reproduce? I didn't experience this in my testing and there's no code that would divide the generation by the number of ports.

**Comment by WhiteFire-Sondergaard** [comment]
I thin this is related, but the behavior is SO strange it's hard to say. Here it goes:

With the problems with universal cable, I have been trying other options for extracting energy from the turbine, which is now attached to a Mekanism reactor. Results have varied, none have been good. 

Cryo-Stabalized Flux Duct: refuses to pass any energy at all.

Creative Energy Cell set to input: No result. Actually this goes for a lot of other things I tried.

Hyper-Transfer Node: Flip-flops between reporting a large charge, and a large NEGATIVE charge. Which I originally thought was an extra utilities bug. Interestingly it does output energy if sporadically, but does not drain the turbine at all. Then...

Draconic Evolution energy storage multi-block: Hooking a pylon directly to the turbine had some interesting and mixed results. usually I could not get it to do anything at all. Sometimes it would output energy. Once it causes the energy storage device to turn stark white and report a growing negative charge which I could only get rid of by breaking the multi-block and yanking the core out.

Draconic Evolution Advanced Energy Transceiver: As I mentioned before, it caused this device's particle stream to glitch and energy didn't actually flow or did so inconsistently.

I am beginning to think the problem is a little deeper than a UI display error.

Of note the really strange results were all gotten with devices that can take a large or unlimited amount of power.

You don't happen to be using a signed int in there somewhere are you? :)

**Comment by Lescius** [comment]
I can completely reproduce the problem with new turbines in my original Bevo test world. I can't reproduce the problem in a minimal modpack with only Mekanism / NEI / Pressure Pipes. When I get a chance, I'll try creating a new Bevo world and testing there.

**Comment by Lescius** [comment]
I created a new world with Bevo T. The UI is still bugged after a quit/restart, but this time it's showing flow rate and production of 0 instead of a dividend of the actual flow rate. As before, the actual power output remains unchanged and breaking/reforming the multiblock fixes the problem.

I'm willing to write this off as a mod interaction, but I don't know how another mod would affect Mek's own UI.

**Comment by Ladett** [comment]
So I've been creating steam via the Mek reactor and inputting it into the Mek turbine, now this is getting silly OP,  You'll start to understand as I explain. 

I first started out with the standard setup for the Mek reactor to create RF with Mek V8 which is fine. However after updated to V9 of course I made another reactor to create steam and use the mek turbine. this is the DNS pack btw. in which we have the Pressure Pipes mod. 

Basically the pressure pipes mod transfers liquid from point A to point B within a split second. Very nice and very useful. It also has an infinite water source block. So like any good minecrafter would do ,  you think and setup the best u can right. 

1 x Mek Reactor, 2 x basic gas tanks with red and blue filled right up. 1 x water source block,  pressure pipe into the reactor and pressure pipe into 5 bedrock drums <---- !!!! and flowing from them into the biggest Industrial turbine you can make,  28 blades.

So I switch it on , within a sec I have to turn it off. Why you ask. 

the Turbine is filled up and all 5 bedrocks drums as well. 

If not had to turn this on again in a week. I've had my whole base plus a bunch of MFR lasers farms etc running. 

Hence the OP statement.

Now after thinking about it, the mek reactor works like it will turn the water into steam as fast as you can pipe it in and out which is fine for most mods. however in this case I've basically created a setup which has more power than anything else in the minecraft modding world. 

The funny thing is the only choke point is the dam industrial turbine is pain to get the power out into my dranconic teir 7 energy core. I've resorted to getting 10 ish ultimate energy cubes attached to the side of it and running cryo cables to the tier 7 core. problem being if I want to get more out of it i'm gonna have to make more ultimate cubes,  this is going to get laggy rather quickly.

So suggestion is to put a choke point on the input of water in and also sort out the power out of the industrial turbine. 

Other than that beautiful machines keep up the good work 


Ladett

**Comment by aidancbrady** [comment]
Can someone write up an exact reproduction strategy for this issue? If this is an actual issue that is reproducible every time then I need to take a deeper look. I doubt this could be an interaction issue.

**Comment by Ladett** [comment]
We've just made a new world ,  i'll test again at some point and let you know,  I did however do this a number of times with the same results,  

Mod used ,  Pressure Pipes & Mek V9 

Test 1
Infinite Water block -> Pressure pipe into -> Mek V9 Reactor -> output steam via pressure pipe -> into Mek Indust Turbine = result filled to the brim with steam.

Test 2
Infinite Water block -> Pressure pipe into -> Mek V9 Reactor -> output steam via pressure pipe -> into 5 bedrock drums -> into Mek Indust Turbine = result filled to the brim with steam.

2nd issue

Unable pull power out via Cryo energy conduit, i'm assuming that the only way would be make a induction matrix and a massive one at that?

**Comment by Lescius** [comment]
As mentioned above, I can only reproduce my problem with a full mod pack. I created a brand new instance of Bevo's Tech Pack (BTP-Reborn-BetaW, Mekanism 9.0.3.278). I created a new creative/flat world in single player. I did notice that the splash screen has a disclaimer about a turbine-related crash bug.

Reactor: Fuel from creative portable tanks feeding decondensentrators. Water from pressure pipes. Steam into pressure pipes. Fuel rate 60.

Turbine: 9x9x17 frame, 22 blades, 49 coils, 161 vents (4 wall layers plus roof).

2 ports: 1 for steam in from pressure pipe, 1 for power out to Extra Utils trash can.

I set the UI to display RF. I start the reactor and let the reactor+turbine reach equilibrium. Then I log out and log back in, and see that the steam and RF numbers in the UI have dropped by approximately 50%. The reactor is still reporting the same heat and steam numbers. In today's test, I did not attempt to externally measure the turbine's RF output, but in previous tests it has remained unchanged.

In today's test, attempting to break the turbine caused a crash. Presumably this is what the splash screen warning was talking about. I don't know if that issue is being tracked elsewhere.

**Comment by Rayder44** [comment]
I think Ladett's issue regarding the Fluxducts relates to the energy buffer in the turbine.

I've had this issue previously, but I've found that if you don't let the buffer fill up, the Fluxducts work perfectly. Sometimes they might appear disconnected (upon reload, for example) but a block update rectifies this issue.

But I've found on a turbine that is at maximum size, the fluxduct disconnects, and no power can be drawn even after replacing the cable. I've also found that at this point if you try to break the turbine multiblock, the game crashes and the world becomes corrupted.

I think the issue is that the number gets too high. As in, the number representing the energy buffer becomes so high it gets bugged.

**Comment by Rayder44** [comment]
Upon further testing, I can say that the crash is not related to the buffer reaching extreme levels. I had a crash this morning with the buffer filled around 10%. However I still believe this problem arises from the energy buffer. There may be a relation between the Thermal Dynamics Fluxducts, but I can't say for sure.

However, to counter this issue what I've done is install a "bleeder line", of sorts. While the Fluxduct is theoretically unlimited, its benefit is mostly pointless when it's not working. What I've done is run a second line from the turbine to my induction cell using Mekanism's native energy cables.

These are not unlimited and hence hit the transfer cap quite easily, but it helps to drain the buffer in the event the Fluxducts refuse to cooperate. Stragely, once the energy buffer is empty the Fluxducts begin to work again.

So I can confidently say that this issue is related to the Energy buffer, but I'm yet to confirm it's entirely the fault of the Turbine.

**Comment by Rayder44** [comment]
I've done some further testing with this issue, and I can say that it's not necessarily a result of the energy buffer reaching extreme levels. My turbine suffered this problem at only 10% capacity.

Another thought I had was perhaps this issue is related to the steam buffer reaching its limit? I'll have to do some testing later but from memory I've only witnessed this issue when the steam buffer fills and doesn't empty fast enough.

**Comment by aidancbrady** [comment]
Merging with #3837. Similar issues can be encountered with EIM
