### ISSUE TITLE
[suggestion] nuclear reactor

### ISSUE THREAD

**Issue by Anghelos92** [aidancbrady/Mekanism#3315]
You made an awesome job with mekanism and now with defensetech. Do you think a nuclear reactor and the intregration of the uranium processing with nukes of defensetech will ever be added to mekanism? Also I want to make some considerations about the energy production of your mod. I think is the best tech mod to use in raid servers but also in general server but I think power generation has no equilibrium and sometimes too OP. For example renewable resources output too much power for too cheap cost and some non renewabe output too low for the cost and the problem you must provide fuel. I know that most settings are configurable but most server owners leave them default so I think it' a better idea uniform power consuption and production to mods like thermal expansion or industrialcraft. The fusion reactor is then a case of its own. I know the cost to make is high and all but it's a false myth that fusion power give so much energy in reality. In fact the actual Project for the first fusion power plant will output the energy equivalent of a middle sized fission power plant. I think if you ever add fission reactors, this and the fusion should output quite the same amount of energy, (what you think about 10k j/t?) lower the cost and the difference will be the fuel ( infinite for fusion, long running but difficult in the processing for nuclear) fusion will have a greater cost to make the infrastructure and nuclear will produces wastes difficult to store and deal with (i have some ideas). What do you think? Maybe you will ignore this post, in any case I want to thanl you for your mods and your work. :)

**Comment by mimikal** [comment]
Yep...

**Comment by Acdrybones** [comment]
good idea

**Comment by aidancbrady** [comment]
Fission power is something I'd love to do in the future :)

And as much as I appreciate your suggestions, I am not planning on changing the default balance of fusion anytime soon. I noticed your reference to the joint ITER tokomak fusion project, but there's a couple factors you need to realize.

First, the tokomak design is not the same as the the internal-confinement fusion (ICF) style utilized in Mekanism. There has yet to be a full-scale prototype tested using this strategy, with the highest power output ranging only up to 1.2 MW in the largest testing facility. This gives me a bit of designing leeway to come up with my own energy output values.

Also, you described this "false myth" of fusion energy output. While it is true that the ITER project will be producing less energy than one would expect using fusion technology, that is because ITER is not planned on existing as a commercial power plant, rather as a form of proof to highlight break even in power output as proving the technology to be viable to the public. Even with this said, my values are actually consistent with ITER's "low" planned energy generation of 500 MW- my fusion reactors produce just 3.5 MW with the minimum injection rate. In fact, at the maximum injection rate of 98, the reactor produces less than 175 MW. If you wanted me to be consistent with the DEMO project's expected production of 4 GW, I'd have some serious tweaking to do on my end :)

Sorry if the formatting is bad, I'm on mobile. I'd be happy to discuss possible balance of other power generation methods, but like I said, I think I'm going to leave fusion alone.

**Comment by XFactHD** [comment]
If you inject the fuel in the intended way (separately), the output is limited to 175 MW but if you inject d-t-fuel at the rate 6 fully upgraded rotary condensentrators can manage, the energy output goes up even higher.
