### ISSUE TITLE
[1.9.4] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#3361]
I have been getting a few of these as I'm testing Mekanism in my modpack:

When I first loaded the world: http://pastebin.com/JvpH45uh
When I placed a pipe: http://pastebin.com/2K2nHHCT
When I took Planks out of the Precision Sawmill: http://pastebin.com/7yKQ9EbK

Doesn't seem to be happening in a minimalistic modpack (JEI, Journeymap, Inventory Tweaks and Mekanism)
Edit: got one with minimalistic modpack when trying the oredictionaryficator: 
Crash Report: http://pastebin.com/yYMsSmrr
Log: http://pastebin.com/3xkazrpm

and more:
Log: http://pastebin.com/u2VPzQnj

**Comment by aidancbrady** [comment]
Believe it or not, not one of those crashes mentions Mekanism at all. Likely why minimalistic modpacks did not experiencing crashes as often. I'd suggest opening issue reports to the developers of the mods mentioned in the stack traces.

**Comment by Xiaminou** [comment]
Interesting, because all of it is fixed by removing Mekanism, but okay I will.

**Comment by blay09** [comment]
Mekanism is handling network packets on the wrong thread which is likely causing the issue with all these mods. Ever since 1.8.9 IMessageHandler is no longer called from the main thread, so if you want to interact with pretty much anything from Minecraft you need to wrap that code in a Runnable and pass it to Minecraft.getMinecraft().addScheduledTask() / the equivalent method for servers which I believe is in WorldServer.

**Comment by aidancbrady** [comment]
Thanks for the heads up. Should be fixed in this commit: https://github.com/aidancbrady/Mekanism/commit/e4aed3f7c1268ebe5ad2075041174a11bbec8aa1
