### ISSUE TITLE
Mekanism intermod compatibility with EnderIO.

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#3504]
Good evening,

I've updated to Mek's 286 release and I am having an issue where I cannot transfer rf between two EnderIO capacitors using Mek's universal cables.

Image here: http://imgur.com/fQ94y6n

What you're seeing is a full capacitor (like an rf battery) trying to send power to an empty one to no avail.

For testing purposes, I tried the Ultimate Energy Cube (one discharged, one fully charged) with an EnderIO conduit and could transfer power without any issues.

I'm running:
Mekanism 1.10.2-9.1.0.286
EnderIO 1.10.2-3.0.1.73_beta
EnderCore 1.10.2-0.4.1.41
FML 1.10.2-12.18.1.2011
on Minecraft 1.10.2

If I have neglected anything that would be helpful, please let me know

**Comment by aidancbrady** [comment]
Thanks for the well-made bug report, appreciate it.

The main issue here is that the RF API has not updated yet to utilize capabilities, which Universal Cables require in order to interact with other blocks. Mekanism's energy system has already updated to use this function, which is why you'll find that Universal Cables work fine with Mekanism content. Furthermore, any blocks that utilize the Tesla API should interact seamlessly with Mekanism, as the API supports capabilities.

I've spoken to the EnderIO developers about this, and it seems that they are still not quite sure whether or not to integrate with the Tesla API.  If they did, you'd find that the cables would once again work as intended.  You could try submitting an issue request on their page, though I can't guarantee results :)
