### ISSUE TITLE
[Issue] Tesselating block model

### ISSUE THREAD

**Issue by Moustik2002** [aidancbrady/Mekanism#3534]
Hi,

Random client crash when i'm in my base, it seems to begin to happen since i've built a boiler.

Crash log : http://pastebin.com/qQqD8yf6

**Comment by Apocryphai** [comment]
I'm having the same crash being caused by a Dynamic Tank, seems to be the Structural Glass that's doing it. My log is here: http://pastebin.com/eWYKcsu6

Still happens with Optifine removed, also WAILA, WailaHarvestability and Wawla removed. Running a modified AllTheMods pack, no shaders, Mekanism 1.10.2-9.1.0.288. Already opened this as an issue on AllTheMods and closed when the Dynamic Tank was identified as the cause. Previous report, including link to full forge log [here](https://github.com/whatthedrunk/allthemods/issues/80).

Let me know if there's anything I can do to help track it down.

**Comment by thiakil** [comment]
Both logs contain Optifine. If you can produce it without OF we can look into it.

OF is causing a chunk list change of some variety from simply getting a light value.

**Comment by thommy101** [comment]
What a coincidence, I'm currently also looking into this issue. I've found a error which I'm currently fixing ;)
