### ISSUE TITLE
Flying Not Enabled on Server - Jetpack Issue

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3665]
Running into this problem again as I thought it was fixed on 1.7.10 but I'm seeing it on a 1.10.2 server I play on. When using the Mekanism jetpack I will get kicked from the server with the "flying not enabled on server" message. It seems to do this if you use too much thrust, ie if you fly straight up for a few seconds it gets mad and boots ya. If you kind of go up/down/up/down while flying it seems to behave ok.

On the same server, no issues with the Extra Utils Angel Ring so I *think* this is a Mekanism bug.

Minecraft: 1.10.2
Mekanism: 9.1.1

**Comment by Stuart74** [comment]
I believe Angel Ring is more creative flight than jetpacks.  Why modded servers disable flight is silly in my opinion.  But i believe you were talking about this fix back in 1.7.10 

https://github.com/MachineMuse/MachineMusePowersuits/commit/569c9b27de812a1e6153022697db5352b4680158

https://github.com/MachineMuse/MachineMusePowersuits/commit/f8ddad0a6a548342ff18220e48d0405ec71a557a

**Comment by VT-14** [comment]
Servers don't disable flying; they just forget to enable it.  The vanilla server config file defaults that option to false.

Yell at your server admin to fix the "server.properties" file by setting "allow-flight" to true.

**Comment by Stuart74** [comment]
Yes i am aware it is set to false by default I don't need to yell at my server admin to change it i am the server admin :P  I was merely stating i do not understand why server admins disable it on modded servers.

**Comment by VT-14** [comment]
My answer to you was 'it just gets missed when first making the server.'  Mistakes like that are common. I'm pretty certain all but one of my personal servers used a whitelist where I forgot to add anyone (including myself) to the whitelist before trying to log in the first time.  Allow-flying could go a while without getting caught.

The "Yell at your server admin..." was for Utildayael, as the issue is the server is set to the default of not allowing flying when it really shouldn't be; so someone with access to change that file needs to fix it.

**Comment by Utildayael** [comment]
Doesn't that setting allow anyone to fly?

It's clearly not an issue as *other mods* work fine with it not set.

**Comment by VT-14** [comment]
allow-flying=true just sets it so you don't get kicked if you are in the air (and not changing altitude?) for more than 5 seconds.  It won't give anyone flight; it just removes the check for 'illegal flying' and subsequent auto-kick.

'other mods' sometimes (and probably unintentionally) work around it.  Extra Utilities literally triggers creative mode flying.  Things like Simply Jetpacks in 1.7 would slowly descend, as would gliders and the new elytra.  Heck, your jump and fall technique for Mekanism's uses altitude changes.

Meanwhile Mekanism's jetpack can be set to hover, which will keep your altitude steady for more than 5 seconds.

Aidan could spend a bit of time figuring out a way to bypass it, but he really shouldn't.  It's already a (vanilla) config option, and intentionally bypassing configs is a bad idea.  The other option would to rework how the jetpack functions, which he may do at some point.  Input on that belongs in the Mekasuit Discussion issue. #3108 


Either way, your immediate concern is to let your server admin know about these.  Either flying is allowed and they need to fix the vanilla config, or flying is not allowed and they need to remove Jetpacks, Angel Rings, etc.

**Comment by Utildayael** [comment]
Appreciate the info and you're right, no point reinventing the wheel!

**Comment by Stuart74** [comment]
Bypassing Configs is a bad idea ??? Maybe somebody should tell that to Gregtech and a lot of other mods that do the same thing.  As i linked above Powersuits managed to override / bypass / workaround  the Vanilla Allow Flight option and also Aiden implemented the same code in the 1.7.10 version i see no reason it cant be an option for the 1.10.2 version but should not be a priority since it comes down to the server admin to fix it not a mod dev.

But saying intentionally bypassing configs is a bad idea to me is false since there a lot of other mods that do such things especially mods that unify the ore dictionary instead of having multiple types of the same ore. 

I might be mistaken though....

**Comment by bookerthegeek** [comment]
@Stuart74 A lot of people do crack cocaine and/or commit adultery. Does not make it a good it a good idea.

**Comment by Stuart74** [comment]
@bookerthegeek make it a good it a good maybe you need to quit the crack cocaine

**Comment by HenryLoenwind** [comment]
Should Forge actually provide an event to check if the player is using a valid method of flying instead of the vanilla check for creative flight? Someone might want to PR such a thing...

**Comment by VT-14** [comment]
@Stuart74 

Bypassing a choice made by the users of the mod (either players or the admins) is a bad idea.  I think the well known config that Greg 'bypassed' was something to due with how many planks you get from a log; and that was an absolute s***storm so bad that I know about it, even though it was before I started playing Minecraft, let alone modded.  That Gregtech + Tinkers' Construct wood thing is another example of why config bypasses are a bad idea.

...Though the reason I say they are a bad idea is that they are practically anarchy in nature.  An Admin says that this is not allowed, and then a mod comes along and bypasses it.  If a server doesn't allow AFK'ing, and you make one of those water loops to bypass an auto-kick; you know you will get banned if you get caught.  A mod intentionally bypassing set rules will be similarly removed from a server.

The Ore Dictionary is added by Forge, which is essentially Modded's Vanilla.  Forge gets a mostly free pass on vanilla changes as most mods are based off Forge.  As for your argument; no.  The Ore Dictionary is something mod devs have to opt into.  A mod can add "copper" without registering it to the ore dictionary and force you to use that mod's copper, which means you could have 2 or more copper ores.  Obviously that's obnoxious and is the reason the Ore Dictionary is a thing.  Mods that don't use the ore dictionary when they clearly should are rare and usually ostracized into obscurity.

@HenryLoenwind I would be happy to see Forge 'fix' that vanilla config into something useful.  If a server is configured for flying to not be allowed, then mods should respect that and not bypass it (intentionally or not).  The Vanilla Elytra do create a slight gray area on how that should be handled though.

**Comment by HenryLoenwind** [comment]
I don't see much of a gray area here. That config flag is to prevent client-side-only (a.k.a cheat) flying. The moment the server is involved, either by creative mode or by using a legitimately acquired item (elytra, jetpack, ...) that config flag should no longer matter. In the past this was pure opinion, but now that even a vanilla item works that way, I think we can take that as "the way the game works".

If a server owner wants to disable all forms of flying, then they should disable the crafting (and loot gen) of all items that give flight or not install a mod that gives flight in the first place. Same as with any other feature that would be cheating in vanilla, e.g. pulling diamonds out of the ground without mining out their gen layer---in vanilla that's called X-ray-cheating, here it's called digital miner.

**Comment by Stuart74** [comment]
@VT-14 Is this why in my modpack we have multiple types of copper and tin and  this has been a issue in every modpack that i have seen or played that was why the forge lexicon was made by thermal expansion to turn all the different ore types into whichever one we preferred it to be.

Its still a issue. Just look at the different types of steel there is like 3 to 5 types of Steel ingots depending on which mods you have and not all are comparable to use such as Electrical Steel from EnderIO  i don't see him being ostracised or anything due to him forcing people use his version of steel, then you have RotaryCrafts Steel, Immersive Engineering Steel. 

So not really sure where your getting your information regarding mod devs being ostracised into obscurity for forcing people use their version of ores.

Gregtech was the extreme example he did more than over ride a config he placed malicious code in his mod if it detected tinkers construct and caused your game to crash this was also done by the dev for bees this is more serious than somebody changing how many logs you get back, I seriously think what your trying to say is quite incorrect as there are plenty of mods that do this such as Minetweaker etc etc, how do you think all these skyblock challenge maps are being configured. 

I yet again mention Extra Utils that has coded its angel ring to be detected as creative style flight and back in 1.7.10 both mekanism and Powersuits did fix code to ensure you would not be kicked on servers with flight disabled .  

Anyhow i am done with this conversation it is just going in circles but i do agree to some of your points but i think that they are factually incorrect in part.

**Comment by VT-14** [comment]
Electrical Steel, Dark Steel, and (normal) Steel are 3 different things.  Electrical Steel Requires Silicon, while Dark Steel Requires Obsidian.  Normal Steel has a few different ways of making it, but usually just requires processed coal and a lot of time.

Not being able to think of any mods that add things like copper or tin without using the ore dictionary is the point I was trying to make.

You can remove duplicate ores by disabling the ore gen for those extra ores in those mods configs and only leave one mod generating each type of ore.  It's very common for major modpacks to do that.  Got IC2 and Mekanism? Just turn off one of their ore gens for copper and tin, and increase the generation of the other's if you think the balance is off.

MineTweaker is all configs to be set by the players/admins.  Bypass mods like power converters and MineTweaker do have their place, but are added by the people making the rules for that pack.

Last word for the win, am I right? (sarcasm)


@HenryLoenwind I don't know enough about the specifics of how that config works.  There seems to be a somewhat fine line between flying and gliding, but I'll leave how that should be determined to the mod dev community to agree upon.

**Comment by Stuart74** [comment]
@VT-14 IF it helps you sleep at night sure you win i honestly couldn't care less either way its gone a bit off topic anyhow. I personally think if server admins are disabling flight on there mod pack and keep jetpacks and the like in the pack there not too bright.....

You also completely disregarded the fact that mekanism and other mods have in the past versions over ridden vanilla configs in regards to flight being disabled server side that was my main point and in all honesty its not a game breaker especially with Elytra now in the game. I have even tested if the gliding will kick you and yes it does under certain circumstances. I personally don't see a major issue with this sort code overriding the server properties. 

As henry stated if a server does not wish flight they should remove all items that allow flight. Still this is not a high priority at this time for mekanism but it would be nice to see implemented further down the track. 

Enjoy the win @VT-14 go to the head of the class :+1:

**Comment by Utildayael** [comment]
I'm just happy to hear flight mode doesn't give everyone creative flight. My server admin seemed to think that was the case so he argued about changing it. Finally did and realized I wasn't making it up. :)

No flight packs are hard with Mek as Aidan doesn't give you very good *item* control in the config a which is odd since he gives great block config. I asked for this a looooong time ago and was denied so the fix is to minetweaker the recipe for jetpacks. It works tho not as nice as having a config to flip.

**Comment by aidancbrady** [comment]
My implementation of flight control has not changed between versions, and my obf mappings are up-to-date for 1.10.2.  Still, strange this is occurring.  I'll look into this again if it turns out I'm doing something wrong on my end.
