### ISSUE TITLE
[1.10.2] Mechanical and Thermo pipes require replacement after server restart

### ISSUE THREAD

**Issue by Archadia** [aidancbrady/Mekanism#3678]
A recurrence of #3460 from user EzR3aL

Mechanical and Thermo pipes do not work after a server restart and require replacement in order to function again.

**Forge**: 2065
**Minecraft**: 1.10.2
**Mekanism**: 9.1.1.290

**Comment by BaalEvan** [comment]
[1.10.2] [Mekanism-1.10.2-9.1.1.290] [All the mods - 1.10.2 v1.13c] I think it's affect all kind of pipes. 
I have room with Adv. Logistic (from furnace to chest), Adv. Mechanical (Pump to Electrolytic Separator), Adv. Pressurized (Electrolytic to Puryfying) and after restart only Universal Cable works.

But in same time in other room i have Logistic connection between (actually addition) auto-breaker and chest and this one works (sometimes) after restart.

**Comment by Utildayael** [comment]
It's all pipes. I've noticed it much moreso when the pipes travel across a bunch of chunks. For example, the main power line in my base goes across about a dozen chunks [ultimate univ cable] and it will just "stop working" sometimes from server restarts or really anything that unloads the chunks such as if I leave the area for a long time to go mining in Mining Dimension or Nether or whatnot.

Breaking the pipe and replacing it fixes the issue but it's super annoying and you lose the "buffer" contained in the pipe [power/fluid/etc] which can be very painful given how large the buffers are. TBH this has been an issue since Mek v8 on 1.7.10 and I think @aidancbrady has put a few fixes in for it as I know I've reported it before but it just keeps coming back. I've even tried throwing down chunkloaders everywhere and still have the issue when server restarts which is sadly somewhat often on our pack since so many of the 1.10 mods are buggy as hell and we have a large pack. 

If you look at the pipe you'll see something like:

xxxxxxooooo

x = has power and visibly shows it
o = no power and visibly shows no power, ie pipe not lit up

Next time I see it break I'll have to check it against chunk lines to see if that is it. Like I said, chunk loaders across your base help but... that's not ideal either and pisses off the server admin. :)

Cheers

**Comment by aidancbrady** [comment]
Fairly certain I've found the issue after some intense testing.  The transmitter network formation algorithm takes a copy of the set of "orphan" transmitters whenever it creates the shared transmitter network, and then once finished, clears the original orphan transmitter set.  Well, 1.8/1.9's world threading has made it possible for new orphan transmitters to be added DURING the network creation algorithm.  As such, the new transmitters were being lost when the algorithm cleared the orphan transmitter set.  I've made some changes to ensure no orphans are lost in the network creation algorithm, and no longer am experiencing the issue.  I think we're good!

**Comment by Utildayael** [comment]
Woot!!!

**Comment by Archadia** [comment]
Good

**Comment by Avamander** [comment]
I'm having the problem again with 1.11.2 see #3460.
