### ISSUE TITLE
[Bug?] Annoying 9.1.1 update news despite no 9.1.1+ version in MC1.7.10

### ISSUE THREAD

**Issue by karakufire** [aidancbrady/Mekanism#3682]
I always play minecraft with Mekanism in 1.7.10.
Every time entering to play the world, Mekanism says the update news of 9.1.1 version for ONLY "1.9 or 1.10".

**Comment by VT-14** [comment]
I'm pretty certain there is a config option to check for mod updates.  Turn that off and it will stop annoying you.

**Comment by bookerthegeek** [comment]
Their is an update to 1.7.10 but it is a failed build that did not get pushed out. 

We should not need disable this as what happens when a new 1.7.10 version is released? We would never know! :(

Can we by default have the update checker NOT check for different minecraft versions, and make sure it is also not checking for failed builds?

**Comment by VT-14** [comment]
Once Aidan uploads Mekanism to Curse, I'll keep up with updates by seeing and clicking on a green 'download update' button.  :P 

My 'turn off the config' was intended as a temporary workaround.  I agree that it would probably be a good idea for Mekanism to not try searching for updates in other versions of Minecraft.

**Comment by aidancbrady** [comment]
This is done in 1.10.2 versions, checks are done based on game version instead of universally as they were done before. Disabling "UpdateNotifications" will solve your issue for now.
