### ISSUE TITLE
1.10.2 - Electric Pump (Mekanism) will not send water via Fluid Conduit (Ender IO)

### ISSUE THREAD

**Issue by viper2g1** [aidancbrady/Mekanism#3710]
MC: 1.10.2
Forge: 12.18.1.2073
Mekanism + Generators + Tools: 9.1.1.290
Ender IO: 3.0.1.96_beta

Ender IO's energy conduit will connect to all machines needed for tier 2 ore processing and the electric pump (haven't tried anything else yet).  Ender IO's Fluid Conduit (also tried Pressurized and Ender Fluid Conduits with same results) will seemingly connect to the Mekanism Electric Pump but no water will be transfered (with a complete line or without).  The same configuration with a Mekanism Basic Mechanical pipe will transfer water.

**Comment by viper2g1** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/3649

**Comment by Utildayael** [comment]
Make sure your ender IO pipes are set to extract. [you probably did, just saying]

The ender io energy conduits are... a different issue that the EnderIO dev refuses to fix. @aidancbrady said it is due to them not properly implementing Tesla API and when I posted the info on the EnderIO Git, the dev pretty much told me to get bent and ef Tesla. I'm sure he's a blast at parties too. They work for machines but have issues pulling energy from induction matrix and energy cubes. Likewise, Mek power cables have issues interacting with EnderIO capacitator banks. I know your issue was with liquid pipes but just FYI as I'm sure you'll run into this soon enough.

Sad really. I love the enderio conduits for the simple fact you can run them all in one block which, afaik, is the only mod that does that. Super handy for clean setups. I wish Aidan would do those in Mek... ;)

**Comment by ShadowDrakken** [comment]
Seems just as likely that it's an issue with Mekanism not correctly implementing RF. EnderIO gets heavy daily testing on ForgeCraft. Mekanism gets much less testing, and has a TON of compatibility issues with a range of mods.

Not saying EnderIO is innocent, just that if you look at the situation and Mekanism's history as compared to EnderIO's, signs point the other direction.

One thing I can say for certain though, is that my server was stable until I installed Mekanism. Now I get mod cross-compatibility errors 2-3 times a week, at which point I have to avoid letting Mekanism and the other mod accidentally touch for fear of it wrecking the server.

I know it's entirely possible that Mekanism is the only mod doing things right... but it's more likely that it's the only one doing things wrong.

**Comment by viper2g1** [comment]
The error was my own, I had to toggle the redstone activation signal to always active.  This works beautifully.  I've never seen any other mod conflicts that ShadowDrakken has referred to.  

I do like Utildayael's idea of Mekanism style conduits that fit in the same block :)
