### ISSUE TITLE
1.10.2 Electrolytic Separator's energy upgrades isn't working

### ISSUE THREAD

**Issue by LordHellscream** [aidancbrady/Mekanism#3731]
Version : 1.10.2-9.1.1.290

Repro: put 8 x energy upgrade into the Electrolytic Separator, and watch the energy consumption (I am showing RF, so 160 RF/t with 0x energy upgrade, and 160 RF/t with 8x energy upgrade)
I am pretty sure any number (1-8) doesn't reduce the energy consumption in anyway. Speed upgrade however increase it, so 1x speed upgrade and 8x energy upgrade = 320 RF/t.

**Comment by VT-14** [comment]
Intentional.  Energy Upgrades only increase the energy storage buffer in the Electrolytic Separator.

Electrolytic Separators can produce Hydrogen, which can be burned in a Gas-Burning Generator to produce power.  This is locked at 100% efficiency.  Hydrogen is intended as a form of energy storage, not energy generation.  You need to make Ethylene to generate energy with Gas-Burning Generators.

If you could generate power with a Water -> Hydrogen -> Combustion (back to water) loop, then you would break the laws of Thermodynamics.  Technically you shouldn't get all of the power back, but it's a game so most people don't care all that much that there is an unrealistic 100% efficiency.


I would suggest that the Electrolytic Separator not accept energy upgrades at all.  This special situation just leads to confusion, and I don't see any real benefit from a larger energy buffer.

**Comment by LordHellscream** [comment]
i am only doing the 3x ore processing, so I just need the oxygen for purification. and the entire pipeline is slowed down because I cannot afford to speed up electrolytic separation (RF cost), I am not using it to generate free power.

**Comment by VT-14** [comment]
Gas-Burning Generators burn Hydrogen at 100% efficiency (in Mekanism).  You get exactly as much power out as you put in.  Oxygen is practically free with a small bit of infrastructure set up.

For full speed, you need 2 generators for 0 speed upgrades, and each upgrade doubles the generators (1 speed upgrade needs a total of 4 generators, 2 upgrades need 8...).  Once it has gotten its initial kick, the system is self sustaining.  The only energy draw would be your water pump, and some mods have theirs run for free.

The cheap early solution I use is 0 speed upgrades and 2 generators; and a several gas tanks for a bunch of oxygen storage when I'm not using it.
