### ISSUE TITLE
Cables, pipes, and tubes not updating.

### ISSUE THREAD

**Issue by Mahdniss** [aidancbrady/Mekanism#3741]
The universal cables, logistical/mechanical pipes, and pressurized tubes do not update themselves after server restart. Only picking up the blocks and replacing them fixes them.
The screenshot provided shows the items trying to enter the pipes to no avail. I had already replaced the mechanical pipes, universal cables, and pressurized tubes before committing to this post. I even tried coloring the pipes to see if that fixed the issue. It did not.

Mod pack: All The Mods version 1.19
Mekenism version: 1.10.2-9.9.1.290
Forge: 2076
Sponge (if necessary): Spongeforge 2073 
BETA-1696
Operating System: Ubuntu Linux 16.04 (for minecraft server)

![screenshot 1](https://cloud.githubusercontent.com/assets/6937557/18233842/1030c830-72c1-11e6-9b9d-d7e05a9672ab.png)

**Comment by Utildayael** [comment]
I've seen this happen on our server as well with all Mekanism 9.x versions. It seems to be worst if it loads and some parts aren't chunkloaded, ie you have a large base. Very annoying I agree.

I had to stop using Mekanism power cables [the worst offender as I usually have the longest runs with them] because of this. You lose all the buffered fluid/gas/energy as well which is really painful with ultimate pipes given their large buffers.

**Comment by aidancbrady** [comment]
Already reported, very strange issue. I'll try and have a fix soon.
