### ISSUE TITLE
Mekanism models causing crash in TiCo Workbench

### ISSUE THREAD

**Issue by utoc** [aidancbrady/Mekanism#3748]
Crash here: http://pastebin.com/ugEw05za

`java.lang.RuntimeException: No OpenGL context found in the current thread.`

This crash is WITHOUT optifine and happens when Tinker's tables render Mek items.. but it isn't consistent.  In this particular crash we were trying to make the advanced tank.

**Comment by andyion** [comment]
I got this crash yesterday WITh optifine, removed it and it works now. Maybe you have another render-touching mod?

**Comment by utoc** [comment]
@andyion negative on another rendering mod. I did remove BetterFPS to test but still experienced the same crash.

**Comment by aidancbrady** [comment]
This is a known issue and there's honestly not much more I can do.  You can disable the fancy TiCo table render in their config.

**Comment by McJty** [comment]
That's a strange response. No other mod (that I know) currently has problems with rendering on the TiCo table. The problem is that you are doing GL calls in IBakedModel which is an absolute no-go and can cause problems with other mods too that need to render your blocks like this. The code is here:

https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/generators/client/render/item/BakedGeneratorItemModel.java#L63
