### ISSUE TITLE
(BUG) Digital Miner bounding block. 1.10.2

### ISSUE THREAD

**Issue by Dylanmc30** [aidancbrady/Mekanism#3766]
![2016-09-07_18 01 41](https://cloud.githubusercontent.com/assets/15089449/18321471/01221864-7526-11e6-99b5-4e80ec04e601.png)

Digital Miner is unusable for me. Cant pick it up because of this issue. 
Using latest version of mekanism 1.10.2

**Comment by RogerTsang** [comment]
Same to me, Once placed, it shifts and cannot be pick up with by mining pickaxe again. Showing Bounding Block.

**Comment by krysis2k16** [comment]
Still happening as of the 12/04/17, using version 9.2.2, MC 1.10.2 Direwolf20 pack.

Digital miner will rotate seemingly randomly and waila reports as bounding block. When trying to break the miner with a pickaxe, it shows the particle effects of a block breaking and makes the breaking block sound, but several times a second (guessing 20 times per second for ticks, but is just a guess with no evidence to support) and the block doesn't break.

Can be fixed by either moving far enough away to graphically unload (wording is probably incorrect as this fixed for me even in a chink the was kept loaded the chunk with the FTB Utilities) and move back, or logout and back in. Digital Miner also contains an anchor upgrade, if that makes any difference,

**Comment by ktole1999** [comment]
the miner is 3x3 multiblock even though miner doesnt fill a 3x3 area. rather than trying to break from a bounding block does it make a difference if breaking the actual miner say from rear?

**Comment by krysis2k16** [comment]
When the miner rotates, it's always 90 degrees (not sure if it's always the same rotation direction) but it seems to be only graphically that it does this.
So, any part of the miner that is still within the original 3x3 of where the miner was placed will be shown on waila as 'digital miner'. Any block that is either missing from the original location of the 3x3, or is where it shouldn't be due to rotating on a corner will show on waila as 'Bounding Block'.
If one of these bounding blocks is attempted to be broken to collect the miner, what happens in my last post happens. If you attempt to break the miner from a block that is part of the original 3x3 location, the miner can be broken and collected as though everything is perfectly fine.

The miner does not function any differently while it's rotated, and will still output to a chest or collect power through a port even after is has rotated. Opening the GUI for the miner also seems to temporarily reset the rotation of the miner back to normal, so maybe it is just a sync issue? Though this is happening in an solo single player world (not using a separate server, even locally).

Might be worth mentioning that the rotating issue is also happening to other machines in Mekanism, though with fewer problems as they are 1x1's and do not spin out of the dimensions that they were placed in, so for those it just looks like a graphical glich.

**Comment by krysis2k16** [comment]
Should also mention about the miner, once it's rotated and part of the 3x3 has moved, you still cannot walk there, as if it hasn't spun. You can walk through the part of the miner that's NOT within the original 3x3, as if  it isn't really there.

**Comment by aidancbrady** [comment]
Should be fixed as of the 1.11 version. Had to do with the inconsistent machine updates.
