### ISSUE TITLE
9.2.0.292 for 1.10.2 Pipes not providing power to AE2

### ISSUE THREAD

**Issue by KingZero** [aidancbrady/Mekanism#3911]
I have tried to give energy to AE2 with pipes and it does not seem to work I know it isn the creative engery block that I used cause EnderIO and no problem providing the power from the block to the cells

(I do have Telsa API)

![2016-10-21_15 17 35](https://cloud.githubusercontent.com/assets/13442728/19613516/d70c8534-97a1-11e6-91eb-76d4142b441f.png)
![2016-10-21_15 17 40](https://cloud.githubusercontent.com/assets/13442728/19613517/d70e141c-97a1-11e6-9ed8-d6f65c743550.png)

**Comment by chaos234** [comment]
Did you tried to switch the end of the pipe into input mode? SOmetimes I have hade some problem with the default mode so I use the Configurator to set the pipe either to extract or input mode.

I hope that this will fix your problem.

**Comment by KingZero** [comment]
? The configurator only changes the redstone state

**Comment by KingZero** [comment]
![2016-10-21_18 53 46](https://cloud.githubusercontent.com/assets/13442728/19616094/ca510a90-97bf-11e6-8f00-56f09f7917d1.png)

**Comment by VT-14** [comment]
Test the Mekanism Universal Cable into an Ender IO (or another Tesla mod's) Machine/capacitor bank.  I've been having issues with that, but haven't bothered tracking down if it is a Mekanism or Ender IO issue.

This makes it look like Mekanism.

From my general playing (not debugging) experience, the only problem are the Universal Cables and Chargepad.  An Energy Cube or Quantum Entangloporter directly works fine.  Mekanism cables do work fine with Mekanism machines.  If you can duplicate that, then this is almost certainly a Mekanism issue.

**Comment by KingZero** [comment]
I have tried multiple other mods and dont wish to have them in this private pack im making to play myself. EnderIO's energy conduits do work and Mekanism pipes all work fine with its own machines it is just the mekanism energy pipes to other mods (brought this up to the AE2 guys and they said the same cause they are trying to get all mods to work with it) but I can put the machines next to the block and it works fine

**Comment by chaos234** [comment]
This is a good work arround but if AE2 has any API for that then it should be possible to call it but this can maybe a bit complicated.

**Comment by VT-14** [comment]
Issue appears to be Mekanism Universal Cables.  Mek Energy Cubes and Quantum Entangloporters work fine, but the cables are having issues with multiple mods (EnderIO in my case).

**Comment by KingZero** [comment]
Make sure you guys have Tesla API installed cause that also is another reason it wont work but i already have that installed and it isnt working

**Comment by VT-14** [comment]
I'm pretty certain I installed Tesla.  I'm not on that computer atm though.

**Comment by KingZero** [comment]
OKay cause with EnderIO I have no issues at all the eneger conduits work amazing for me but i dont want to have all the other stuff the mod adds so I will probably just be putting the blocks next to each other untill there is a real fix

**Comment by KingZero** [comment]
@VT-14 You may also want to check to see if you have setup the pipes correctly (input and extract not in-to or anything else) for EnderIO if it isnt working

**Comment by VT-14** [comment]
Issue is Mek pipes not outputting to Ender IO machines.  I have tried adjusting the Mek settings.  Ender IO doesn't distinguish in/out on power for most machines (only capacitor banks).

Ender IO conduits are working fine, and cooperating with Mekanism Machines, Energy Cubes, etc.

As I said before, proper bug report later tonight.

**Comment by VT-14** [comment]
As promised, a full bug report.

Minecraft: 1.10.2
Forge: 12.18.2.2107
Mekanism: 1.10.2-9.2.0.292 (same for Mek Generators and Tools).
Tesla: 1.10.2-1.2.1.49
Ender IO: 1.10.2-3.0.1.120_beta
EnderCore: 1.10.2-0.4.1.56
RFTools: 1.10-5.55
McJtyLib: 1.10-2.2.0

Issue:
![2016-10-22_21 53 05](https://cloud.githubusercontent.com/assets/12564251/19623708/dc00f0dc-98a2-11e6-97db-72c7499b0f3a.png)

In that image, all power goes from the left to the right.  Green blocks indicate that is row is working as would expect (at the time, see case 7), red indicates a problem.  I configured each block to push/pull correctly.  Ender IO allowed me to see the RF/t in/out directly on its capacitors.  You can't see power transfer on most of the RFTools tests, and their creative power cell does not accept (void) energy, forcing me to use normal blocks.

Based on [This Power API Spreadsheet](https://docs.google.com/spreadsheets/d/1cay91dfNXrell8swa43yk2L6JVOlzSD0Qo7AOxz3nGk/edit#gid=534173858), Ender IO and RFTools can both use Tesla, Energy (Forge), and RF (CoFH).  Mekanism only shares Tesla and RF from that list.  AE2 only supports Tesla at the moment (but I don't have that to test in this pack).

Ender IO - Mekanism:
- 1: The Ender IO does not accept power from Mekanism Universal Cables.  The cable turned green, so it appeared to accept power from the Mekanism Energy Cube.
- 2, 3, 4, and 5: The Ender IO Capacitor Bank will push power into Mekanism Universal Cables, regardless of the setting on the cable.  4 (pulling from capacitor) and 5 (no special interaction with capacitor) worked as expected, but that is likely a coincidence considering the clearly incorrect behavior of 2 (no connection to capacitor) and 3 (Pushing into capacitor).
- 6 works as expected and is a direct connection.
- 7 initially appeared to work correctly, but in writing this, I noticed that the capacitor is receiving 50,499K RF/t  I believe the capacitor bank has a transfer limit of 500,000 RF/t, so that 50,499,000 RF/t transfer is likely WAY to high.  The Energy Cube is likely bypassing its transfer limit.

RFTools - Mekanism:
- 8 works as expected.
- 9 Energy does not leave the Power Cell.  The Power Cell should be pushing, and the Cable is pulling, but power isn't moving.
- 10 and 11 works as expected and are direction connections (again).  I can't think of a simple way to test for exceeding power limits of the Power Cell (if there are any).

Ender IO - RFTools:
- 12 Worked as expected.  Only shows 0 RF/t transfer due to the Power Cell being full of energy.
- 13 Worked as expected.


Logs:
Debug Crash: https://gist.github.com/VT-14/acb1637e19727f7fa862a32086740f1a
FML Log: https://gist.github.com/VT-14/e7f282fa59eb60e4a3412906c0b95974
