### ISSUE TITLE
[Suggestion] Split pipes into its own module

### ISSUE THREAD

**Issue by ToadsworthLP** [aidancbrady/Mekanism#3921]
If the mechanical and logistical transporters, together with the logistical sorter were splitted into a seperate module like you did with the tools, we finally had an awesome-looking and nicely-working standalone piping system in Minecraft 1.10.2! Even though it wouldn't be fully standalone, I could modify it myself to make it independent, but splitting the mod even further would also allow to have Mekanism's machines, but without the pipes, whyever one would want that. I just like mods that are split into modules, OK? And I'm sure that I am not the only one.

**Comment by rdunham3** [comment]
Are there other mods which provide the gas pipe and thermal pipe functionality? I think splitting off the pipes would give people an easy way of breaking their Mekanism without realizing how or why they did so.  Easy enough to choose not to use Mekanism pipes in favor of another mod's should you have that other mod installed.

**Comment by VT-14** [comment]
The recipes would have to be altered to be standalone, and using vanilla materials for Mek pipes would be unreasonably cheap.  Mekanism would probably end up being a dependency anyway, so you would only be making another download and causing confusion.  Plus, Mekanism would become practically unplayable if you don't have all 5 types of pipes (especially Gas and Thermal, which are quite rare in other mods).

Mek Generators and Mek Tools are both separate add-ons partially because Mekanism doesn't really need them.  If you find Paxels or Wind Generators overpowered compared to the other mods in your pack, then you can choose to not install those mods and play Mekanism reasonably fine.

**Comment by aidancbrady** [comment]
Transmitters are such an essential part of Mekanism that it doesn't make sense to split them from the core.
