### ISSUE TITLE
Energy Cube Hermitpack 1.2 Multiplayer

### ISSUE THREAD

**Issue by Reko420** [aidancbrady/Mekanism#3922]
when i place any energy cube into a crafting table it causes client side crash.

**Comment by VT-14** [comment]
Notes for bug reporting:
0) Before reporting an issue, use the search function to see if it has been reported before.

1) Please post a (full) crashlog when reporting a crash.  Please use Pastebin, a Github Gist (link at the top of this page), or another known text dumping site.

2) Have you made any changes to the pack (mod additions/removals, config changes, etc)?  It's usually requested to include the Minecraft Version, Forge Version, and the versions of any mods related to the issue in the report itself.  Crash Logs include full mod lists, so no need to list every mod in the pack.

3) Most modpacks request that you report bugs to them first.

4) Be as detailed as possible.  You want anyone to be able to follow your directions and recreate your issue.  Which tier of Energy Cube was it, did it have any power in it, was it a Vanilla Crafting Table or a modded one, etc.


Back to your issue:  I'll take a random shot in the dark.
From what I know of the Hermitpack and issues I have seen on here in the past (since before the Hermitpack came out), you are very likely using a Tinkers' Construct Crafting Station, might have added Optifine*, and the config has been left on to have items render on top of the Crafting Station.

You might be able to fix this by disabling the Crafting Station item render in the Tinkers' Construct config.  You may also need to remove or update Optifine if you installed it.

*Most mods do not support Optifine.  They usually have the attitude of 'if it works, great. If not, we aren't going out of our way to add compatibility for a closed source mod that updates quickly and is a pain to develop for.'

I think Optifine recently updated and isn't crashing as much.  If you are using a version of Optifine that is more than about 2 weeks old, then try updating.
