### ISSUE TITLE
Universal Cables unable to extract from Ender IO Machines

### ISSUE THREAD

**Issue by xandayn** [aidancbrady/Mekanism#3936]
I couldn't say for certain if this is an Ender IO issue or a Mekanism issue, but considering it appears to be an issue with the cables (Ender IO machines are able to output to Mekanism energy storage units, tested with an Energized Induction Matrix), I think it's safe to assume it's a Mekanism issue. 

I've tested with Ender IO version 1.10.2-3.0.1.125_beta (the newest version at the time of writing), Mekanism version 9.2.0.292 and Minecraft Forge version 1.2.18.2.2118 for Minecraft 1.10.2.

I seemed to have missed a previous issue #3732 mentioning they don't accept non-Tesla sources, is this still the case, or is this an actual issue?

**Comment by accessdenied0** [comment]
Universal Cables or Tubes/Cables from Mekanism have strange behavior with Ender IO in general. You can't push or pull and sometimes the energy (at least Banks) doesn't work, too.

I can confirm this too and I'm sure this is a compat issue. But it doesn't surprise me because most of the mods have some compat issues because of the "unfinished" modding state of 1.10.2. Even Forge has 2 Recommend releases yet, 1.10.2 is far from finished yet. 
Just give it all time.

access_denied

**Comment by VT-14** [comment]
#3911
