### ISSUE TITLE
Electrolytic Separator

### ISSUE THREAD

**Issue by klaujesi** [aidancbrady/Mekanism#3982]
First at all: Thanks, awesome mod.

I just installed on 1.10.2. Everything look fine until I've try to make the Electrolytic Separaton on a Tinker's: Crafting Station, and then game crashed. Now it crashed over and over again. I can't load my world :(

Hope crash report be usefull. Thanks in advance

[crash-2016-11-16_22.02.34-client.txt](https://github.com/aidancbrady/Mekanism/files/596281/crash-2016-11-16_22.02.34-client.txt)

**Comment by ktole1999** [comment]
sounds like you will need to use a world editor to delete the bad block.

**Comment by rdunham3** [comment]
I noticed a few odd behaviors in the 1.10.2 Tinker's with regard to other mods.  I think they did a total rewrite and introduced some compatibility issues.

You could try starting up that world with the Tinker's mod disabled.  That will remove the Tinker's blocks and items including the bad block while keeping your other base items.  Slightly less than a complete setback.  Hope that helps!

**Comment by VT-14** [comment]
This is a 3 way crash that has been reported several times.  Please use the search bar before posting an issue to try to prevent duplicate reports.

1) Optifine is not supported by 90+% of mods.  You are just asking for rendering crashes.
2) Tinkers' Construct renders items on top of its tables.  You can turn this off in the config for TC.
3) Mekanism has weird rendering which is causing this bug.  TC can't fix it on their end, and Mek has yet to figure out what the problem is, and I don't think Mek has updated in a while.

**Comment by klaujesi** [comment]
Thanks a lot guys.
Good newss . Removing Optifine, solve the problem. But still I can't get my Electrolytic Separator :(

![rotary](https://cloud.githubusercontent.com/assets/6095955/20456060/be7c77d0-ae4a-11e6-8763-e072cad44d85.jpg)


The recipe for Electroytic Separator .. gives me: Rotary Condensentrator. I'm doing something wrong?

**Comment by VT-14** [comment]
Mekanism's JEI integration is messed up.  There are multiple machines visible when you look up the recipe.  You have to find the actual Electrolytic Separator recipe in that list.

#3925 should fix it once the next version of Mekanism is released.
