### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by HyperBlueCore** [aidancbrady/Mekanism#4000]
I was playing on my server with my modpack and I started crashing in the middle of the game with this issue but I don't get it in singleplayer
http://pastebin.com/YJJf6Z27

**Comment by HyperBlueCore** [comment]
and dont tell me to remove optifine  since it handles all of the lag of modpacks that cause crashing ;FIX IT
and upgrade the deploader cus I think that's what is causing it

**Comment by ktole1999** [comment]
how do you know its not the crafting station causing it. You posted in another issue for player to change mipmapping and remove optifine due to render issues. does that not also apply to you?

**Comment by HyperBlueCore** [comment]
First i didnt advice him i explained for him how to chnge the mipmapping if he might get pucky with it and i never said it was the crafting station insaid i get the issue with the smeltery controller caused by mekansim cus i already asked tic

**Comment by HyperBlueCore** [comment]
Lucky not pucky

**Comment by ktole1999** [comment]
i referenced the crafting station because there is a known render issue that can be resolved by making a change in config to not render on top of the station.

**Comment by jburrows82** [comment]
Optifine doesn't fix lag, it changes how Minecraft does rendering along with other hacky things which improve FPS. While it may seem like it's a true savior when it comes to modded Minecraft, it is not. Mods are written to work with Minecraft, not Optifine. It breaks a lot of mods because they're expecting things to work normally how Minecraft does them, not how Optifine does things. If a mod is expecting result A, but instead gets result B, well you start getting unexpected results like bugs and crashes.

If you can't reproduce the EXACT same crash WITHOUT Optifine then DON'T REPORT the issue.

**Comment by HyperBlueCore** [comment]
Still same crash and what is left in mc microsoft broke the mods and eula soo they are soo laggy which causes immediate crash so if this mod mod is cant be compatible with one of the most important (mod) then it will fail

**Comment by HyperBlueCore** [comment]
And every single mod until I know this day is trying its best to work with optifine plus why should we decrase the mipmap isnt it from MINECRAFT and we want it thats why its there and now do you have any dumb execuse (sorry im mad right now i have too much stress

**Comment by VT-14** [comment]
...And 98%+ of the mods I've seen have said Optifine is not supported.  It's on the same blacklist by the vast majority of the Forge mod community as Bukkit, Sponge, and Cauldron.

1) Optifine is not built on Forge (so you can use it directly with Vanilla Minecraft), which introduces many of the issues that it causes.
2) Optifine is closed source.  Mod authors can't look at the code and figure out what the heck changed.
3) Optifine does not provide a dev version for modders to work with.  Modders basically have to hack into Optifine in order to try to support it.

Point 1 means that it causes problems constantly.  Points 2 and 3 means that it is practically impossible to develop for while working on your own mod.

Most mods take the "if it works, great.  If not, well, it's not supported." approach.  Many will also say "report to Optifine because that broke it."  I've also seen the occasional minor tweak in a mod when someone explains precisely what change needs to be done or if a pull request is filed.  Otherwise, it's just too massive a pain in the ass to work around.


"...if this mod mod is cant be compatible with one of the most important (mod) then it will fail."  You would think, but Optifine is still around because it does a good job on Vanilla Minecraft, and doesn't change any (major) gameplay so vanilla players are willing to download it.

**Comment by HyperBlueCore** [comment]
but optifine is not the cuase because I said I tried it and MODS don't support optifine but they become compatible with optifine

**Comment by ktole1999** [comment]
does it work with only mekanism installed?

**Comment by VT-14** [comment]
If it still happens without Optifine, then you are right and Optifine is not the issue.  If it only happens with Optifine installed, then it's because Optifine f***s up rendering to try to improve vanilla minecraft.  If it only crashes when Optifine is there, then report it to Optifine because it's their problem.  Their dev will be able to find the problem much quicker and either be able to fix it in Optifine, or point out to Aiden how to fix it in Mekanism (or file a pull request).  https://github.com/sp614x/optifine/issues

... also, step 1 of troubleshooting to report a bug is to make sure you are using the most recent versions of all of the mods in question.  Your Optifine is out of date (-_-), and I haven't seen this crash since its last updated because Optifine is working to become more compatible with mods (not the other way around).

**Comment by HyperBlueCore** [comment]
I made sure its mechanism and no other mod such as optifine is  making mekanisim do this so IT IS surely the coding of mekanism

**Comment by VT-14** [comment]
If it occurs without Optifine, then post the crash log where Optifine is not installed.

**Comment by VT-14** [comment]
"...caused by mekansim cus i already asked tic"

Well, here is your TiC report: https://github.com/SlimeKnights/TinkersConstruct/issues/2588
Based on the Labels Bonii put on your issue, he agrees that it is an Optifine issue.  Following the 'referenced in' link, I can see that KnightMiner also told you to try reproducing the issue without Optifine.

I'm curious how you so strongly believe that Optifine is not the issue when everyone you have talked to has said to try it without Optifine?

**Comment by HyperBlueCore** [comment]
never mind it wasing cus I was running optifine it was because the server was running it and I forgot to remove it
