### ISSUE TITLE
Crash with Mek's Mcmultipart + Refined Storage?

### ISSUE THREAD

**Issue by DuskFalls** [aidancbrady/Mekanism#4011]
[crash-2016-11-24_05.20.40-server.txt](https://github.com/aidancbrady/Mekanism/files/610525/crash-2016-11-24_05.20.40-server.txt)

I don't know how to remove the offending pipes, as it crashes the moment the world loads

**Comment by jburrows82** [comment]
Development version of Mekanism. Which branch of source is it built from?

**Comment by DuskFalls** [comment]
The one that someone posted around here that fixed the pipes breaking crash, it happened on the most recent standard release too so I decided to test it on that one too

**Comment by thommy101** [comment]
Can you try the newly compiled version found at issue 3989 (which also contains the pipe breaking fix)? I guess it might solve this one also.

**Comment by DuskFalls** [comment]
Thats the one i used

Initially i just used the release that comes with All the Mods, but after it crashed, i came here looking for an update and found and used that one, it has the same problem

**Comment by thommy101** [comment]
I'm trying to replicate the issue and looking at your referenced issue at refined storage it happens when placing a pipe next to an refined storage exporter? What kind of pipe and how is it placed next to the storage exporter?

Also I'm very certain this is an Mekanism issue, not an mcmultipart/refined storage issue.

**Comment by HyperBlueCore** [comment]
remove code chiken core and any mod related to it and try again

**Comment by aidancbrady** [comment]
Fixed in dev.
