### ISSUE TITLE
about digital miner need help

### ISSUE THREAD

**Issue by Javacym** [aidancbrady/Mekanism#4020]
1.i use mc1.7.10, how to make Digital Miner chunk  auto load.
2.about Quantum Entangloporter , i use Quantum Entangloporter to send energy to miner, and send items from miner.but why Quantum Entangloporter work slowly,the send item speed is most slowly then miner. how to make Quantum Entangloporter faster

**Comment by HyperBlueCore** [comment]
1 use a chunk loader from chickenchunks
2 I guess use speed upgrades on it

**Comment by Javacym** [comment]
@HyperBlueCore 
1.I try use chickenchunks
2.I not found out upgrade for Quantum Entangloporter

**Comment by ktole1999** [comment]
chickenchunks has been known to cause issues. i would recommend anchors from railcraft

**Comment by Malkierian** [comment]
Oh, he's on 1.7.10...  I was about to say that I use tons of CC loaders with no issues, but I'm on 1.10.2, so that explains that.

As far as making the entangloporter faster, it is only as slow as the slowest/least upgraded pipe/tube/cable/transporter you have attached to it.  It does not have its own behavior or max rate, and therefore you can't make it go faster.

**Comment by Javacym** [comment]
two Quantum Entangloporters send items to one Quantum Entangloporter.it work slow. item may get back .

**Comment by Malkierian** [comment]
I have four QEs sending to one (one for each miner), and it doesn't lose or return any items, at least.  But like I said, I'm on 1.10.2.  Also, I tend to use auto-eject a lot, too, and that could explain the difference in experiences.
