### ISSUE TITLE
Power transfer issue with Universal Cables

### ISSUE THREAD

**Issue by iamomicron** [aidancbrady/Mekanism#4027]
Some tile entities that use power do not accept it while connected to Universal Cables, however they work fine connected to an Energy Cube. For example:

![Example 1](http://dl.aimes.eu/2016-11-29_20-50-37.png)

As seen here, the Capacitor Bank does not accept power when connected via cables, but connected directly to the Cube. The same goes for the Controller from Refined Storage. Here's a list of other such examples.

* EnderIO - Cappacitor Bank
* RFTools - Advancesd Powercell
* Forestry - Squeezer

However, oddly, power transfer with cables does work with some blocks, such as:

* IC2 - MFSU
* Immersive Enginering - Capacitor
* Draconic Evolution - Energy Infuser
* Extra Utilities 2 - Wireless RF Battery
* DeepResonanse - Smelter

Original source: https://github.com/DNSTechpack/DNS10-MC1.10.2/issues/27

Tested myself and this is indeed a notable issue.

**Comment by Malkierian** [comment]
Want to confirm this issue, but add that with other blocks, like Ender IO's Sag Mill, it doesn't even accept power directly from the cube with no intervening cables.  Haven't tested any other blocks.

**Comment by Malkierian** [comment]
As an addendum, even for the blocks that don't pull energy straight from the energy cubes, the EnderIO energy conduits are able to interact with it, and then can power everything else that runs on RF (I think.  I haven't tested EVERY RF machine).

**Comment by VT-14** [comment]
#3911

**Comment by MainFreak** [comment]
When you give a bug report like that you should add info about what version you used. If this is an issue with the most recent version this bug is important to fix. If you use an outdated version this was already fixed.

**Comment by iamomicron** [comment]
It is the most recent version, as can be found in the log.

**Comment by Malkierian** [comment]
Also have the latest version, 295.

**Comment by PJB3005** [comment]
Probably related: OpenComputers computer cases connect but don't draw power, while the power converter does function fine.

**Comment by adveres** [comment]
+1

Playing FTB Infinity Lite and tried to use `Advanced Universal Cable`s to pull energy out of an RFTools Powercell to put power into a Gendustry Industrial Hive.  

1. I know the Powercell/Hive were working because when placed next to each other they're fine.
2. I also know that the cables can input energy *into* an RFTools Powercell because that works elsewhere in the world.

The problem seems to be specifically piping energy into the `Industrial Hive` via Mekanism's universal cables. I attempted to use the `Configurator` to properly configure pulling from the Powercell and pushing into the `Industrial Hive`, but it didn't make a difference.  I crafted some Energy Conduits from EnderIO just to test, and those worked with the Powercell/Hive.

* FTB Infinity Lite  v1.6.0
* Minecraft 1.10.2 (modded) forge-12.18.3.2221
* Mekanism-1.10.2-9.2.1.295
