### ISSUE TITLE
Oredictionificator does not work properly

### ISSUE THREAD

**Issue by Xiaminou** [aidancbrady/Mekanism#4052]
![2016-12-07_19 01 10](https://cloud.githubusercontent.com/assets/8670392/20980129/9a1c72dc-bcaf-11e6-8417-5eb7d198aa9f.png)

It does not convert between aluminum equivalents even though it recognizes the ore dictionary.
It does not recognize the blockSteel ore dictionary at all.

These are just a couple of example I'm sure if I played with it some more I'd find more stuff that's not working.

Minecraft: 1.10.2
Forge: 2183
Mods: [list.txt](https://github.com/aidancbrady/Mekanism/files/636909/list.txt)

**Comment by Malkierian** [comment]
I think it's because it has two dictionary entries, and the first one doesn't match the rest of them.  I've seen that in several instances, not just in Mekanism, where the dictionary entries listed first didn't match, so a process of some kind was halted, even though they still shared A dictionary entry.

**Comment by L0laapk3** [comment]
It doesnt seem to work on many of the industrialcraft 2/techreborn stuff, like plateCarbon or machineBlockAdvanced (even tho these only have 1 oredict tag)

**Comment by JaSpr** [comment]
As I understand it, the oredictionificator does not support *any* blocks, since that would allow converting things that were never intended to be converted.  For example, converting between colors of stained glass and glass without needing any dye.

**Comment by L0laapk3** [comment]
Aha! Sorry, my bad.-------- Oorspronkelijk bericht --------Onderwerp: Re: [aidancbrady/Mekanism] Oredictionificator does not work properly (#4052)Van: Jason Spradlin Aan: aidancbrady/Mekanism Cc: L0laapk3 ,Comment As I understand it, the oredictionificator does not support any blocks, since that would allow converting things that were never intended to be converted.  For example, converting between colors of stained glass and glass without needing any dye.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aidancbrady/Mekanism","title":"aidancbrady/Mekanism","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aidancbrady/Mekanism"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JaSpr in #4052: As I understand it, the oredictionificator does not support *any* blocks, since that would allow converting things that were never intended to be converted.  For example, converting between colors of stained glass and glass without needing any dye."}],"action":{"name":"View Issue","url":"https://github.com/aidancbrady/Mekanism/issues/4052#issuecomment-289159289"}}}
