### ISSUE TITLE
divide Pressurized Tube??

### ISSUE THREAD

**Issue by Javacym** [aidancbrady/Mekanism#4053]
for eg. i have two Pressurized Tube . . but the two put together(on purpose), how to make one is transport Hydrogen .the other one is Oxygen.and the two tube can not connect together?

**Comment by Malkierian** [comment]
It doesn't exist right now.  Same goes for any of the other ones that you can't change the color of.  It would be solved if that functionality was added to the pipe and tube, and I'm really surprised it hasn't been added yet (especially since the only mod that adds a facade in 1.10.2, that I can find, only works on its own cables).

**Comment by MrPatience** [comment]
I must be foolish , but can't you use the configurator to set the connections off between the two cables ? I think I did that one time (now I make them fluids , move them with refined storage , then make them gas again before sending them to their needed machines)
Btw  I think you can do covers with chisel and bits  (like with refined storage)
Also this mod can serve your needs : https://minecraft.curseforge.com/projects/simple-covers

**Comment by Malkierian** [comment]
Yeah, no, you can set the connections however you want, but the flow ignores those settings for the ones right next to each other.

Yes, Simple Covers works perfectly between mech pipes.
