### ISSUE TITLE
1.10.2(latest one) Ic2 integration

### ISSUE THREAD

**Issue by bigpodgurc** [aidancbrady/Mekanism#4061]
So i was using direwolf20 1.10.2 pack and added your mod in for easy change between eu and rf(and for induction matrix) and i have array of ic2(eu) solars connected to mfsu when i connected your universal cable thingys and added energy cube nothing came out of mfsu but your universal cable did render the connection. And your cable does say it can convert

My opinion (probably not correct but wanna just see what you think about it): API change on IC2 side because even some other mod(immersive engineering) doesnt work (could be not implemented in .immersive engineering). This was just my idea that might save you some trouble or make you more work and please if you can at least tell me if i was correct

**Comment by bookerthegeek** [comment]
Immersive Engineering no longer supports EU.

**Comment by bigpodgurc** [comment]
learned of that couple of hours later after i wrote this

**Comment by VT-14** [comment]
Personally, I would like to see Mekanism drop EU support for various reasons.

1) RF (and J) is a very different power system than EU.  EU has voltage tiers, energy packets, transformers, and significant consequences when you mess something up.  RF has none of those.

2) Mekanism is an RF-like mod.  Yes, it uses Joules, but to the player it functions exactly like RF with only a factor difference.  Whenever it transfers EU, it turns it into RF (well, J) and treats it as such; completely removing EU all together and turning IC2 into an RF mod (which they clearly do not want).  Note: I do not have any problems with generic power converter mods.  Those are only made to convert power and have no other features; plus they tend to respect EU's nuances.  They can also show the IC2 devs just how many people are playing IC2 using RF (rather than 'how many people are playing Mekanism') and could cause some sway in the future.

3) The 1 EU = 4 RF power conversion is WAY out of date.  RF has gone through years of power creep and its numbers have been inflated to stupidity.  99% of the time, the conversion is RF -> EU, which shows that it clearly isn't balanced at all.  Unfortunately, there isn't any good number.  Looking at early game generators from various mods, it make sense to keep the 1-4 conversion.  Look at mid to late game generators, and we are comparing the IC2 reactor that generates ~2,000 RF/t to things like Big (Extreme) Reactors, the Mekanism Reactor, or even just Ethylene or ~11 Wind Generators.

4) Power converters exist because people don't like EU.  However, these same mods are giving IC2 more players and downloads and thus indirectly supporting IC2 and their decision to stick with EU.  In my opinion, if you don't like dealing with EU, then you don't like IC2 and should probably not play it.

**Comment by bigpodgurc** [comment]
you make good reasons but in my case its that thing that i have to many cables and only that and also i do like IC2 machines and powergen but i that i cannot use it with most of my base. but mostly it is because i cant transport it like with dimensional transciever(from enderIO) and that one new block from mekanism

**Comment by bookerthegeek** [comment]
> The 1 EU = 4 RF power conversion is WAY out of date

Personally, while building my pack, I found that a good ratio considering the end game mechanics of popular mods was over 1RF = 1000EU

I hate to say it but I agree with with @VT-14 (hate it because lack of inter-mod compatibility sucks)
