### ISSUE TITLE
Game crashing as soon as my world is loaded

### ISSUE THREAD

**Issue by GoldenAurora** [aidancbrady/Mekanism#4065]
So I was crashing one of the chemical machines and I got the following crash, every single time, the same crash message pretty much.

[crash-2016-12-13_20.39.02-client.txt](https://github.com/aidancbrady/Mekanism/files/650616/crash-2016-12-13_20.39.02-client.txt)

**Comment by GoldenAurora** [comment]
Figured it out! It was with Tinker's Constructs crafting benches and displaying the items left in them, Mekinism doesn't seem to work well with that.

**Comment by VT-14** [comment]
Without bothering to look at the crash log, I'm willing to bet you are using Optifine.  Known issue that has been reported several times already.

**Comment by PJB3005** [comment]
I did bother to look at he did indeed.
```
OptiFine Version: OptiFine_1.10.2_HD_U_D4
```

**Comment by jburrows82** [comment]
Forge should just crash the instance if Optifine is detected and force the user to acknowledge a config setting like the EULA, that any crashes experienced while using unstable and highly unrecommended modifications such as Optifine are to be expected and NOT be randomly reported somewhere on the internet.

**Comment by VT-14** [comment]
@jburrows82 I both like and don't like that idea.

I like it because Optifine, Sponge, Cauldron, etc. are so often incomparable with Forge mods and end up being a complete waste of time for mod authors and frustrating for their overly attached users.

I don't like it because it will turn some people away from modded if it's implemented like that.  Some people won't have any idea where to find the file that would need to be changed and would either give up, or open bug reports everywhere saying that the game immediately crashes and waste everyone's time anyway.

I would personally put an acknowledgment screen right before the title screen when Optifine is detected on a client.  That way the people who choose to use it only get a slightly annoying extra button to press on startup, and see it every time they start modded Minecraft.  I would also add near the top of the crash log that one of those incompatible plug-ins is detected.

EULA-like acknowledgement would be great for servers though.  "No, you can not start a modded server with this plug-in until you acknowledge that it will probably cause problems and removing it should be your first step in troubleshooting."

**Comment by GoldenAurora** [comment]
I appreciate the feedback and didn't know about the opticienne bug, but it would seem you have misread the issue and not seen that I had fixed it before I had gotten any responses, it was not the game but the world itself that was having problems, I had to use MCedit to remove the work station to Tinkers construct that has the items in it, since then I have encountered no problems, even with optifine, but I appreciate the effort

**Comment by VT-14** [comment]
I see that I need to explain the crash to you.

Tinkers tried to render a Mekanism thingy on top of the table.  Optifine screwed up that rendering process, which is why the game crashed.

Yes, this is a 3 way crash.  Mek has some weird rendering at the moment, TiC tries to render something not expecting Optifine to be there, and Optifine screwed it up and caused TiC to crash and throw a rendering error.  If you remove Optifine, then the rendering isn't as screwed up and the game doesn't crash.  Thus, It's an Optifine issue.

**Comment by GoldenAurora** [comment]
Thank you for explaining this, I did not fully understand and apologise
