### ISSUE TITLE
[1.10.2][9.2.1.295] Universal cable not connecting to Applied Energistics Energy Acceptor.

### ISSUE THREAD

**Issue by addrever** [aidancbrady/Mekanism#4093]
Not sure why this isn't working as it was in previous Minecraft versions.

Versions:
Minecraft 1.10.2
Mekanism ( All ): 9.2.1.295
AE: rv4-alpha-9
Forge: 12.8.3.2185

![2016-12-27_01 46 10](https://cloud.githubusercontent.com/assets/190461/21492954/a62ba652-cbd6-11e6-882e-fb5f83e5f999.png)

**Comment by halvors** [comment]
This is due to lack of tesla or forge energy support in AE2. AE2 needs to implement one of these.

A quick fix to make these interface is to add IndustrialCraft2. Which will make this work as expected.

This is due to AE2 and Mekanism both support IC2 energy.

This is an AE2 issue and is known by the developers. Buth AE2 is in alpha. So we need to give it some time.

**Comment by addrever** [comment]
Thank you for the response.  I will check again on the AE2 issues site for an update.

Happy New Year!
