### ISSUE TITLE
[Bug] Universal cables instantly empties full Draconic Evolution energy multiblock storage

### ISSUE THREAD

**Issue by RedSnt** [aidancbrady/Mekanism#4105]
Mekanism version 9.1.0, Draconic Evolution 1.0.2h. MC version 1.7.10.

Title says it all. When I place an energy cube as the "buffer" or replacement for cable connection it works fine, but when connected directly with cable it just instantly empties the energy storage.

**Comment by nanakisan** [comment]
I will chalk this up as a relevant issue on my end and add my input here as well. I am presently playing Project Ozone 2. While playing I noticed an inconsistent behavior between the cables and ExU generators. For some reason the generator's will begin to infinitely produce RF and exceed their internal buffers. This only happens with Universal Cables attached.

I have added an album showing the issue.
1st image is the normal function without issue by using IE cable's. But once I switch to the Universal Advanced Cable the problem occurs.

https://imgur.com/a/pWXdZ

**Comment by ThatGamerBlue** [comment]
Sorry but 1.7.10 isn't supported.

**Comment by nanakisan** [comment]
Sorry to say to sound a tad rude on this matter. But these two issues are directly affecting two different mods. This is no longer an issue regarding mod support or a tiny little bug. This mod is breaking two different mods through the same problems with the Universal Cables. This at least warrants an investigation in the relevant code. Because if it is present here it might still occur in the later versions.

I can understand having a stance on moving forward. But remember, even forge supported older versions if a bug was found that broke a lot of things.
