### ISSUE TITLE
Nether Ores Support

### ISSUE THREAD

**Issue by roboderpy** [aidancbrady/Mekanism#4130]
Next ores are *Nether Variation* of usual ores:
```
oreNetherCoal
oreNetherIron
oreNetherGold
oreNetherDiamond
oreNetherRedstone
oreNetherLapis
oreNetherDiamond
oreNetherEmerald
```
They should be acceptable by ore processing machinery and give twice as usual processed output.
E.g. Nether iron Ore -> 4 Iron dust or 8 iron shards
Mod that adds Nether Ores: https://mods.curse.com/mc-mods/minecraft/241576-nether-core
*Other mods (example: EnderIO) already supports that ores*

**Comment by ThatGamerBlue** [comment]
Why are you here advertising your mod? Get out.

**Comment by roboderpy** [comment]
Not my mod. I don't even making mods @ThatGamerBlue
Before 1.10.2 there was another mod: Nether Ores by Team CoFH

**Comment by jburrows82** [comment]
Supporting every novelty ore out there isn't feasible. There are solutions out there for adding support, such as Unidict or Minetweaker for example. It's up to the modpack makers IMO to add compatibility if they want it. If every mod author hardcodes support for 200 different ores then that author has to constantly update support and balance around said ores. That isn't fair to mod authors, and that's why there are tools for modpack makers and players alike to tweak their instances as they see fit.

**Comment by roboderpy** [comment]
In balancing, Nether ores was never changed, they always give twice output. EnderIO, IC2, ExtraUtils and many other mods supports nether ores, why can't Mekanism?

**Comment by aidancbrady** [comment]
I don't understand why they can't use the default ore dictionary terms for their resources, the addition of 'Nether' seems a bit silly. I'm normally fine with adding extra integration but this doesn't seem logical.

**Comment by roboderpy** [comment]
@aidancbrady they add `nether` to ore dictionary prefix because nether ores **gives twice as usual output**
```
oreIron -> 2 iron dusts
oreNetherIron -> 4 iron dusts
```
