### ISSUE TITLE
MCVersion annotation problem in v1.10.2

### ISSUE THREAD

**Issue by Herekar** [aidancbrady/Mekanism#4178]
This morning i tried loading two different mod packs with Mekanism (Skyexchange and a private pack of my own) and both times got this line in the game output section of the launcher and loading just stopped

[06:10:57] [main/WARN] [FML/]: The coremod mekanism.common.launch.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft

**Comment by TehStoneMan** [comment]
No you have an NVidia video card? Did you recently update the drivers?
If you did, the new drivers broke something. You may need to re-install the older drivers.

**Comment by thommy101** [comment]
The warning has nothing to do with the crashes, it's just a warning that some annotations are missing. That warning is already fixed in one of the development branches (1.10 branch).

The reason behind the crash could be, as @TehStoneMan said, be an up-to date NVidia driver.
https://www.reddit.com/r/feedthebeast/comments/5pydv9/dont_install_nvidia_gpu_driver_version_37849_it/

**Comment by Herekar** [comment]
I followed up on the Nvidia driver issue and that solved the problem thanks.
