### ISSUE TITLE
Cardboard box and Oak Door

### ISSUE THREAD

**Issue by ktole1999** [aidancbrady/Mekanism#4187]
when placing a cardboard box on a door it captured as intended. when box was broken and retrieved to inventory this crash occurred when i moused over the cardboard box. as long as you dont mouse over the box while in inventory everything is fine. Happens in SSP and SMP.

Mekanism-1.10.2-9.2.1.295
forge-1.10.2-12.18.3.2202

http://pastebin.com/dcvDZhqP

**Comment by jburrows82** [comment]
Can you reproduce this without Optifine? I can't with my local version. Also, if you can't reproduce this without Optifine.. Try updating Optifine. You're using a known buggy version

**Comment by ktole1999** [comment]
will let you know results when i get home. thanks.

**Comment by thommy101** [comment]
I think I saw this report earlier. And if I'm right I could reproduce it succesfully.
There is a bug with getItemTooltip which adds null to a list which won't accept null or something.

**Comment by ktole1999** [comment]
tested without optifine.
http://pastebin.com/5g3bapYh

**Comment by oliver276** [comment]
I've had the same problem over here, #4094

Can confirm it's just client-side rendering presumably from the getItemTooltip()

**Comment by thommy101** [comment]
The problem is probably on the following line:
https://github.com/aidancbrady/Mekanism/blob/1.10/src/main/java/mekanism/common/item/ItemBlockCardboardBox.java#L55

Somehow the blocks is null or it doesn't have a registered item.
The constructor of ItemStack accepts blocks and items. If it's an block it uses Item.getItemFromBlock(blockIn).

When trying to get the name of the itemstack, that item should not be null. Somehow it is. My guess is that doors do not have a appropriate item registered to the block.
Another thing: If you place a door out of a cardboardbox, it's only the bottom half, not the whole door.

**Comment by thiakil** [comment]
Doors have 2 block instances (top and bottom half), and one of them will return null from the getItemFromBlock. (Can't check which right now)
