### ISSUE TITLE
[Suggestion] Config Option to Disable Mekanism Steel

### ISSUE THREAD

**Issue by MastaC729** [aidancbrady/Mekanism#4235]
In our modpack we are using more difficult means to make Steel. However, since ModTweaker refuses to support Mekanism we cannot easily disable the Mekanism steel recipes. Would you be willing to add a config option to disable the Metallurgic Infuser recipe of making steel?

**Comment by Just-some-cannibal** [comment]
You could make a fork of this and compile it without the steel recipe

**Comment by aidancbrady** [comment]
I'd rather not, then it would make sense to add support to remove any recipe. IMC does enough for the time being.

**Comment by BrianEdmonds** [comment]
> I'd rather not, then it would make sense to add support to remove any
> recipe. IMC does enough for the time being.

Steel seems like a bit of a special case, since its difficulty is wildly
different between the various mods. It varies from pretty trivial in
EnderIO, to a bit more involved in Mekanism, to laborious (yet
fundemental) in Immersive Engineering. I could see a pack wanting some
parts of Mek (like the jetpack), but aiming for a general IE vibe,
wanting to make people use the IE steel production.

**Comment by thiakil** [comment]
@BrianEdmonds Can't you remove Mek steel from the OreDict with Tweaker?

**Comment by BrianEdmonds** [comment]
I've not played with it myself, I was just observing that the complexity of producing steel is something that varies quite a bit between mods, so would not be unreasonable to configure with a simple option.
