### ISSUE TITLE
[1.10] Universal cables don't expose acceptor methods like they should (RF and EU)

### ISSUE THREAD

**Issue by Paul17041993** [aidancbrady/Mekanism#4238]
Universal cables push to destination devices just fine with RF and EU, however they don't allow either to be pushed into the cables. This can be fixed for most sources by setting the cable to pull, however this is not the case for other energy transport methods such as IE's wire connectors.
( https://github.com/BluSunrize/ImmersiveEngineering/issues/1912 )

I'm aware of the tesla API rewrite awaiting to be pulled in, but made this a new issue for clarity.

**Comment by VT-14** [comment]
The Tesla rewrite won't help in this case.  IE only uses Immersive Flux (it's internal power system), Forge Energy, and the legacy CoFH RF APIs.  Mekanism only shares the legacy CoFH RF API.

That said, the released build is months old and a bit behind what is here on GitHub, so it might be a good idea to make sure this hasn't already been fixed.

Immersive Engineering dropped IC2's EU support in 1.8+ due to it being abused in 1.7.10 to send PowerCreeped RF into relatively balanced IC2; and Blu hated seeing his mod treated like a simple power converter.

**Comment by aidancbrady** [comment]
Forge Energy support is planned, that should fix this issue.

**Comment by Paul17041993** [comment]
good to mention an issue related to the implementation (or just leave this one open until the commit) so I know when I can test it out...
