### ISSUE TITLE
Wind Generator goes invisible if placed at y≤63 and its base is off-screen

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#4276]
I placed three Wind Generators: the one on the right is at y=64, the other two are at or lower than y=63.

![2017-03-26_20 54 50](https://cloud.githubusercontent.com/assets/6743303/24336501/c8ec787a-1266-11e7-8b22-279b62c36327.png)

Now look up at the sky so that their bases go off-screen.

![2017-03-26_20 55 07](https://cloud.githubusercontent.com/assets/6743303/24336511/e5f819ce-1266-11e7-8c80-8988e0d8d120.png)

**_Using:_** Forge 2254, Mekanism-1.10.2-9.2.2.301, with and without Optifine.

**Comment by thommy101** [comment]
It's not only at 63, it's at every 16 blocks. It's related to Minecraft issue 88176 [1] and 1058 [2]. I've read somewhere a time ago that there is a "fix" for mods to use so that they do render, but I didn't save that. If I found something I'll open a pull request.

[1] https://bugs.mojang.com/browse/MC-88176
[2] https://bugs.mojang.com/browse/MC-1058

**Comment by TehStoneMan** [comment]
Every 16 blocks - Sound like it's related to vertical chunks.
For those not aware of vertical chunks, when a regular chunk is saved to disk, it is further divided up into 16 vertical chunks as part of the file format. Modders generally don't need to worry about these vertical chunks as they only really exists at the file level, and not part of the running code, like regular chunks are.
But maybe the vertical chunks are also used in the world rendering code as well?

**Comment by thommy101** [comment]
It's indeed related to vertical chunks (for those unaware, chunks are rendered in blocks of 16*16*16).
Related link explaining what it does: https://imgur.com/a/Fkh3f
