### ISSUE TITLE
Cables, Pipes and Tubes stop working when unloading the Chunk. (maybe Transporters as well)

### ISSUE THREAD

**Issue by kevdotcom** [aidancbrady/Mekanism#4479]
#### Issue description:
I was just trying to build a new base on multiplayer and used water tanks in between Electric Pumps and an Electrolytic Separator. It went dark so I ran to the old base to go to bed and when I came back to what I built, all connected Pipes, Tubes and Cables didn't work anymore. The water stopped one block after the tanks and I had to replace all Cables, Pipes and Tubes in the area before it worked again. 

Same setup without Tanks: works like a charm.

#### Steps to reproduce:
1. Connect Electric Pumps to Water Tanks (to Electrolytic Separators)
2. Unload the Chunk
3. (Sleep)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 13.20.0.2315
**Mekanism:** 9.3.2.307

**Comment by kevdotcom** [comment]
Actually, it even happens without the Tanks. It seems to happen every time I go far away from what I built.

**Comment by kevdotcom** [comment]
After looking into it some more I found that it stops working right where the next chunk starts.

**Comment by alucard87pl** [comment]
Can confirm, this happens on our multiplayer server as well.

**Comment by marcin212** [comment]
Same problem here:
video: https://www.youtube.com/watch?v=fhsKE3C5s3E&feature=youtu.be

**Comment by thommy101** [comment]
Transporter as well according to #3940

**Comment by Rosethorns** [comment]
I can confirm this bug thoroughly for power.

Energy pipes will stop working connected to mekanism machines, receiver machines are specifically what break power. but a power network powering other rf receivers will not break. Only when mek machines are introduced does power stop being provided when the chunk is reloaded.

The pipes do not appear unconnected and The One Probe shows the energy pipe being full. BUT below normal maximum (1.5krf instead of 2.6krf for example)

**Comment by Ricket** [comment]
Yep my cables keep refusing to deliver power randomly, it always starts at a chunk boundary but then every cable piece after that has to be broken and replaced. Also 1.11.2 9.3.2.307 here (ATM2 modpack).

**Comment by Ricket** [comment]
Happens often. Here's a screenshot of today's incident.

![image](https://user-images.githubusercontent.com/196978/27668735-cc008a54-5c50-11e7-8f59-866aa36c1f28.png)

Right on a chunk border of course.

**Comment by bowmanjd** [comment]
Also having this issue with Mekanism 9.3.2.309 and Forge 13.20.0.2345. I welcome advice.

**Comment by Rosethorns** [comment]
yo @aidancbrady You have seen this yes?

**Comment by aidancbrady** [comment]
Merging with #4507

**Comment by thommy101** [comment]
Reposting from #4507 as some others might get a notification from here:

Can anyone provide a strict reproduction scenario which will lead to this issue? I'd really like to get this solved soon but I've been unable to reproduce anything similar.

If anyone could provide any information, please report it at #4507. Any hints/tips/whatever what could help us would be really appreciated.

**Comment by bowmanjd** [comment]
I won't be much help because I am not using Mekanism currently, but two
bits of information you may find helpful:

   - This (pipes failing to conduct at chunk boundaries) only happened on a
   Forge server, not the client (and neither when opening the client to LAN)
   - Restarting the server always fixed it (in other words, it seemed to
   occur after the Forge server was idle for a while)
   - We didn't notice it after a bit. Could it be that a later upgrade of
   Forge may have fixed it? Just a hunch.

Hope this helps.
Jonathan
