### ISSUE TITLE
Charging pad crash: 1.11.2 (redstone arsenal compatibility)

### ISSUE THREAD

**Issue by kragnoth** [aidancbrady/Mekanism#4485]
While holding any Redstone Arsenal items (had boots on) you will crash to desktop.

#### Steps to reproduce:
1. Have redstone arsenal items in inventory
2. Step on charging pad
3. Crash to desktop

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.11.2 2315
**Mekanism:** 307
**Other relevant version:** 2.2.2.4 redstone arsenal version on 1.11.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]
https://pastebin.com/648tYmQD

I'm not sure if redstone arsenal has a github to post to, if so I will try to post there as well.  I'm thinking it has to do with them trying to separate the redstone flux API from the main mods.

**Comment by HanatakeYurii** [comment]
Report to CoFH there: https://github.com/CoFH/Feedback/issues

**Comment by KingLemming** [comment]
Or you know, don't. Because it's not Redstone Arsenal's fault in any way, shape, or form.

**Comment by kragnoth** [comment]
I'm just at the moment wondering what is at fault.  I just noticed it with redstone arsenal, but I think its because its the only item I can wear that has a charging option in 1.11.2.  If I find the root cause I will report back, for now I'm not sure if I should even leave this open here, as ultimately it looks like a missing capability compatibility between mekanism charging pad, pushing tesla capabilities, to RF based items.  Might even be caused by combining it with mods like energy synergy.  Closing for now, as I don't think its mekanism.

**Comment by KingLemming** [comment]
Ultimately the problem is Tesla and the fact that it even exists at all.

But codewise, here's the issue:
https://github.com/aidancbrady/Mekanism/blob/f277f49b92cd15764dd72f74f1ad6401d58fc364/src/main/java/mekanism/common/tile/TileEntityChargepad.java#L140

That check is going through for some reason, except it really shouldn't be. Those items don't have Tesla capability, and if something it trying to push it on there, it's going to fail spectacularly.

This could be trivially fixed by supporting Forge Energy as the first check in the chain, or by actually supporting the RF API, neither of which attempts to force any capabilities onto items.

**Comment by kragnoth** [comment]
I'll try it with a few tweaks to energy synergy.  Could be he achieves what I want in a way that is incompatible with this.  Thanks for the better insight into the crash KL.
