### ISSUE TITLE
Crash on startup [1.12]

### ISSUE THREAD

**Issue by zackeezy** [aidancbrady/Mekanism#4610]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crash on start up.

#### Steps to reproduce:
1. Load the other mods I have installed with the same versions
2. Watch it crash
3. Some other third thing

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.21.1.2443
**Mekanism:** 9.4.0.318
**Other relevant version:** Mc Version: 1.12

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[pastebin link here](https://pastebin.com/nNYFGgzx)

Is loading the 1.12.1 version in 1.12 a problem? It hasn't been in the past.  If so I can just move to 1.12.1.  But if not I'd love to know what my problem is.

**Comment by thiakil** [comment]
That crash doesn't look like it should be possible.... @thommy101 any ideas?

**Comment by zackeezy** [comment]
[Here's my fml-client-latest.log](https://github.com/zackeezy/RandomStuff/blob/master/fml-client-latest.log)

**Comment by thommy101** [comment]
I agree with you @thiakil, looks impossible, but I'll look into it

**Comment by thommy101** [comment]
Looked through the logs and found this:
`[17:05:01] [main/ERROR] [mekanismgenerators/]: Skipping event FMLPreInitializationEvent and marking errored mod mekanismgenerators since required dependency mekanism has errored
[17:05:01] [main/DEBUG] [FML/]: Bar Step: PreInitialization - MekanismGenerators took 0.000s
[17:05:01] [main/ERROR] [mekanismtools/]: Skipping event FMLPreInitializationEvent and marking errored mod mekanismtools since required dependency mekanism has errored
[17:05:01] [main/DEBUG] [FML/]: Bar Step: PreInitialization - MekanismTools took 0.000s`

Looks like something is going wrong..

**Comment by thiakil** [comment]
And forge seems to be bugging out and still calling the registration event? D:

**Comment by thommy101** [comment]
I would expect Forge to unload tools/generators so the event bus is unloaded, but apparently the bus stays loaded.

**Comment by thommy101** [comment]
@zackeezy Could you look at your mod folder and check if there's a mekanism-somethingsomething-api.jar? If so, remove it and try again ;)

**Comment by zackeezy** [comment]
Yea the api jar was the issue.

**Comment by thommy101** [comment]
Great! Thanks for letting it know :)
