### ISSUE TITLE
Digital Miner silktouch crash/issue

### ISSUE THREAD

**Issue by dakamojo** [aidancbrady/Mekanism#4637]
[crash-2017-08-17_13.37.04-server.txt](https://github.com/aidancbrady/Mekanism/files/1232272/crash-2017-08-17_13.37.04-server.txt)
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Digital Miner in the Deep Dark seems to be hitting something that causes it to crash.  Crash log attached.  This is in the Project Ozone Lite modpack although I manually updated Mekanism.

Since my Digital Miner is chunk loaded everytime I start my game it crashes in a few seconds.

#### Steps to reproduce:
1.  Place Digital Miner in Deep Dark and wait.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2422
**Mekanism:** 1.10.2-9.2.3.97
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

Attached

**Comment by thommy101** [comment]
Reported by @nekoexmachina (#4640)

> #### Issue description:
> I wanted to clear a forest using Digital miner, and it was left in silktouch mode because I've forgot to change that. 
> 
> Its filter was "logWood". It produced a series of unusable unstackable non-textured blocks named "Oak Wood", etc. This blocks, when placed, reverted themselves to regular Oak Woods (every single one of them, including Acacia logs and Pine logs). 
> 
> #### Steps to reproduce:
> 1. Place SilkTouch Digital Miner
> 2. Configure it to harvest Logs
> 3. Behold!
> 
> #### Version (make sure you are on the latest version before reporting):
> **Forge:** 12.18.3.2422
> **Mekanism:** Mekanism-1.10.2-9.2.3.97.jar 
> **Other relevant version:** n/a

The issue is Mekanism implemented it's own `getSilkTouchDrop` as the one from `Block` is protected. The current implementation is a copy of the implementation `Block`, but this would ignore every block which has it's own implementation of `getSilkTouchDrop`. Causing `getSilkTouchDrop` from `BlockRotatedPillar` to be ignored and giving wrong items for harvested logs.

The other crash is caused by a nullpointer in the silktouch code, which points us to a block which doesn't have a item.

**Comment by thiakil** [comment]
I came to the same conclusion (though without looking at those other mods), the silk code just looked a bit odd
