### ISSUE TITLE
Condensentrator arrows are wrong in JEI when showing multiple recipes

### ISSUE THREAD

**Issue by josephcsible** [aidancbrady/Mekanism#4751]
#### Issue description:
When viewing recipes for the rotary condensentrator with JEI, all arrows on each page will point the same way, even if some of the recipes are condensentrating and some are decondensentrating. (This bug does not occur if only one recipe per page is visible.)

#### Steps to reproduce:
1. Right-click a rotary condensentrator 
2. Click the arrow with tooltip "Show Recipes"
3. Make sure your screen is big enough, or your GUI size small enough, to see at least two recipes per page

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.0.2503
**Mekanism:** 9.4.1.326
**Other relevant version:** JEI 4.8.0.105

![2017-10-07_11 32 56](https://user-images.githubusercontent.com/16061266/31309435-12d5ee54-ab54-11e7-83eb-0127eaca0353.png)

**Comment by thommy101** [comment]
Looked a bit at this issue, it seems a misunderstanding of how JEI works. Some technical explanation will follow:

JEI uses `IRecipeCategory` (RotaryCondensentratorRecipeCategory) classes to render the recipes. It has a method `drawExtras(Minecraft)` which in our case renders the arrow for the condensentrating & decondensentrating. This uses the by JEI provided `IRecipeWrapper` (RotaryCondensentratorRecipeWrapper). The problem is, that (what it seems) the recipes is only set once when stuff changes. This together with JEI only using one object of the `IRecipeCategory` causes the recipe we save is being overwritten with the one on the bottom of the screen as that is set directly after it, causing it to always render as decondensentrating.

A tldr:
The method `setRecipe` is not intended to store data in the `IRecipeCategory`, only update the `IRecipeLayout` we receive with the stuff from `IRecipeWrapper`.

**Comment by thommy101** [comment]
The new and improved JEI integration for the Rotary Condensentrator:

![afbeelding](https://user-images.githubusercontent.com/1036527/31317941-0c1d1a46-ac4a-11e7-9805-5ffa81c7d503.png)

![afbeelding](https://user-images.githubusercontent.com/1036527/31317948-22bd5e50-ac4a-11e7-890e-8b8ba9f9a059.png)
