### ISSUE TITLE
[1.12] Crash on Gameload

### ISSUE THREAD

**Issue by MasterEnderman** [aidancbrady/Mekanism#4963]
#### Issue description:
Minecraft doesn't load at all and crashes during the loadingscreen

#### Steps to reproduce:
1. install Forge, mekanism and mekanism generators
2. start the pack
3. crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.2.2623
**Mekanism:** 9.4.3.330
**Mekanism Generators:** 9.4.3.330

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/ViVM2KQY

**Comment by thecow275** [comment]
Seems to me that a mod you use has outdated api i have tried forge 14.23.2.2623 and only Mekanism and no crashing on load and 

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (mekanism)
Caused by: java.lang.NoClassDefFoundError: mekanism/api/MekanismAPI$BoxBlacklistEvent

in your pastebin tells me that is the issue possibly but not 100% certain but if you remove mods 1 By 1 and see if it crashes and when it stops crashing you have found that which mod is makin mekanism crash with its outdated api

**Comment by thiakil** [comment]
You seem to have a mod that's bundling our API (a no-no to begin with), but it's bundling the 1.7 version.

So yeah, you'll need to remove mods til it stops, or add them until it does, as your reproduction steps do not match your log.
