### ISSUE TITLE
AE2 P2P tunnels don't connect to mekanism cables

### ISSUE THREAD

**Issue by justinrusso** [aidancbrady/Mekanism#5014]
#### Issue description:
When right clicking the p2p tunnel, the tunnel turns to an FE tunnel. The pipes connect fine, but once you pair them using the memory card, the side you are setting disconnects from the Mekanism cables.

Reference: https://github.com/Darkosto/SevTech-Ages/issues/1973

#### Steps to reproduce:
1. Place an AE2 cable, and a p2p on 2 sides
2. Right click the tunnels with mekanism cables to turn them into FE tunnels and place down a mekanism cable in front of each end of the terminal. Note that both currently are connecting to the tunnel.
3. Get a memory card and shift right click one tunnel and right click the other. Note that now the one you right clicked has disconnected from the mekanism cable.

![image](https://user-images.githubusercontent.com/25138621/39096324-6703dec4-461c-11e8-9ba4-a07a37033ca8.png)

#### Version:
**Minecraft:** 1.12.2
**Forge:** 14.23.3.2669
**Mekanism:** 1.12.2-9.4.3.330
**AE2:** rv5-stable-11

#### Logs:

I can get a log if needed, but this was found as an excerpt:
```[AE2:C]: Problem detected when processing IMC add-p2p-attunement-forge-power from mekanism```

**Comment by artdude543** [comment]
But the tunnel does not push power to the cable at all.
![image](https://user-images.githubusercontent.com/1885466/39216406-6daf5a3e-4813-11e8-9a92-c2b3924d43a6.png)


When using another cable from another mod.
![image](https://user-images.githubusercontent.com/1885466/39216418-7a1b8cb6-4813-11e8-92ae-a9964bfa9987.png)

This is still a valid issue and I don't think this is the fault from AE2.

**Comment by thiakil** [comment]
Contrary to my initial thought the cable won't accept power from an unconnected side. The AE tunnel is returning false for both `canReceive` and `canExtract`. That is a failure on their side, as it seems like the output side loops back on itself for some strange reason instead of looking to the input end.

You can use an energy cube as a buffer.

**Comment by artdude543** [comment]
@thiakil from the linked issue above AE are telling me that it's Meka at fault here using a wrong name for the IMC call. Could you look at this issue again, please?

**Comment by thiakil** [comment]
The imc thing is unrelated to this issue (that's to do with right clicking the tunnels to tune)

As for the output not connecting, that's just how our cables work. They do the work normally, but will accept power if the other device at least says it is a producer or consumer

**Comment by artdude543** [comment]
So is there anything that could be done for this in regards to the issue? With a large modpack using the mod, this issue is causing issues for people wanting to make their systems work. It's also gating people at having to use RS over AE because of this issue and the limited transfers we offer in SevTech. Is there any way the devs of the two mods can talk about this and come to a resolution?

As you blame them and they're blaming you. So I'm kinda on the gate here on trying to help with getting this resolved. I'm not trying to sound all loud but it's a pain when your stuck in a blame game 🙁

**Comment by thiakil** [comment]
Well both sides are essentially saying the same thing, just with opposite push/pull requirements. They rely on push, we rely (mostly) on pull to get it into the cable.

A buffer (such as an energy cube) can be used on the output side.

**Comment by justinrusso** [comment]
so why does every other mod seem to work fine?

**Comment by justinrusso** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1912

**Comment by MadSciSlack** [comment]
Six years later and this still doesn't work?  I've also had no luck using energy cubes as a buffer.  This is just sad, and like many people; I have no choice but to go to refined storage.

I have 200 mods, many tech based, in my modpack.  AE2 is the only thing that doesn't work with Mekanism Universal Cables.  Food for thought...
