### ISSUE TITLE
Mek Generators Crash with Astral Sorcery 1.9.0

### ISSUE THREAD

**Issue by BrisingrAerowing** [aidancbrady/Mekanism#5081]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crashes with Astral Sorcery 1.9.0

#### Steps to reproduce:
1. Run Mekanism Generators and AS 1.9.0 together
2. Crash on startup

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2705
**Mekanism:** 9.4.11.346
**Other relevant version:** 1.9.0

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
See the log in HellFirePVP/AstralSorcery#749. I get the same crash.

#### Other

The fact that [this method](https://github.com/aidancbrady/Mekanism/blob/1.12/src/main/java/mekanism/generators/common/item/ItemBlockGenerator.java#L91) doesn't check the generator type for `null` seems to be the root of the issue, as AS is looping over items and getting their stack sizes for one of its features.

**Comment by Sacrificialgaming** [comment]
I can say this crash is legit as I just had it happen to me

**Comment by tlitookilakin** [comment]
It hasn't crashed for me (ironically because another mod is causing the serverStartEvent to fail), but I've been getting the same error when closing a world, which hardlocks the game.

Running Mekanism 9.4.11.346 on forge 14.23.3.2694, also tested with forge 14.23.4.2707
No crash log, but [here's the client log of me starting the game, opening a world, and closing it](https://www.dropbox.com/s/1a9b0cn9erfnk2s/latest.log?dl=0).

`Exception caught during firing event net.minecraftforge.event.AttachCapabilitiesEvent@4cadccd3:
java.lang.NullPointerException: null
	at mekanism.generators.common.item.ItemBlockGenerator.getItemStackLimit(ItemBlockGenerator.java:95) ~[ItemBlockGenerator.class:?]
	at net.minecraft.item.ItemStack.func_77976_d(ItemStack.java:248) ~[aip.class:?]
	at hellfirepvp.astralsorcery.common.enchantment.amulet.EnchantmentUpgradeHelper.isItemBlacklisted(EnchantmentUpgradeHelper.java:176) ~[EnchantmentUpgradeHelper.class:?]`

interestingly, this also seems to affect RFTools Dimensions-

`Failed to create a dimlet for block mekanismgenerators:generator! Please report to the correct mod!
java.lang.NullPointerException: null
	at mekanism.generators.common.item.ItemBlockGenerator.getItemStackLimit(ItemBlockGenerator.java:95) ~[ItemBlockGenerator.class:?]
	at net.minecraft.item.ItemStack.func_77976_d(ItemStack.java:248) ~[aip.class:?]`

**Comment by thiakil** [comment]
Not sure why things are trying to make wildcard items for it, but it should no longer crash.

**Comment by PlasticPhoenix** [comment]
Yes, I have updated AS and Mekanism to the current releases and it is working fine so far. No crashes on MC loadup, world load or save. Running on Forge 2707 in SP mode.
