### ISSUE TITLE
Digital Miner bug - new data

### ISSUE THREAD

**Issue by ghohenzollern** [aidancbrady/Mekanism#5110]
This is a new Issue with information to add to closed tickets https://github.com/aidancbrady/Mekanism/issues/3718 and https://github.com/aidancbrady/Mekanism/issues/4226

We're experiencing the disappearing Digital Miner bug. Two things to add which may help lead to a solution:

1. We were able to reproduce the bug while running Mekanism ONLY, eliminating the possibility that it's a modcross bug.
2. We got it on video. https://youtu.be/BEy24f7ChxI

I've left the same comment on #4226, in case it's more useful to reopen the cold case. 

Thanks

**Comment by thiakil** [comment]
Can you please link to the *specific* section(s) of the video? I'm not watching a 30 min video.

**Comment by BlueAgent** [comment]
Here's a summary of the video:
- [00:00](https://youtu.be/BEy24f7ChxI?t=0s) Loads modpack while telling a story of their history playing modded minecraft.
- [05:45](https://youtu.be/BEy24f7ChxI?t=5m45s) Sets up digital miner to replace diorite with stone, and then walks far away discussing dissapearing bins also being an issue.
- [07:48](https://youtu.be/BEy24f7ChxI?t=7m48s) Starts walking back while discussing problems associated with refunding items to players on a server.
- [09:08](https://youtu.be/BEy24f7ChxI?t=9m8s) Arrives back to find that the digital miner hasn't dissapeared, realising that the miner was inactive the whole time. Sets up the miner to be active this time and walks far away again.
- [11:05](https://youtu.be/BEy24f7ChxI?t=11m05s) Starts walking back while talking about what else they could be doing instead of making this bug report video.
- [12:13](https://youtu.be/BEy24f7ChxI?t=12m13s) Arrives back to find the digital miner has dissapeared. Goes through the process of refunding their digital miner.
- [14:28](https://youtu.be/BEy24f7ChxI?t=14m28s) Searches Google to find the existing issue.
- [15:48](https://youtu.be/BEy24f7ChxI?t=15m48s) Backs up all the current mods into a folder named "aidancbradyisannoying". Then adds Mekanism, Mekanism Tools and Mekanism Generators back in.
- [24:17](https://youtu.be/BEy24f7ChxI?t=24m17s) Sets up a digital miner on a new world with a heat generator on a chunk boundary.
- [31:02](https://youtu.be/BEy24f7ChxI?t=31m02s) Starts walking away from the setup.
- [33:09](https://youtu.be/BEy24f7ChxI?t=33m09s) Starts walking back.
- [34:20](https://youtu.be/BEy24f7ChxI?t=34m20s) Finds that the digital miner has dissapeared. Exclaims that it's a Mekanism problem and demands that it be fixed.

Notes/observations from watching the video:
- Occurs just with Mekanism.
- Happens when the Digital Miner is on a chunk bounary
- Walking/flying away will cause it to dissapear.

I think teleporting away which unloads the chunks all at once probably won't reproduce it, it'd need to be the digital miner gradually unloaded, such that at some point it's partially loaded as the player moves away from it.

Suggestions on ways to improve the bug report in the future:
- Keep it succinct.
- Focus only on the minimum way to reproduce the problem.
- Include a text description of the steps required to reproduce the bug in the issue itself.
- Leave out any passive agression and entitlement. This being an open source project which contributors work on for free in their spare time. If you want a bug to be fixed, creating a good reproducible bug report is very helpful, or making a pull request with the bugfix.

**Comment by thiakil** [comment]
Thanks for taking the time to sift through all that cruft BlueAgent!

Really, there seems to be no new info here, it has already been mentioned in the linked issues that chunk borders are likely the issue. *You should never be placing multiblocks on chunk borders!*

> 11:05 Starts walking back while talking about what else they could be doing instead of making this bug report video.
> 15:48 Backs up all the current mods into a folder named "aidancbradyisannoying". Then adds Mekanism, Mekanism Tools and Mekanism Generators back in.
> 34:20 [..]. Exclaims that it's a Mekanism problem and demands that it be fixed.

These are easy ways to get devs to not care about your bug report. Has no one ever taught you that putting people on the defensive / annoying them is highly unlikely to get them to do what you want?!

That whole video should have started at the 31 min mark with using *only mekanism*.

**Comment by ghohenzollern** [comment]
I'm afraid I cannot justify the time to further edit videos that are
intended for such a small audience.  If I am to spend the time cutting down
the video (assuming this does not get my bug reports ignored because I
could have faked the problem)  then I will have to release it to a wider
audience to justify the time I spend on it.  Is that what you would prefer
in future?  I have a 43 minute video about bins clipping through ceilings
when harvested even if the ceiling is many blocks thick.  Currently it is
private, but I would be willing to cut it down, but then I'd have to make
it public to justify the extra time spent.

**Comment by ghohenzollern** [comment]
If placing a digital miner on a chunk boundary (or a multiblock in general)
is a problem that cannot be gotten around, it shouldn't be too hard to
print a warning in chat when a player does so.  If you did that, you'd be
in the vanguard of mod-makers, as I've never seen it done before and I've
tested literally hundreds of different mods.

**Comment by thiakil** [comment]
> If I am to spend the time cutting down the video

You still seem to be missing the point *that it was not necessary to record all the fluff to begin with*

> then I will have to release it to a wider audience to justify the time I spend on it

No. No No No NO. You want to get your bug solved quickly? Optimise **_MY_** time, not yours. This might sound selfish, but if you're not going to invest the time to make it easy for me (and instead do the opposite), why would I want to help you?

> I have a 43 minute video about bins clipping through ceilings

Why on earth is it 43 minutes? Does your PC run at 1 frame per minute? Did you retell your life story?

It literally doesn't need to be anything fancy. I don't give a rats arse if your audio isn't perfect, or you stutter or whatever. If you are doing anything more than recording and *maybe* adding voice over you're doing it wrong. If your video is longer than a couple of minutes, you're probably doing it wrong.

> it shouldn't be too hard to print a warning in chat when a player does so

Sure, that's a band aid solution, though I'd rather fix the actual issue before resorting to immersion breakage.

**Comment by pyscho974** [comment]
so does it only happen on chunk boundries where the digi miner sits in 2 seperate chunks or does it also do this when in middle of a chunk?.. ill need to test this myself probly but was just curious .. i know a server that it happens frequently on .

**Comment by thiakil** [comment]
What do you mean by "immediately"? Did it do it while you were watching?

No that config file doesn't really relate, it only sets the limits of chunkloading

**Comment by yaroslav4167** [comment]
Yes, the miner disappeared immediately after pressing the start.

**Comment by thiakil** [comment]
I have no idea how that'd happen. Would need an exact reproduction scenario.

**Comment by yaroslav4167** [comment]
I'll try to reproduce myself locally.

**Comment by yaroslav4167** [comment]
It did not happen to recreate this error. Apparently, it affected something else. If I succeed, I will try to assemble a special assembly for testing.

**Comment by Sleeeper** [comment]
Could it be that it mines itself (and thus disappear) because it has "Ore" in the name?

**Comment by thiakil** [comment]
No

**Comment by racinmat** [comment]
So does a use of chunk loader fix this or is the only solution not to but the digital miner on chunk borders? I just look for any way to prevent that happening, because it seems that its issue of minecraft itself, not the mod.

**Comment by thiakil** [comment]
As far as we know it is often related to being placed on chunk borders. The latest release (9.6) contains a fix for the ChunkLoader upgrade which may help this issue.

**Comment by ghohenzollern** [comment]
Oh god, folks are still trying to tell me I reported this bug the wrong
way?  I stopped paying attention to this long ago.  No time.  I don't
bother reporting bugs with mekanism anymore, because apparently I just
can't do it right, and I don't have time to even read your posts on how I
do it wrong.  I bet bins are still clipping through the ceiling when placed
against it and then harvested.  Have fun with your buggy mod.  You want
community members to help you troubleshoot your mod, show us some respect
when we bother to take the time to instead of telling us we're doing it
wrong.
