### ISSUE TITLE
Garden Cloche / Cardboard Box disappearing

### ISSUE THREAD

**Issue by ke5hxf** [aidancbrady/Mekanism#5290]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*
SEARCH: nothing
#### Issue description:
MODPACK: ENIGMATICA2:EXPERT
Placing a Cardboard Box (Mekanism) on a Garden Cloche (Immersive Engineering) deletes both the cloche, all it's contents and the cardboard box. (reporting issue to both mod groups)

#### Steps to reproduce:
1. Place Garden Cloche in world, fill with dirt, potato and bone meal,  
2. Supply with water and power.
3. Place a Cardboard box onto the Garden Cloche.
4. Check every where for the drop.

#### Version (make sure you are on the latest version before reporting):
**Forge:** Mod Loader: 8.0.99.99
**Minecraft Forge:** 14.23.5.2781
**Mekanism:** 1.12.2-9.4.13.349
**Other relevant version:** Immersive Engineering: 0.12-88

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

Willing to provide video if needed?

**Comment by dizzyd** [comment]
I reproduced this with IE and Mek in a standalone pack. It's worth noting that it only occurs when the block is larger than a single block. Also notable is that after setBlockState on a problematic block, the block state is AIR.

**Comment by dizzyd** [comment]
Hi @ke5hxf - I've fixed this in my fork and submitted a PR to this repo. The problem is that IE actually triggers it's own setBlockState whenever a cloche (or other double-high block) is broken - the work around is to first set the block in question to air, then place the cardboard box. Ideally we wouldn't have to do this two-step, but double-blocks are such a hack that I think this is a reasonable tradeoff.

I'll cut a new release of my fork tomorrow with this change.

**Comment by thiakil** [comment]
Based on discussion with the author of IE, multiblock devices have been blacklisted for the cardboard box.

Even with working around the disappearing act, it won't come out of the box properly.

![2019-03-11_23 31 57](https://user-images.githubusercontent.com/1788847/54140916-9ee68480-445f-11e9-83aa-815adfec6068.png)
After removing the box, there is no 2nd block and your cloche will probably not work right without it.
