### ISSUE TITLE
Game Crashes When I Try To Craft With Basic Liquid Tank

### ISSUE THREAD

**Issue by Drac0logist** [aidancbrady/Mekanism#5293]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Every time i put a basic liquid tank in a crafting table to craft an item my game crashes and will keep crashing every time i log back into my world until i break the crafting table and re place and then take the tank out.

#### Steps to reproduce:
1.Put basic liquid tank in a tinkers crafting table
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2781
**Mekanism:** 1.12.2-9.4.17
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/2j5CwZ5X
[gist/pastebin/etc link here]

**Comment by dizzyd** [comment]
Hi @Drac0logist - based on the version number, I think you might be reporting this against my fork, not the mainline. If this is true, please re-open this issue at the [repo](https://github.com/dizzyd/Mekanism/issues) so we can not bother the mainline with something that might be my own bug. :)

That aside, you seem to be playing a pack with a _lot_ of mods and I can't reproduce this with just Tinker's Construct and Mekanism. If you can provide:
1. Screenshot of the tinker's construct tables and surrounding area, just before you place the tank
2. The packname (or at least manifest.json)

These items would be super helpful in reproducing this.

**Comment by thiakil** [comment]
@dizzyd please rename your fork to not use the Mekanism name (unless you have direct permission from Aidan that I'm not aware of)

**Comment by dizzyd** [comment]
@thiakil - I'm operating under the terms of the MIT license, as described in the README: 

> As such, I have decided to license Mekanism under the MIT license, allowing for anyone with an interest in the project to fork/pull/distribute.

I have no desire to cause confusion/animosity, but given that it's been nearly a year since the last release of Mekanism and no ongoing patching or acceptance of outside patches, I'm not sure what else to do. If this mainline starts accepting patches and cutting releases again, I'm happy to stop working on my fork.

**Comment by thiakil** [comment]
@dizzyd though I didn't specify anything about the licence being in violation, that does only apply to the code itself, not the name or any copyright. Names fall under copyright. I am surprised curse let your name through though, given the trouble I had doing similar a while back with another project. 

I ask because of issues exactly like this that get reported here, making it more difficult to actually sort through them and work on things. You wanna be a dick and fragment things, the least you could do is make things clearer for the inevitable few who miss the tiny suffix. 

As for your fork in general, did you even attempt to communicate with us prior to releasing a fork? Did you open pull requests before releasing? (I ask because I haven't looked into timings to that level of detail)

**Comment by dizzyd** [comment]
The question at hand is the name - the copyright is part of the license. Given that this is open source work, it's arguably not commerce and thus the name would not fall under common-law trademark. However, IANAL, so I'll shut up now. :)

I don't _want_ to fragment things; I've been submitting PRs and they've either been closed without further discussion (see #5282) or just ignored (see #5291, #5292) -- as were a host of other PRs from a large number of people. The timeline was that I submitted #5282 on Feb 22, nothing happened for a several days (and had not happened for 6+months on any other PR) I decided to open the fork Feb 25, so I could at least use my branch in my modpack. So yes, I tried to help the original project first.

I would greatly prefer not to be maintaining a fork, but given the lack of activity and releases from this project and the amount of arbitrary gatekeeping on PRs/issues, I don't have much choice. I would be happy to take over maintainership of this project if you don't want to do it. Otherwise, I will change the name of my fork and we'll consider the issue resolved.

**Comment by thiakil** [comment]
> The question at hand is the name - the copyright is part of the license. Given that this is open source work, it's arguably not commerce and thus the name would not fall under common-law trademark. However, IANAL, so I'll shut up now. :)

I'm not talking about trade mark... That said, I'm not American, so perhaps my country's copyright differs in this regard.

> closed without further discussion (see #5282)

You didn't even respond to my comment there, so that's on you. I gave you my reasons, there's also another open PR from someone I trust regarding the mappings. This (OP) issue is why you cant just remove the rendering check, so what exactly are you wanting with "further discussion"??

Mappings are super low priority as they mean nothing in the compiled jar, and can cause many issues if not done right (though thankfully those breaking changes are rare). They're just names.

Forge version updates - only important for testing purposes, not as much of a hassle as mappings.

> just ignored (see #5291, #5292)

That's been less than a week, and certainly *after* you've released a fork... You realise this is a hobby project, and that we might only be able to work on it on weekend and when we have the motivation to do so (we're full time developers for our day jobs). They need to be tested properly prior to being merged.

So even from your own timeline, you opened one pr, and *3 days* without a response released a fork...

**So, moving on how can we do better?**

It would be helpful for the code based PRs for them to be tested, and those tests listed as a comment on the PR. 

e.g. #5291 listing other mod's blocks tested, if any mekanism blocks were tested, etc.

e.g. the JEI gas rendering ones - they need to be tested with external mods that add gasses, like JAOCPA and MMD's Base Metals

**Comment by pupnewfster** [comment]
Just slightly interjecting here because of the JEI gas rendering. It works properly with the latest version of "Mekanism Ores" (Which added support for actually coloring the slurry, including in pressurized tubes not just for jei), and it will work with JAOPCA when https://github.com/TheLMiffy1111/JAOPCA/pull/110 gets merged. Note: Currently JAOPCA doesn't render properly in JEI, AND also doesn't render the correct color in pressurized tubes.

**Comment by dizzyd** [comment]
We could argue about proper procedures for forking and whether I waited long enough until the cows come home -- but the reality is that this project has been mostly dead for 6-8 months from a code perspective and even longer from a release perspective. I followed the guidelines for forking and attribution and have done my best to resolve issues in a timely manner while also moving the code forward.

I will be changing the name of the fork moving forward -- when I can do it without breaking everyone's world. It's disappointing to me that you've taken a protectionist approach to maintaining a mod as great as Mekanism -- you'd get a lot further if you were more collaborative in issues/PRs and open-minded instead of attacking people trying to help.

Good luck.

**Comment by thiakil** [comment]
Forking always causes drama, especially when little communication is involved. And yes, I am often an arsehole.

I am happy for you to help out, but *here* on this repo, where the releases can be made on Curse under Aidan's account (No, I don't get any curse points from it).

> when I can do it without breaking everyone's world

Leave the mod id if you want (though there are events for remapping that) but changing the actual project name won't break anything.

> It's disappointing to me that you've taken a protectionist approach to maintaining a mod as great as Mekanism -- you'd get a lot further if you were more collaborative in issues/PRs and open-minded instead of attacking people trying to help.

It's about keeping standards up. Yes I can be a hardass, but I don't exactly have time to handhold.

**Comment by sdras** [comment]
Can you please reread the README posted? 

> Some people really don't like others to review or distribute their mods, something which I honestly don't understand. You are the ones who help get this mod into the Minecraft community's hands, which seems like a good thing from my perspective. As long as you follow the terms laid out in the license below, go right ahead. I honestly just don't want you messaging me on IRC or on the forums, asking my permission. If you need proof, provide a link to this page.

Some of the actions taken on this repo in the last week are far from community standards, and seem to be more ego-driven then collaborative. 

Please stop talking down to people trying to contribute, and covering up/going in another direction when people are actively trying to help (with good code to boot). Open source benefits us all by working together.

**Comment by thiakil** [comment]
You realise that releasing a fork under a separate project is the opposite of collaboration, right?

And I'm pretty sure the quoted section of the readme is about the 'can I use your mod in my pack' question which was more relevant before the days of Curse
